// Lecturas auxiliares. Las consultas originales de las secciones CAC se conservan.
export const EXISTENCIA_PACIENTE_SQL = `SELECT GENPACIEN.OID, PACPRINOM, PACSEGNOM, PACPRIAPE, PACSEGAPE,
PACTIPDOC, PACNUMDOC, GPAFECNAC, GEFEAFEAPB AS [Fecha de afiliación a la EPS que registra],
GPASEXPAC, GPATIPPAC,
GENOCUPACION, GENPOBESP, DGNMUNICIPIO, GENDETCON,
(SELECT GENDEPTO FROM GENMUNICI WHERE OID = GENPACIEN.DGNMUNICIPIO) DEPARTAMENTOID,
TELEFONO.OID TELEFONOID, TELEFONO.PACTELEFONO
FROM GENPACIEN
OUTER APPLY (SELECT TOP 1 OID, PACTELEFONO FROM GENPACIENT
WHERE GENPACIENT.GENPACIEN = GENPACIEN.OID
ORDER BY CASE WHEN PACTELPRINC = '1' THEN 0 ELSE 1 END, OID) TELEFONO
WHERE PACTIPDOC = @PACTIPDOC AND PACNUMDOC = @PACNUMDOC`;

export const BLOQUEAR_REGISTRO_SQL = `SELECT TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, IDETIPOTRATAMIENTO
FROM CACIdentificacionGeneral WITH (UPDLOCK, HOLDLOCK)
WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO AND NUMDOCUSUARIO = @NUMDOCUSUARIO AND CODCIE10 = @CODCIE10`;

export const RECURSOS_PACIENTE_SQL = {
  ocupaciones: `SELECT OID id, CAST(OID AS varchar(20)) codigo, DGONOMBRE nombre
FROM GENOCUPACION ORDER BY DGONOMBRE`,
  gruposPoblacionales: `SELECT OID id, CAST(OID AS varchar(20)) codigo, GPENOMBRE nombre
FROM GENPOBESP ORDER BY GPENOMBRE`,
  eps: `SELECT GENDETCON.OID id, ISNULL(GEENENTADM.ENTCODIGO, '') codigo,
GEENENTADM.ENTNOMBRE + CASE WHEN GENDETCON.GDENOMBRE IS NULL OR GENDETCON.GDENOMBRE = '' THEN '' ELSE ' · ' + GENDETCON.GDENOMBRE END nombre
FROM GENDETCON
INNER JOIN GENCONTRA ON GENCONTRA.OID = GENDETCON.GENCONTRA1
INNER JOIN GEENENTADM ON GEENENTADM.OID = GENCONTRA.DGNENTADM1
WHERE GENDETCON.GDEBLOPLA = 0
ORDER BY GEENENTADM.ENTNOMBRE, GENDETCON.GDENOMBRE`,
  departamentos: `SELECT OID id, DEPCODDEP codigo, DEPNOMDEP nombre
FROM GENDEPTO ORDER BY DEPNOMDEP`,
  municipios: `SELECT OID id, MUNCODDEMU codigo, MUNNOMMUN nombre, GENDEPTO padreId
FROM GENMUNICI ORDER BY MUNNOMMUN`,
} as const;

export const ACTUALIZAR_PACIENTE_SQL = `UPDATE GENPACIEN SET
PACPRINOM = @PACPRINOM, PACSEGNOM = @PACSEGNOM, PACPRIAPE = @PACPRIAPE,
PACSEGAPE = @PACSEGAPE, GPAFECNAC = @GPAFECNAC, GEFEAFEAPB = @GEFEAFEAPB,
GPASEXPAC = @GPASEXPAC,
GPATIPPAC = @GPATIPPAC, GENOCUPACION = @GENOCUPACION, GENPOBESP = @GENPOBESP,
DGNMUNICIPIO = @DGNMUNICIPIO, GENDETCON = @GENDETCON
WHERE OID = @OID AND PACTIPDOC = @PACTIPDOC AND PACNUMDOC = @PACNUMDOC`;

export const BLOQUEAR_PACIENTE_GEN_SQL = `SELECT OID FROM GENPACIEN WITH (UPDLOCK, HOLDLOCK)
WHERE OID = @OID AND PACTIPDOC = @PACTIPDOC AND PACNUMDOC = @PACNUMDOC`;

export const BLOQUEAR_IDENTIDAD_PACIENTE_SQL = `SELECT OID FROM GENPACIEN WITH (UPDLOCK, HOLDLOCK)
WHERE PACTIPDOC = @PACTIPDOC AND PACNUMDOC = @PACNUMDOC`;

export const BLOQUEAR_IDENTIDAD_CAC_SQL = `SELECT CODCIE10 FROM CACIdentificacionGeneral WITH (UPDLOCK, HOLDLOCK)
WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO AND NUMDOCUSUARIO = @NUMDOCUSUARIO`;

// Los demás campos de GENPACIEN conservan sus valores predeterminados en Dinámica.
export const CREAR_PACIENTE_SQL = `INSERT INTO GENPACIEN
(PACNUMDOC, PACTIPDOC, PACPRINOM, PACSEGNOM, PACPRIAPE, PACSEGAPE,
GPAFECNAC, GEFEAFEAPB, GPASEXPAC, GPATIPPAC, GENOCUPACION, GENPOBESP,
DGNMUNICIPIO, GENDETCON)
OUTPUT INSERTED.OID
VALUES
(@PACNUMDOC, @PACTIPDOC, @PACPRINOM, @PACSEGNOM, @PACPRIAPE, @PACSEGAPE,
@GPAFECNAC, @GEFEAFEAPB, @GPASEXPAC, @GPATIPPAC, @GENOCUPACION, @GENPOBESP,
@DGNMUNICIPIO, @GENDETCON)`;

export const TELEFONO_PRINCIPAL_SQL = `SELECT OID, PACTELEFONO FROM GENPACIENT
WHERE GENPACIEN = @GENPACIEN AND PACTELPRINC = '1'`;

export const ACTUALIZAR_TELEFONO_SQL = `UPDATE GENPACIENT SET PACTELEFONO = @PACTELEFONO
WHERE OID = @OID AND GENPACIEN = @GENPACIEN AND PACTELPRINC = '1'`;

export const CREAR_TELEFONO_SQL = `INSERT INTO GENPACIENT
(GENPACIEN, PACTELEFONO, PACTIPTEL, PACTELPRINC)
VALUES (@GENPACIEN, @PACTELEFONO, 1, '1')`;
