// SQL suministrado: conservar expresiones, joins y filtros originales.
import { CampoCac } from '../../presentation/dtos/cac.dto';
export interface ConsultasSeccion {
  tabla: string;
  campos: readonly CampoCac[];
  select: string;
  insert: string;
  update: string;
}
export const CONSULTAS_CAC: readonly ConsultasSeccion[] = [
  {
    tabla: 'CACIdentificacionGeneral',
    campos: ['TIPDOCUSUARIO', 'NUMDOCUSUARIO', 'CODCIE10', 'IDETIPOTRATAMIENTO'],
    select:
      'SELECT TIPDOCUSUARIO ,NUMDOCUSUARIO ,CODCIE10 ,IDETIPOTRATAMIENTO  FROM CACIdentificacionGeneral WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO   AND NUMDOCUSUARIO = @NUMDOCUSUARIO  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO [dbo].[CACIdentificacionGeneral]  (TIPDOCUSUARIO,NUMDOCUSUARIO ,CODCIE10,IDETIPOTRATAMIENTO) VALUES(@TIPDOCUSUARIO, @NUMDOCUSUARIO,@CODCIE10, @IDETIPOTRATAMIENTO)',
    update:
      'UPDATE [dbo].[CACIdentificacionGeneral]  SET TIPDOCUSUARIO = TIPDOCUSUARIO, NUMDOCUSUARIO = NUMDOCUSUARIO , CODCIE10 = CODCIE10 ,IDETIPOTRATAMIENTO= IDETIPOTRATAMIENTO \r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO   AND NUMDOCUSUARIO = @NUMDOCUSUARIO  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACDiagnosticoEstadificacion',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'NOMNEOPLASIA',
      'CANPRIORIZADO',
      'INDINCIDENCIA',
      'EDADDX',
      'FECREMMEDICO',
      'FECINGINST',
      'TIPESTUDIODX',
      'MOTSINHISTOPAT',
      'FECMUESTRAHISTO',
      'FECINFORMEHISTO',
      'CODIPSCONFIRM',
      'FEC1RACONSULTA',
      'HISTOTUMORMUESTRA',
      'GRADIFTUMOR',
      'ESTADTUMORSOLIDO',
      'FECESTADIFICACION',
      'MAMAHER2PRETRAT',
      'MAMAFECHER2',
      'MAMARESHER2',
      'COLESTADDUKES',
      'FECESTADIFICACIONDUKES',
      'LINFESTADIFICACION',
      'PROSTESCALAGLEASON',
      'PEDCLASIFRIESGO',
      'PEDFECCLASIFRIESGO',
      'OBJTRATINICIAL',
      'OBJINTERVPERIODO',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, NOMNEOPLASIA, CANPRIORIZADO,\r\n    INDINCIDENCIA, EDADDX, FECREMMEDICO, FECINGINST, TIPESTUDIODX,\r\n    MOTSINHISTOPAT, FECMUESTRAHISTO, FECINFORMEHISTO, CODIPSCONFIRM,\r\n    FEC1RACONSULTA, HISTOTUMORMUESTRA, GRADIFTUMOR, ESTADTUMORSOLIDO,\r\n    FECESTADIFICACION, MAMAHER2PRETRAT, MAMAFECHER2, MAMARESHER2,\r\n    COLESTADDUKES, FECESTADIFICACIONDUKES, LINFESTADIFICACION, PROSTESCALAGLEASON,\r\n    PEDCLASIFRIESGO, PEDFECCLASIFRIESGO, OBJTRATINICIAL, OBJINTERVPERIODO\r\nFROM CACDiagnosticoEstadificacion\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACDiagnosticoEstadificacion (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, NOMNEOPLASIA, CANPRIORIZADO,\r\n    INDINCIDENCIA, EDADDX, FECREMMEDICO, FECINGINST, TIPESTUDIODX,\r\n    MOTSINHISTOPAT, FECMUESTRAHISTO, FECINFORMEHISTO, CODIPSCONFIRM,\r\n    FEC1RACONSULTA, HISTOTUMORMUESTRA, GRADIFTUMOR, ESTADTUMORSOLIDO,\r\n    FECESTADIFICACION, MAMAHER2PRETRAT, MAMAFECHER2, MAMARESHER2,\r\n    COLESTADDUKES, FECESTADIFICACIONDUKES, LINFESTADIFICACION, PROSTESCALAGLEASON,\r\n    PEDCLASIFRIESGO, PEDFECCLASIFRIESGO, OBJTRATINICIAL, OBJINTERVPERIODO\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10, @NOMNEOPLASIA, @CANPRIORIZADO,\r\n    @INDINCIDENCIA, @EDADDX, @FECREMMEDICO, @FECINGINST, @TIPESTUDIODX,\r\n    @MOTSINHISTOPAT, @FECMUESTRAHISTO, @FECINFORMEHISTO, @CODIPSCONFIRM,\r\n    @FEC1RACONSULTA, @HISTOTUMORMUESTRA, @GRADIFTUMOR, @ESTADTUMORSOLIDO,\r\n    @FECESTADIFICACION, @MAMAHER2PRETRAT, @MAMAFECHER2, @MAMARESHER2,\r\n    @COLESTADDUKES, @FECESTADIFICACIONDUKES, @LINFESTADIFICACION, @PROSTESCALAGLEASON,\r\n    @PEDCLASIFRIESGO, @PEDFECCLASIFRIESGO, @OBJTRATINICIAL, @OBJINTERVPERIODO\r\n)',
    update:
      'UPDATE CACDiagnosticoEstadificacion\r\nSET NOMNEOPLASIA           = @NOMNEOPLASIA,\r\n    CANPRIORIZADO          = @CANPRIORIZADO,\r\n    INDINCIDENCIA          = @INDINCIDENCIA,\r\n    EDADDX                 = @EDADDX,\r\n    FECREMMEDICO           = @FECREMMEDICO,\r\n    FECINGINST             = @FECINGINST,\r\n    TIPESTUDIODX           = @TIPESTUDIODX,\r\n    MOTSINHISTOPAT         = @MOTSINHISTOPAT,\r\n    FECMUESTRAHISTO        = @FECMUESTRAHISTO,\r\n    FECINFORMEHISTO        = @FECINFORMEHISTO,\r\n    CODIPSCONFIRM          = @CODIPSCONFIRM,\r\n    FEC1RACONSULTA         = @FEC1RACONSULTA,\r\n    HISTOTUMORMUESTRA      = @HISTOTUMORMUESTRA,\r\n    GRADIFTUMOR            = @GRADIFTUMOR,\r\n    ESTADTUMORSOLIDO       = @ESTADTUMORSOLIDO,\r\n    FECESTADIFICACION      = @FECESTADIFICACION,\r\n    MAMAHER2PRETRAT        = @MAMAHER2PRETRAT,\r\n    MAMAFECHER2            = @MAMAFECHER2,\r\n    MAMARESHER2            = @MAMARESHER2,\r\n    COLESTADDUKES          = @COLESTADDUKES,\r\n    FECESTADIFICACIONDUKES = @FECESTADIFICACIONDUKES,\r\n    LINFESTADIFICACION     = @LINFESTADIFICACION,\r\n    PROSTESCALAGLEASON     = @PROSTESCALAGLEASON,\r\n    PEDCLASIFRIESGO        = @PEDCLASIFRIESGO,\r\n    PEDFECCLASIFRIESGO     = @PEDFECCLASIFRIESGO,\r\n    OBJTRATINICIAL         = @OBJTRATINICIAL,\r\n    OBJINTERVPERIODO       = @OBJINTERVPERIODO\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACAntecedentes',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'ANTOTROCANCER',
      'ANTFECDXOTRO',
      'ANTNOMCANCER',
      'ANTCODCIE10',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10,\r\n    ANTOTROCANCER, ANTFECDXOTRO, ANTNOMCANCER, ANTCODCIE10\r\nFROM CACAntecedentes\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACAntecedentes (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10,\r\n    ANTOTROCANCER, ANTFECDXOTRO, ANTNOMCANCER, ANTCODCIE10\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10,\r\n    @ANTOTROCANCER, @ANTFECDXOTRO, @ANTNOMCANCER, @ANTCODCIE10\r\n)',
    update:
      'UPDATE CACAntecedentes\r\nSET ANTOTROCANCER = @ANTOTROCANCER,\r\n    ANTFECDXOTRO  = @ANTFECDXOTRO,\r\n    ANTNOMCANCER  = @ANTNOMCANCER,\r\n    ANTCODCIE10   = @ANTCODCIE10\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACTerapiaSistemicaIntratecal',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'QUIRECIBIOCORTE',
      'QUICANFASES',
      'QUIFASPREFASE',
      'QUIFASINDUCCION',
      'QUIFASINTENSIF',
      'QUIFASCONSOLID',
      'QUIFASREINDUCC',
      'QUIFASMANTENIM',
      'QUIFASMANTLARGO',
      'QUIFASOTRA',
      'QUINUMCICLOSREP',
      'QUIUBITEMP1CICLO',
      'QUIFECINICIO1CICLO',
      'QUINUMIPS1CICLO',
      'QUICODIPS11CICLO',
      'QUICODIPS21CICLO',
      'QUIMEDANTINEOP1CICLO',
      'QUIMEDESPECIF1CICLO',
      'QUIMEDNOPOS1A1CICLO',
      'QUIMEDNOPOS21CICLO',
      'QUIMEDNOPOS31CICLO',
      'QUIRECIBIOINTRATECAL',
      'QUIFECFIN1CICLO',
      'QUICARACACTUAL1CICLO',
      'QUIMOTFINPREM1CICLO',
      'QUIUBITEMPULTCICLO',
      'QUIFECINICIOULTCICLO',
      'QUINUMIPSULTCICLO',
      'QUICODIPS1ULTCICLO',
      'QUICODIPS2ULTCICLO',
      'QUIMEDANTINEOPULTCICLO',
      'QUIMEDESPECIFULTCICLO',
      'QUIMEDNOPOS1AULTCICLO',
      'QUIMEDNOPOS2ULTCICLO',
      'QUIMEDNOPOS3ULTCICLO',
      'QUIRECIBIOINTRATECALULT',
      'QUIFECFINULTCICLO',
      'QUICARACACTUALULTCICLO',
      'QUIMOTFINPREMULTCICLO',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, QUIRECIBIOCORTE, QUICANFASES,\r\n    QUIFASPREFASE, QUIFASINDUCCION, QUIFASINTENSIF, QUIFASCONSOLID, QUIFASREINDUCC,\r\n    QUIFASMANTENIM, QUIFASMANTLARGO, QUIFASOTRA, QUINUMCICLOSREP, QUIUBITEMP1CICLO,\r\n    QUIFECINICIO1CICLO, QUINUMIPS1CICLO, QUICODIPS11CICLO, QUICODIPS21CICLO,\r\n    QUIMEDANTINEOP1CICLO, QUIMEDESPECIF1CICLO, QUIMEDNOPOS1A1CICLO, QUIMEDNOPOS21CICLO,\r\n    QUIMEDNOPOS31CICLO, QUIRECIBIOINTRATECAL, QUIFECFIN1CICLO, QUICARACACTUAL1CICLO,\r\n    QUIMOTFINPREM1CICLO, QUIUBITEMPULTCICLO, QUIFECINICIOULTCICLO, QUINUMIPSULTCICLO,\r\n    QUICODIPS1ULTCICLO, QUICODIPS2ULTCICLO, QUIMEDANTINEOPULTCICLO, QUIMEDESPECIFULTCICLO,\r\n    QUIMEDNOPOS1AULTCICLO, QUIMEDNOPOS2ULTCICLO, QUIMEDNOPOS3ULTCICLO,\r\n    QUIRECIBIOINTRATECALULT, QUIFECFINULTCICLO, QUICARACACTUALULTCICLO, QUIMOTFINPREMULTCICLO\r\nFROM CACTerapiaSistemicaIntratecal\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACTerapiaSistemicaIntratecal (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, QUIRECIBIOCORTE, QUICANFASES,\r\n    QUIFASPREFASE, QUIFASINDUCCION, QUIFASINTENSIF, QUIFASCONSOLID, QUIFASREINDUCC,\r\n    QUIFASMANTENIM, QUIFASMANTLARGO, QUIFASOTRA, QUINUMCICLOSREP, QUIUBITEMP1CICLO,\r\n    QUIFECINICIO1CICLO, QUINUMIPS1CICLO, QUICODIPS11CICLO, QUICODIPS21CICLO,\r\n    QUIMEDANTINEOP1CICLO, QUIMEDESPECIF1CICLO, QUIMEDNOPOS1A1CICLO, QUIMEDNOPOS21CICLO,\r\n    QUIMEDNOPOS31CICLO, QUIRECIBIOINTRATECAL, QUIFECFIN1CICLO, QUICARACACTUAL1CICLO,\r\n    QUIMOTFINPREM1CICLO, QUIUBITEMPULTCICLO, QUIFECINICIOULTCICLO, QUINUMIPSULTCICLO,\r\n    QUICODIPS1ULTCICLO, QUICODIPS2ULTCICLO, QUIMEDANTINEOPULTCICLO, QUIMEDESPECIFULTCICLO,\r\n    QUIMEDNOPOS1AULTCICLO, QUIMEDNOPOS2ULTCICLO, QUIMEDNOPOS3ULTCICLO,\r\n    QUIRECIBIOINTRATECALULT, QUIFECFINULTCICLO, QUICARACACTUALULTCICLO, QUIMOTFINPREMULTCICLO\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10, @QUIRECIBIOCORTE, @QUICANFASES,\r\n    @QUIFASPREFASE, @QUIFASINDUCCION, @QUIFASINTENSIF, @QUIFASCONSOLID, @QUIFASREINDUCC,\r\n    @QUIFASMANTENIM, @QUIFASMANTLARGO, @QUIFASOTRA, @QUINUMCICLOSREP, @QUIUBITEMP1CICLO,\r\n    @QUIFECINICIO1CICLO, @QUINUMIPS1CICLO, @QUICODIPS11CICLO, @QUICODIPS21CICLO,\r\n    @QUIMEDANTINEOP1CICLO, @QUIMEDESPECIF1CICLO, @QUIMEDNOPOS1A1CICLO, @QUIMEDNOPOS21CICLO,\r\n    @QUIMEDNOPOS31CICLO, @QUIRECIBIOINTRATECAL, @QUIFECFIN1CICLO, @QUICARACACTUAL1CICLO,\r\n    @QUIMOTFINPREM1CICLO, @QUIUBITEMPULTCICLO, @QUIFECINICIOULTCICLO, @QUINUMIPSULTCICLO,\r\n    @QUICODIPS1ULTCICLO, @QUICODIPS2ULTCICLO, @QUIMEDANTINEOPULTCICLO, @QUIMEDESPECIFULTCICLO,\r\n    @QUIMEDNOPOS1AULTCICLO, @QUIMEDNOPOS2ULTCICLO, @QUIMEDNOPOS3ULTCICLO,\r\n    @QUIRECIBIOINTRATECALULT, @QUIFECFINULTCICLO, @QUICARACACTUALULTCICLO, @QUIMOTFINPREMULTCICLO\r\n)',
    update:
      'UPDATE CACTerapiaSistemicaIntratecal\r\nSET QUIRECIBIOCORTE         = @QUIRECIBIOCORTE,\r\n    QUICANFASES             = @QUICANFASES,\r\n    QUIFASPREFASE           = @QUIFASPREFASE,\r\n    QUIFASINDUCCION         = @QUIFASINDUCCION,\r\n    QUIFASINTENSIF          = @QUIFASINTENSIF,\r\n    QUIFASCONSOLID          = @QUIFASCONSOLID,\r\n    QUIFASREINDUCC          = @QUIFASREINDUCC,\r\n    QUIFASMANTENIM          = @QUIFASMANTENIM,\r\n    QUIFASMANTLARGO         = @QUIFASMANTLARGO,\r\n    QUIFASOTRA              = @QUIFASOTRA,\r\n    QUINUMCICLOSREP         = @QUINUMCICLOSREP,\r\n    QUIUBITEMP1CICLO        = @QUIUBITEMP1CICLO,\r\n    QUIFECINICIO1CICLO      = @QUIFECINICIO1CICLO,\r\n    QUINUMIPS1CICLO         = @QUINUMIPS1CICLO,\r\n    QUICODIPS11CICLO        = @QUICODIPS11CICLO,\r\n    QUICODIPS21CICLO        = @QUICODIPS21CICLO,\r\n    QUIMEDANTINEOP1CICLO    = @QUIMEDANTINEOP1CICLO,\r\n    QUIMEDESPECIF1CICLO     = @QUIMEDESPECIF1CICLO,\r\n    QUIMEDNOPOS1A1CICLO     = @QUIMEDNOPOS1A1CICLO,\r\n    QUIMEDNOPOS21CICLO      = @QUIMEDNOPOS21CICLO,\r\n    QUIMEDNOPOS31CICLO      = @QUIMEDNOPOS31CICLO,\r\n    QUIRECIBIOINTRATECAL    = @QUIRECIBIOINTRATECAL,\r\n    QUIFECFIN1CICLO         = @QUIFECFIN1CICLO,\r\n    QUICARACACTUAL1CICLO    = @QUICARACACTUAL1CICLO,\r\n    QUIMOTFINPREM1CICLO     = @QUIMOTFINPREM1CICLO,\r\n    QUIUBITEMPULTCICLO      = @QUIUBITEMPULTCICLO,\r\n    QUIFECINICIOULTCICLO    = @QUIFECINICIOULTCICLO,\r\n    QUINUMIPSULTCICLO       = @QUINUMIPSULTCICLO,\r\n    QUICODIPS1ULTCICLO      = @QUICODIPS1ULTCICLO,\r\n    QUICODIPS2ULTCICLO      = @QUICODIPS2ULTCICLO,\r\n    QUIMEDANTINEOPULTCICLO  = @QUIMEDANTINEOPULTCICLO,\r\n    QUIMEDESPECIFULTCICLO   = @QUIMEDESPECIFULTCICLO,\r\n    QUIMEDNOPOS1AULTCICLO   = @QUIMEDNOPOS1AULTCICLO,\r\n    QUIMEDNOPOS2ULTCICLO    = @QUIMEDNOPOS2ULTCICLO,\r\n    QUIMEDNOPOS3ULTCICLO    = @QUIMEDNOPOS3ULTCICLO,\r\n    QUIRECIBIOINTRATECALULT = @QUIRECIBIOINTRATECALULT,\r\n    QUIFECFINULTCICLO       = @QUIFECFINULTCICLO,\r\n    QUICARACACTUALULTCICLO  = @QUICARACACTUALULTCICLO,\r\n    QUIMOTFINPREMULTCICLO   = @QUIMOTFINPREMULTCICLO\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACCirugiaRadioterapia',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'CIRSOMETIDOCORTE',
      'CIRNUMCIRUGIAS',
      'CIRFEC1RACIRUGIA',
      'CIRCODIPS11RA',
      'CIRCODIPS21RA',
      'CIRUBITEMP1RA',
      'CIRFECULTCIRUGIA',
      'CIRMOTULTCIRUGIA',
      'CIRCODIPSULT',
      'CIRCODULTCIRUGIA',
      'CIRUBITEMPULT',
      'CIRESTADOVITALULT',
      'RADRECIBIOCORTE',
      'RADNUMESQUEMAS',
      'RADFECINI1ESQ',
      'RADUBITEMP1ESQ',
      'RADTIPRADIO1ESQ',
      'RADNUMIPS1ESQ',
      'RADCODIPS11ESQ',
      'RADCODIPS21ESQ',
      'RADFECFIN1ESQ',
      'RADCARACACTUAL1ESQ',
      'RADMOTFIN1ESQ',
      'RADFECINIULTESQ',
      'RADUBITEMPULTESQ',
      'RADTIPRADIOULTESQ',
      'RADNUMIPSULTESQ',
      'RADCODIPS1ULTESQ',
      'RADCODIPS2ULTESQ',
      'RADFECFINULTESQ',
      'RADCARACACTUALULTESQ',
      'RADMOTFINULTESQ',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, CIRSOMETIDOCORTE, CIRNUMCIRUGIAS,\r\n    CIRFEC1RACIRUGIA, CIRCODIPS11RA, CIRCODIPS21RA, CIRUBITEMP1RA, CIRFECULTCIRUGIA,\r\n    CIRMOTULTCIRUGIA, CIRCODIPSULT, CIRCODULTCIRUGIA, CIRUBITEMPULT, CIRESTADOVITALULT,\r\n    RADRECIBIOCORTE, RADNUMESQUEMAS, RADFECINI1ESQ, RADUBITEMP1ESQ, RADTIPRADIO1ESQ,\r\n    RADNUMIPS1ESQ, RADCODIPS11ESQ, RADCODIPS21ESQ, RADFECFIN1ESQ, RADCARACACTUAL1ESQ,\r\n    RADMOTFIN1ESQ, RADFECINIULTESQ, RADUBITEMPULTESQ, RADTIPRADIOULTESQ, RADNUMIPSULTESQ,\r\n    RADCODIPS1ULTESQ, RADCODIPS2ULTESQ, RADFECFINULTESQ, RADCARACACTUALULTESQ, RADMOTFINULTESQ\r\nFROM CACCirugiaRadioterapia\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACCirugiaRadioterapia (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, CIRSOMETIDOCORTE, CIRNUMCIRUGIAS,\r\n    CIRFEC1RACIRUGIA, CIRCODIPS11RA, CIRCODIPS21RA, CIRUBITEMP1RA, CIRFECULTCIRUGIA,\r\n    CIRMOTULTCIRUGIA, CIRCODIPSULT, CIRCODULTCIRUGIA, CIRUBITEMPULT, CIRESTADOVITALULT,\r\n    RADRECIBIOCORTE, RADNUMESQUEMAS, RADFECINI1ESQ, RADUBITEMP1ESQ, RADTIPRADIO1ESQ,\r\n    RADNUMIPS1ESQ, RADCODIPS11ESQ, RADCODIPS21ESQ, RADFECFIN1ESQ, RADCARACACTUAL1ESQ,\r\n    RADMOTFIN1ESQ, RADFECINIULTESQ, RADUBITEMPULTESQ, RADTIPRADIOULTESQ, RADNUMIPSULTESQ,\r\n    RADCODIPS1ULTESQ, RADCODIPS2ULTESQ, RADFECFINULTESQ, RADCARACACTUALULTESQ, RADMOTFINULTESQ\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10, @CIRSOMETIDOCORTE, @CIRNUMCIRUGIAS,\r\n    @CIRFEC1RACIRUGIA, @CIRCODIPS11RA, @CIRCODIPS21RA, @CIRUBITEMP1RA, @CIRFECULTCIRUGIA,\r\n    @CIRMOTULTCIRUGIA, @CIRCODIPSULT, @CIRCODULTCIRUGIA, @CIRUBITEMPULT, @CIRESTADOVITALULT,\r\n    @RADRECIBIOCORTE, @RADNUMESQUEMAS, @RADFECINI1ESQ, @RADUBITEMP1ESQ, @RADTIPRADIO1ESQ,\r\n    @RADNUMIPS1ESQ, @RADCODIPS11ESQ, @RADCODIPS21ESQ, @RADFECFIN1ESQ, @RADCARACACTUAL1ESQ,\r\n    @RADMOTFIN1ESQ, @RADFECINIULTESQ, @RADUBITEMPULTESQ, @RADTIPRADIOULTESQ, @RADNUMIPSULTESQ,\r\n    @RADCODIPS1ULTESQ, @RADCODIPS2ULTESQ, @RADFECFINULTESQ, @RADCARACACTUALULTESQ, @RADMOTFINULTESQ\r\n)',
    update:
      'UPDATE CACCirugiaRadioterapia\r\nSET CIRSOMETIDOCORTE      = @CIRSOMETIDOCORTE,\r\n    CIRNUMCIRUGIAS        = @CIRNUMCIRUGIAS,\r\n    CIRFEC1RACIRUGIA      = @CIRFEC1RACIRUGIA,\r\n    CIRCODIPS11RA         = @CIRCODIPS11RA,\r\n    CIRCODIPS21RA         = @CIRCODIPS21RA,\r\n    CIRUBITEMP1RA         = @CIRUBITEMP1RA,\r\n    CIRFECULTCIRUGIA      = @CIRFECULTCIRUGIA,\r\n    CIRMOTULTCIRUGIA      = @CIRMOTULTCIRUGIA,\r\n    CIRCODIPSULT          = @CIRCODIPSULT,\r\n    CIRCODULTCIRUGIA      = @CIRCODULTCIRUGIA,\r\n    CIRUBITEMPULT         = @CIRUBITEMPULT,\r\n    CIRESTADOVITALULT     = @CIRESTADOVITALULT,\r\n    RADRECIBIOCORTE       = @RADRECIBIOCORTE,\r\n    RADNUMESQUEMAS        = @RADNUMESQUEMAS,\r\n    RADFECINI1ESQ         = @RADFECINI1ESQ,\r\n    RADUBITEMP1ESQ        = @RADUBITEMP1ESQ,\r\n    RADTIPRADIO1ESQ       = @RADTIPRADIO1ESQ,\r\n    RADNUMIPS1ESQ         = @RADNUMIPS1ESQ,\r\n    RADCODIPS11ESQ        = @RADCODIPS11ESQ,\r\n    RADCODIPS21ESQ        = @RADCODIPS21ESQ,\r\n    RADFECFIN1ESQ         = @RADFECFIN1ESQ,\r\n    RADCARACACTUAL1ESQ    = @RADCARACACTUAL1ESQ,\r\n    RADMOTFIN1ESQ         = @RADMOTFIN1ESQ,\r\n    RADFECINIULTESQ       = @RADFECINIULTESQ,\r\n    RADUBITEMPULTESQ      = @RADUBITEMPULTESQ,\r\n    RADTIPRADIOULTESQ     = @RADTIPRADIOULTESQ,\r\n    RADNUMIPSULTESQ       = @RADNUMIPSULTESQ,\r\n    RADCODIPS1ULTESQ      = @RADCODIPS1ULTESQ,\r\n    RADCODIPS2ULTESQ      = @RADCODIPS2ULTESQ,\r\n    RADFECFINULTESQ       = @RADFECFINULTESQ,\r\n    RADCARACACTUALULTESQ  = @RADCARACACTUALULTESQ,\r\n    RADMOTFINULTESQ       = @RADMOTFINULTESQ\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACTrasplanteCelulasMadre',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'TRARECIBIOCORTE',
      'TRATIPO',
      'TRAUBITEMPORAL',
      'TRAFECTRASPLANTE',
      'TRACODIPS',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10,\r\n    TRARECIBIOCORTE, TRATIPO, TRAUBITEMPORAL, TRAFECTRASPLANTE, TRACODIPS\r\nFROM CACTrasplanteCelulasMadre\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACTrasplanteCelulasMadre (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10,\r\n    TRARECIBIOCORTE, TRATIPO, TRAUBITEMPORAL, TRAFECTRASPLANTE, TRACODIPS\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10,\r\n    @TRARECIBIOCORTE, @TRATIPO, @TRAUBITEMPORAL, @TRAFECTRASPLANTE, @TRACODIPS\r\n)',
    update:
      'UPDATE CACTrasplanteCelulasMadre\r\nSET TRARECIBIOCORTE  = @TRARECIBIOCORTE,\r\n    TRATIPO          = @TRATIPO,\r\n    TRAUBITEMPORAL   = @TRAUBITEMPORAL,\r\n    TRAFECTRASPLANTE = @TRAFECTRASPLANTE,\r\n    TRACODIPS        = @TRACODIPS\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACTratamientoComplementario',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'TRCRECIBIOCIRRECONS',
      'TRCFECCIRRECONS',
      'TRCCODIPSCIRRECONS',
      'TRCVALCUIDADOPALIATIVO',
      'TRCATENCIONESCUIDADOPAL',
      'TRCFEC1RACONSULTAPAL',
      'TRCCODIPSCUIDADOPAL',
      'TRCVALPSIQUIATRIA',
      'TRCFEC1RACONSULTAPSIQ',
      'TRCCODIPSPSIQUIATRIA',
      'TRCVALNUTRICION',
      'TRCFECCONSULTANUTRICION',
      'TRCCODIPSNUTRICION',
      'TRCRECIBIOSOPORTENUTRI',
      'TRCRECIBIOTERAPIASREHAB',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, TRCRECIBIOCIRRECONS, TRCFECCIRRECONS,\r\n    TRCCODIPSCIRRECONS, TRCVALCUIDADOPALIATIVO, TRCATENCIONESCUIDADOPAL,\r\n    TRCFEC1RACONSULTAPAL, TRCCODIPSCUIDADOPAL, TRCVALPSIQUIATRIA, TRCFEC1RACONSULTAPSIQ,\r\n    TRCCODIPSPSIQUIATRIA, TRCVALNUTRICION, TRCFECCONSULTANUTRICION, TRCCODIPSNUTRICION,\r\n    TRCRECIBIOSOPORTENUTRI, TRCRECIBIOTERAPIASREHAB\r\nFROM CACTratamientoComplementario\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACTratamientoComplementario (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, TRCRECIBIOCIRRECONS, TRCFECCIRRECONS,\r\n    TRCCODIPSCIRRECONS, TRCVALCUIDADOPALIATIVO, TRCATENCIONESCUIDADOPAL,\r\n    TRCFEC1RACONSULTAPAL, TRCCODIPSCUIDADOPAL, TRCVALPSIQUIATRIA, TRCFEC1RACONSULTAPSIQ,\r\n    TRCCODIPSPSIQUIATRIA, TRCVALNUTRICION, TRCFECCONSULTANUTRICION, TRCCODIPSNUTRICION,\r\n    TRCRECIBIOSOPORTENUTRI, TRCRECIBIOTERAPIASREHAB\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10, @TRCRECIBIOCIRRECONS, @TRCFECCIRRECONS,\r\n    @TRCCODIPSCIRRECONS, @TRCVALCUIDADOPALIATIVO, @TRCATENCIONESCUIDADOPAL,\r\n    @TRCFEC1RACONSULTAPAL, @TRCCODIPSCUIDADOPAL, @TRCVALPSIQUIATRIA, @TRCFEC1RACONSULTAPSIQ,\r\n    @TRCCODIPSPSIQUIATRIA, @TRCVALNUTRICION, @TRCFECCONSULTANUTRICION, @TRCCODIPSNUTRICION,\r\n    @TRCRECIBIOSOPORTENUTRI, @TRCRECIBIOTERAPIASREHAB\r\n)',
    update:
      'UPDATE CACTratamientoComplementario\r\nSET TRCRECIBIOCIRRECONS     = @TRCRECIBIOCIRRECONS,\r\n    TRCFECCIRRECONS         = @TRCFECCIRRECONS,\r\n    TRCCODIPSCIRRECONS     = @TRCCODIPSCIRRECONS,\r\n    TRCVALCUIDADOPALIATIVO  = @TRCVALCUIDADOPALIATIVO,\r\n    TRCATENCIONESCUIDADOPAL = @TRCATENCIONESCUIDADOPAL,\r\n    TRCFEC1RACONSULTAPAL    = @TRCFEC1RACONSULTAPAL,\r\n    TRCCODIPSCUIDADOPAL     = @TRCCODIPSCUIDADOPAL,\r\n    TRCVALPSIQUIATRIA       = @TRCVALPSIQUIATRIA,\r\n    TRCFEC1RACONSULTAPSIQ   = @TRCFEC1RACONSULTAPSIQ,\r\n    TRCCODIPSPSIQUIATRIA    = @TRCCODIPSPSIQUIATRIA,\r\n    TRCVALNUTRICION         = @TRCVALNUTRICION,\r\n    TRCFECCONSULTANUTRICION = @TRCFECCONSULTANUTRICION,\r\n    TRCCODIPSNUTRICION      = @TRCCODIPSNUTRICION,\r\n    TRCRECIBIOSOPORTENUTRI  = @TRCRECIBIOSOPORTENUTRI,\r\n    TRCRECIBIOTERAPIASREHAB = @TRCRECIBIOTERAPIASREHAB\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
  {
    tabla: 'CACResultadoManejoOncologico',
    campos: [
      'TIPDOCUSUARIO',
      'NUMDOCUSUARIO',
      'CODCIE10',
      'RMORESMANEJOONCO',
      'RMOESTADOVITAL',
      'RMONOVADMINISTRATIVA',
      'RMONOVCLINICA',
      'RMOFECDESAFILIACION',
      'RMOFECMUERTE',
      'RMOCAUSAMUERTE',
    ],
    select:
      'SELECT \r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, RMORESMANEJOONCO, RMOESTADOVITAL,\r\n    RMONOVADMINISTRATIVA, RMONOVCLINICA, RMOFECDESAFILIACION, RMOFECMUERTE, RMOCAUSAMUERTE\r\nFROM CACResultadoManejoOncologico\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
    insert:
      'INSERT INTO CACResultadoManejoOncologico (\r\n    TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, RMORESMANEJOONCO, RMOESTADOVITAL,\r\n    RMONOVADMINISTRATIVA, RMONOVCLINICA, RMOFECDESAFILIACION, RMOFECMUERTE, RMOCAUSAMUERTE\r\n) VALUES (\r\n    @TIPDOCUSUARIO, @NUMDOCUSUARIO, @CODCIE10, @RMORESMANEJOONCO, @RMOESTADOVITAL,\r\n    @RMONOVADMINISTRATIVA, @RMONOVCLINICA, @RMOFECDESAFILIACION, @RMOFECMUERTE, @RMOCAUSAMUERTE\r\n)',
    update:
      'UPDATE CACResultadoManejoOncologico\r\nSET RMORESMANEJOONCO     = @RMORESMANEJOONCO,\r\n    RMOESTADOVITAL       = @RMOESTADOVITAL,\r\n    RMONOVADMINISTRATIVA = @RMONOVADMINISTRATIVA,\r\n    RMONOVCLINICA        = @RMONOVCLINICA,\r\n    RMOFECDESAFILIACION  = @RMOFECDESAFILIACION,\r\n    RMOFECMUERTE         = @RMOFECMUERTE,\r\n    RMOCAUSAMUERTE       = @RMOCAUSAMUERTE\r\nWHERE TIPDOCUSUARIO = @TIPDOCUSUARIO \r\n  AND NUMDOCUSUARIO = @NUMDOCUSUARIO \r\n  AND CODCIE10 = @CODCIE10;',
  },
];
export const REGISTRO_PACIENTE_SQL =
  'SELECT TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, IDETIPOTRATAMIENTO FROM CACIdentificacionGeneral WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO AND NUMDOCUSUARIO = @NUMDOCUSUARIO';
export const BLOQUEAR_PACIENTE_SQL =
  'SELECT TIPDOCUSUARIO, NUMDOCUSUARIO, CODCIE10, IDETIPOTRATAMIENTO FROM CACIdentificacionGeneral WITH (UPDLOCK, HOLDLOCK) WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO AND NUMDOCUSUARIO = @NUMDOCUSUARIO';
