export const DEFINICION_CAMPOS = [
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'IDETIPOTRATAMIENTO',
    etiqueta: 'Tipo Tratamiento (Corte)',
    tipo: 'number',
    obligatorio: true,
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'NOMNEOPLASIA',
    etiqueta: 'Nombre Neoplasia',
    tipo: 'text',
    longitudMaxima: 4,
  },
  {
    nombre: 'CANPRIORIZADO',
    etiqueta: 'Cáncer Priorizado',
    tipo: 'text',
    longitudMaxima: 1,
  },
  {
    nombre: 'INDINCIDENCIA',
    etiqueta: 'Incidencia',
    tipo: 'text',
    longitudMaxima: 1,
  },
  {
    nombre: 'EDADDX',
    etiqueta: 'Edad al Diagnóstico',
    tipo: 'number',
  },
  {
    nombre: 'FECREMMEDICO',
    etiqueta: 'Fecha Remisión Médico',
    tipo: 'date',
  },
  {
    nombre: 'FECINGINST',
    etiqueta: 'Fecha Ingreso Institución',
    tipo: 'date',
  },
  {
    nombre: 'TIPESTUDIODX',
    etiqueta: 'Tipo Estudio Diagnóstico',
    tipo: 'number',
  },
  {
    nombre: 'MOTSINHISTOPAT',
    etiqueta: 'Motivo sin Histopatología',
    tipo: 'number',
  },
  {
    nombre: 'FECMUESTRAHISTO',
    etiqueta: 'Fecha Muestra Histopatología',
    tipo: 'date',
  },
  {
    nombre: 'FECINFORMEHISTO',
    etiqueta: 'Fecha Informe Histopatología',
    tipo: 'date',
  },
  {
    nombre: 'CODIPSCONFIRM',
    etiqueta: 'Código IPS Confirmación',
    tipo: 'text',
    longitudMaxima: 12,
  },
  {
    nombre: 'FEC1RACONSULTA',
    etiqueta: 'Fecha 1ra Consulta Tratante',
    tipo: 'date',
  },
  {
    nombre: 'HISTOTUMORMUESTRA',
    etiqueta: 'Histología del Tumor',
    tipo: 'number',
  },
  {
    nombre: 'GRADIFTUMOR',
    etiqueta: 'Grado Diferenciación Tumor',
    tipo: 'number',
  },
  {
    nombre: 'ESTADTUMORSOLIDO',
    etiqueta: 'Estadificación Tumor Sólido',
    tipo: 'text',
    longitudMaxima: 255,
  },
  {
    nombre: 'FECESTADIFICACION',
    etiqueta: 'Fecha Estadificación',
    tipo: 'date',
  },
  {
    nombre: 'MAMAHER2PRETRAT',
    etiqueta: 'Mama: Prueba HER2 Pre-trat.',
    tipo: 'number',
  },
  {
    nombre: 'MAMAFECHER2',
    etiqueta: 'Mama: Fecha Prueba HER2',
    tipo: 'date',
  },
  {
    nombre: 'MAMARESHER2',
    etiqueta: 'Mama: Resultado HER2',
    tipo: 'number',
  },
  {
    nombre: 'COLESTADDUKES',
    etiqueta: 'Colorrectal: Estadificación Dukes',
    tipo: 'number',
  },
  {
    nombre: 'FECESTADIFICACIONDUKES',
    etiqueta: 'Colorrectal: Fecha Dukes',
    tipo: 'date',
  },
  {
    nombre: 'LINFESTADIFICACION',
    etiqueta: 'Linfomas: Estadificación',
    tipo: 'number',
  },
  {
    nombre: 'PROSTESCALAGLEASON',
    etiqueta: 'Próstata: Escala Gleason',
    tipo: 'number',
  },
  {
    nombre: 'PEDCLASIFRIESGO',
    etiqueta: 'Pediatría: Clasif. Riesgo',
    tipo: 'number',
  },
  {
    nombre: 'PEDFECCLASIFRIESGO',
    etiqueta: 'Pediatría: Fecha Clasif. Riesgo',
    tipo: 'date',
  },
  {
    nombre: 'OBJTRATINICIAL',
    etiqueta: 'Objetivo Tratamiento Inicial',
    tipo: 'number',
  },
  {
    nombre: 'OBJINTERVPERIODO',
    etiqueta: 'Objetivo Intervención en Periodo',
    tipo: 'number',
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'ANTOTROCANCER',
    etiqueta: 'Antecedente de Otro Cáncer Primario',
    tipo: 'number',
  },
  {
    nombre: 'ANTFECDXOTRO',
    etiqueta: 'Fecha Diagnóstico de Otro Cáncer',
    tipo: 'date',
  },
  {
    nombre: 'ANTNOMCANCER',
    etiqueta: 'Nombre Tipo Cáncer Antecedente',
    tipo: 'text',
    longitudMaxima: 4,
  },
  {
    nombre: 'ANTCODCIE10',
    etiqueta: 'Código CIE-10 Antecedente',
    tipo: 'text',
    longitudMaxima: 5,
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'QUIRECIBIOCORTE',
    etiqueta: '¿Recibió Quimioterapia en el Corte?',
    tipo: 'number',
  },
  {
    nombre: 'QUICANFASES',
    etiqueta: 'Número de Fases en este Corte',
    tipo: 'number',
  },
  {
    nombre: 'QUIFASPREFASE',
    etiqueta: 'Fase: prefase',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASINDUCCION',
    etiqueta: 'Fase: inducción',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASINTENSIF',
    etiqueta: 'Fase: intensificación',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASCONSOLID',
    etiqueta: 'Fase: consolidación',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASREINDUCC',
    etiqueta: 'Fase: reinducción',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASMANTENIM',
    etiqueta: 'Fase: mantenimiento',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASMANTLARGO',
    etiqueta: 'Fase: mantenimiento a largo plazo',
    tipo: 'text',
  },
  {
    nombre: 'QUIFASOTRA',
    etiqueta: 'Otra fase',
    tipo: 'text',
  },
  {
    nombre: 'QUINUMCICLOSREP',
    etiqueta: 'Número Ciclos Administrados',
    tipo: 'number',
  },
  {
    nombre: 'QUIUBITEMP1CICLO',
    etiqueta: 'Ubicación Temporal 1er Ciclo',
    tipo: 'number',
  },
  {
    nombre: 'QUIFECINICIO1CICLO',
    etiqueta: 'Fecha Inicio 1er Ciclo',
    tipo: 'date',
  },
  {
    nombre: 'QUINUMIPS1CICLO',
    etiqueta: 'Número de IPS del primer ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUICODIPS11CICLO',
    etiqueta: 'Código IPS1 1er Ciclo',
    tipo: 'text',
    longitudMaxima: 12,
  },
  {
    nombre: 'QUICODIPS21CICLO',
    etiqueta: 'Código de segunda IPS del primer ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIMEDANTINEOP1CICLO',
    etiqueta: 'Antineoplásicos Propuestos 1er Ciclo',
    tipo: 'number',
  },
  {
    nombre: 'QUIMEDESPECIF1CICLO',
    etiqueta: 'Medicamentos específicos del primer ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIMEDNOPOS1A1CICLO',
    etiqueta: 'Medicamento no POS 1 del primer ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIMEDNOPOS21CICLO',
    etiqueta: 'Medicamento no POS 2 del primer ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIMEDNOPOS31CICLO',
    etiqueta: 'Medicamento no POS 3 del primer ciclo',
    tipo: 'number',
  },
  {
    nombre: 'QUIRECIBIOINTRATECAL',
    etiqueta: '¿Recibió Intratecal en 1er Ciclo?',
    tipo: 'number',
  },
  {
    nombre: 'QUIFECFIN1CICLO',
    etiqueta: 'Fecha Fin 1er Ciclo',
    tipo: 'date',
  },
  {
    nombre: 'QUICARACACTUAL1CICLO',
    etiqueta: 'Característica actual del primer ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIMOTFINPREM1CICLO',
    etiqueta: 'Motivo de finalización prematura del primer ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIUBITEMPULTCICLO',
    etiqueta: 'Ubicación temporal del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIFECINICIOULTCICLO',
    etiqueta: 'Fecha Inicio Último Ciclo',
    tipo: 'date',
  },
  {
    nombre: 'QUINUMIPSULTCICLO',
    etiqueta: 'Número de IPS del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUICODIPS1ULTCICLO',
    etiqueta: 'Código IPS1 Último Ciclo',
    tipo: 'text',
    longitudMaxima: 12,
  },
  {
    nombre: 'QUICODIPS2ULTCICLO',
    etiqueta: 'Código de segunda IPS del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIMEDANTINEOPULTCICLO',
    etiqueta: 'Antineoplásicos del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIMEDESPECIFULTCICLO',
    etiqueta: 'Medicamentos específicos del último ciclo',
    tipo: 'number',
  },
  {
    nombre: 'QUIMEDNOPOS1AULTCICLO',
    etiqueta: 'Medicamento no POS 1 del último ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIMEDNOPOS2ULTCICLO',
    etiqueta: 'Medicamento no POS 2 del último ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIMEDNOPOS3ULTCICLO',
    etiqueta: 'Medicamento no POS 3 del último ciclo',
    tipo: 'number',
    longitudMaxima: 2,
  },
  {
    nombre: 'QUIRECIBIOINTRATECALULT',
    etiqueta: 'Intratecal en el último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIFECFINULTCICLO',
    etiqueta: 'Fecha Fin Último Ciclo',
    tipo: 'date',
  },
  {
    nombre: 'QUICARACACTUALULTCICLO',
    etiqueta: 'Característica actual del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'QUIMOTFINPREMULTCICLO',
    etiqueta: 'Motivo de finalización prematura del último ciclo',
    tipo: 'text',
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'CIRSOMETIDOCORTE',
    etiqueta: '¿Sometido a Cirugías en Corte?',
    tipo: 'number',
  },
  {
    nombre: 'CIRNUMCIRUGIAS',
    etiqueta: 'Número de Cirugías en Periodo',
    tipo: 'number',
  },
  {
    nombre: 'CIRFEC1RACIRUGIA',
    etiqueta: 'Fecha 1ra Cirugía',
    tipo: 'date',
  },
  {
    nombre: 'CIRCODIPS11RA',
    etiqueta: 'Código IPS 1ra Cirugía',
    tipo: 'text',
    longitudMaxima: 12,
  },
  {
    nombre: 'CIRCODIPS21RA',
    etiqueta: 'Código de segunda IPS de la primera cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRUBITEMP1RA',
    etiqueta: 'Ubicación temporal de la primera cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRFECULTCIRUGIA',
    etiqueta: 'Fecha Última Cirugía',
    tipo: 'date',
  },
  {
    nombre: 'CIRMOTULTCIRUGIA',
    etiqueta: 'Motivo de la última cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRCODIPSULT',
    etiqueta: 'Código de IPS de la última cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRCODULTCIRUGIA',
    etiqueta: 'Código de la última cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRUBITEMPULT',
    etiqueta: 'Ubicación temporal de la última cirugía',
    tipo: 'text',
  },
  {
    nombre: 'CIRESTADOVITALULT',
    etiqueta: 'Estado Vital al Finalizar Cirugía',
    tipo: 'number',
  },
  {
    nombre: 'RADRECIBIOCORTE',
    etiqueta: '¿Recibió Radioterapia en Corte?',
    tipo: 'number',
  },
  {
    nombre: 'RADNUMESQUEMAS',
    etiqueta: 'Número Esquemas en Corte',
    tipo: 'number',
  },
  {
    nombre: 'RADFECINI1ESQ',
    etiqueta: 'Fecha Inicio 1er Esquema',
    tipo: 'date',
  },
  {
    nombre: 'RADUBITEMP1ESQ',
    etiqueta: 'Ubicación temporal del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADTIPRADIO1ESQ',
    etiqueta: 'Tipo de radioterapia del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADNUMIPS1ESQ',
    etiqueta: 'Número de IPS del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADCODIPS11ESQ',
    etiqueta: 'Código de primera IPS del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADCODIPS21ESQ',
    etiqueta: 'Código de segunda IPS del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADFECFIN1ESQ',
    etiqueta: 'Fecha Fin 1er Esquema',
    tipo: 'date',
  },
  {
    nombre: 'RADCARACACTUAL1ESQ',
    etiqueta: 'Característica actual del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADMOTFIN1ESQ',
    etiqueta: 'Motivo de finalización del primer esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADFECINIULTESQ',
    etiqueta: 'Fecha Inicio Último Esquema',
    tipo: 'date',
  },
  {
    nombre: 'RADUBITEMPULTESQ',
    etiqueta: 'Ubicación temporal del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADTIPRADIOULTESQ',
    etiqueta: 'Tipo de radioterapia del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADNUMIPSULTESQ',
    etiqueta: 'Número de IPS del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADCODIPS1ULTESQ',
    etiqueta: 'Código de primera IPS del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADCODIPS2ULTESQ',
    etiqueta: 'Código de segunda IPS del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADFECFINULTESQ',
    etiqueta: 'Fecha Fin Último Esquema',
    tipo: 'date',
  },
  {
    nombre: 'RADCARACACTUALULTESQ',
    etiqueta: 'Característica actual del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'RADMOTFINULTESQ',
    etiqueta: 'Motivo de finalización del último esquema',
    tipo: 'text',
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'TRARECIBIOCORTE',
    etiqueta: '¿Recibió Trasplante en Corte?',
    tipo: 'number',
  },
  {
    nombre: 'TRATIPO',
    etiqueta: 'Tipo de Trasplante Recibido',
    tipo: 'number',
  },
  {
    nombre: 'TRAUBITEMPORAL',
    etiqueta: 'Ubicación Temporal Trasplante',
    tipo: 'number',
  },
  {
    nombre: 'TRAFECTRASPLANTE',
    etiqueta: 'Fecha de Trasplante',
    tipo: 'date',
  },
  {
    nombre: 'TRACODIPS',
    etiqueta: 'Código IPS Realizó Trasplante',
    tipo: 'text',
    longitudMaxima: 12,
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'TRCRECIBIOCIRRECONS',
    etiqueta: '¿Cirugía Reconstructiva?',
    tipo: 'number',
  },
  {
    nombre: 'TRCFECCIRRECONS',
    etiqueta: 'Fecha Cirugía Reconstructiva',
    tipo: 'date',
  },
  {
    nombre: 'TRCCODIPSCIRRECONS',
    etiqueta: 'Código de IPS de cirugía reconstructiva',
    tipo: 'text',
  },
  {
    nombre: 'TRCVALCUIDADOPALIATIVO',
    etiqueta: '¿Valorado Cuidado Paliativo?',
    tipo: 'number',
  },
  {
    nombre: 'TRCATENCIONESCUIDADOPAL',
    etiqueta: 'Atenciones de cuidado paliativo',
    tipo: 'text',
  },
  {
    nombre: 'TRCFEC1RACONSULTAPAL',
    etiqueta: 'Fecha de primera consulta de cuidado paliativo',
    tipo: 'date',
  },
  {
    nombre: 'TRCCODIPSCUIDADOPAL',
    etiqueta: 'Código de IPS de cuidado paliativo',
    tipo: 'text',
  },
  {
    nombre: 'TRCVALPSIQUIATRIA',
    etiqueta: '¿Valorado por Psiquiatría?',
    tipo: 'number',
  },
  {
    nombre: 'TRCFEC1RACONSULTAPSIQ',
    etiqueta: 'Fecha de primera consulta de psiquiatría',
    tipo: 'date',
  },
  {
    nombre: 'TRCCODIPSPSIQUIATRIA',
    etiqueta: 'Código de IPS de psiquiatría',
    tipo: 'text',
  },
  {
    nombre: 'TRCVALNUTRICION',
    etiqueta: '¿Valorado por Nutrición?',
    tipo: 'number',
  },
  {
    nombre: 'TRCFECCONSULTANUTRICION',
    etiqueta: 'Fecha de consulta de nutrición',
    tipo: 'date',
  },
  {
    nombre: 'TRCCODIPSNUTRICION',
    etiqueta: 'Código de IPS de nutrición',
    tipo: 'text',
  },
  {
    nombre: 'TRCRECIBIOSOPORTENUTRI',
    etiqueta: '¿Recibió Soporte Nutricional?',
    tipo: 'number',
  },
  {
    nombre: 'TRCRECIBIOTERAPIASREHAB',
    etiqueta: '¿Terapias Rehabilitación?',
    tipo: 'number',
  },
  {
    nombre: 'CODCIE10',
    etiqueta: 'Código CIE-10',
    tipo: 'text',
    longitudMaxima: 5,
    obligatorio: true,
  },
  {
    nombre: 'RMORESMANEJOONCO',
    etiqueta: 'Resultado Manejo Oncológico',
    tipo: 'number',
  },
  {
    nombre: 'RMOESTADOVITAL',
    etiqueta: 'Estado Vital al Finalizar Corte',
    tipo: 'number',
  },
  {
    nombre: 'RMONOVADMINISTRATIVA',
    etiqueta: 'Novedad Administrativa',
    tipo: 'number',
  },
  {
    nombre: 'RMONOVCLINICA',
    etiqueta: 'Novedad Clínica',
    tipo: 'number',
  },
  {
    nombre: 'RMOFECDESAFILIACION',
    etiqueta: 'Fecha Desafiliación EPS',
    tipo: 'date',
  },
  {
    nombre: 'RMOFECMUERTE',
    etiqueta: 'Fecha Muerte',
    tipo: 'date',
  },
  {
    nombre: 'RMOCAUSAMUERTE',
    etiqueta: 'Causa Muerte',
    tipo: 'number',
  },
] as const;
