// Complementa registros importados sin alterar las consultas originales.
export const COMPLETAR_TRATAMIENTO_SQL = `
UPDATE [dbo].[CACIdentificacionGeneral]
SET IDETIPOTRATAMIENTO = @IDETIPOTRATAMIENTO
WHERE TIPDOCUSUARIO = @TIPDOCUSUARIO
  AND NUMDOCUSUARIO = @NUMDOCUSUARIO
  AND CODCIE10 = @CODCIE10
  AND (
    IDETIPOTRATAMIENTO IS NULL
    OR LTRIM(RTRIM(CONVERT(varchar(20), IDETIPOTRATAMIENTO))) = ''
  );
`;
