export const fetchDiagnosticoByIdFolioQuery = (id: number) => {
  return `
    SELECT
    F.OID,
    F.HCFECFOL,
    D.DIACODIGO,
    D.DIANOMBRE,
    DP.HCPDIAPRIN,
    ISNULL(DP.HCPOBSERV, 'SIN OBSERVACIONES') observaciones,
    MD.USUNOMBRE,
    MD.USUDESCRI 
    FROM ADNINGRESO I
    INNER JOIN HCNFOLIO F ON F.ADNINGRESO = I.OID
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    INNER JOIN GENUSUARIO MD ON F.GENMEDICO = MD.OID
    WHERE f.OID =  ${id}  ORDER BY F.HCFECFOL DESC`;
};
