import { MODULES } from './principal';

const GESTION_ACTIVOS_CODE = MODULES.INVENTARIO.SUBS.GESTION_ACTIVOS;
const GESTION_TANQUEOS_CODE = MODULES.INVENTARIO.SUBS.GESTION_TANQUEOS;

export const INN_AUTHORITIES = {
  CODE: MODULES.INVENTARIO.CODE,
  RECEPCION_TECNICA: {
    CODE: MODULES.INVENTARIO.SUBS.RECEPCION_TECNICA,
    GENERAR_CONSULTAR_RECEPC_TECN: `${MODULES.INVENTARIO.SUBS.RECEPCION_TECNICA}001`,
  },
  DOCUMENTOS: {
    CODE: MODULES.INVENTARIO.SUBS.DOCUMENTOS,
    GENERAR_RECIBO_ORDEN_DESPACHO: `${MODULES.INVENTARIO.SUBS.DOCUMENTOS}002`,
  },
  SUMINISTROS: {
    CODE: MODULES.INVENTARIO.SUBS.SUMINISTROS,
    VER: `${MODULES.INVENTARIO.SUBS.SUMINISTROS}001`,
    RECIBIR: `${MODULES.INVENTARIO.SUBS.SUMINISTROS}002`,
    GESTION_SUM_MEZCLA_DEV: `${MODULES.INVENTARIO.SUBS.SUMINISTROS}003`,
  },
  CENTRAL_COMPRAS: {
    CODE: MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS,
    VER_TODAS: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}001`,
    AGREGAR: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}002`,
    APRO_RECH_GERENTE: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}003`,
    COTIZAR: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}004`,
    RECOMENDAR_ITEMS_COTI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}005`,
    APRO_RECH_COTI_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}006`,
    AGREGAR_OC: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}007`,
    PROGRAMAR_OC: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}008`,
    CONTABILIZAR_OC: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}009`,
    PAGAR_OC: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}010`,
    CONFIRMAR_OC_EN_COTI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}011`,
    REPORTAR_ENTREGA: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}012`,
    CAJA_MENOR_EXPRESS: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}013`,
    ELIMINAR: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}014`,
    CARGO_1_APROBAR_RECHAZAR_COTI_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}015`,
    CARGO_2_APROBAR_RECHAZAR_COTI_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}016`,
    CARGO_3_APROBAR_RECHAZAR_COTI_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}017`,
    MOVER_A_OTRO_CENTRO: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}018`,
    VER_INCL_FORBIDDEN_VALUES: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}019`,
    COTI_PREFABRI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}020`,
    COTI_PREFABRI_COMPRA_MAYOR_STOCK_MAXIMO: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}021`,
    COTI_PREFABRI_MODIFICAR_VALORES: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}022`,
    CARGO_4_APROBAR_RECHAZAR_COT_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}023`,
  },
  PRODUCTOS: {
    CODE: MODULES.INVENTARIO.SUBS.PRODUCTOS,
    GESTION_REPORTES: `${MODULES.INVENTARIO.SUBS.PRODUCTOS}001`,
  },
  COTIZACIONES_PREFABRICADAS: {
    CODE: MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS,
    REGISTRAR_SET: `${MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS}001`,
    ADD_PROVEEDOR_TO_SET: `${MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS}002`,
  },
  FARMACIA: {
    CODE: MODULES.INVENTARIO.SUBS.FARMACIA,
    GESTION_INVENTARIO_CICLICO: `${MODULES.INVENTARIO.SUBS.FARMACIA}001`,
    VERIFICAR_INVENTARIO_CICLICO: `${MODULES.INVENTARIO.SUBS.FARMACIA}002`,
    GESTION_DEMANDAS_INSATISFECHAS: `${MODULES.INVENTARIO.SUBS.FARMACIA}003`,
    CONTROL_GASTOS_SOLICITANTE: `${MODULES.INVENTARIO.SUBS.FARMACIA}004`,
    CONTROL_GASTOS_FACTURADOR: `${MODULES.INVENTARIO.SUBS.FARMACIA}005`,
    LEGALIZACION_FACTURAS_SOLICITANTE: `${MODULES.INVENTARIO.SUBS.FARMACIA}006`,
    LEGALIZACION_FACTURAS_FACTURADOR: `${MODULES.INVENTARIO.SUBS.FARMACIA}007`,
    INVENTARIO_ADMIN: `${MODULES.INVENTARIO.SUBS.FARMACIA}008`,
    INVENTARIO_CONTEO: `${MODULES.INVENTARIO.SUBS.FARMACIA}009`,
  },
  SERVICIO_TECNICO: {
    CODE: MODULES.INVENTARIO.SUBS.SERVICIO_TECNICO,
    AGREGAR_SOLICITUDES: `${MODULES.INVENTARIO.SUBS.SERVICIO_TECNICO}001`,
    ATENDER_SOLICITUDES: `${MODULES.INVENTARIO.SUBS.SERVICIO_TECNICO}002`,
    MANAGE_TIPOS_TO_USUARIOS: `${MODULES.INVENTARIO.SUBS.SERVICIO_TECNICO}003`,
  },

  GESTION_ACTIVOS: {
    EQUIPOS: {
      VER: `${GESTION_ACTIVOS_CODE}001`,
      CREAR: `${GESTION_ACTIVOS_CODE}002`,
      EDITAR: `${GESTION_ACTIVOS_CODE}003`,
      CAMBIAR_ESTADO: `${GESTION_ACTIVOS_CODE}004`,
      GESTIONAR: `${GESTION_ACTIVOS_CODE}005`,
      CAMBIAR_ESTADO_DIRECTO: `${GESTION_ACTIVOS_CODE}006`,
      AUDITORIA: {
        VER: `${GESTION_ACTIVOS_CODE}007`,
      },
      SOLICITUDES: {
        RESOLVER: `${GESTION_ACTIVOS_CODE}008`,
        VER: `${GESTION_ACTIVOS_CODE}009`,
      },
    },

    ACTIVIDADES: {
      VER: `${GESTION_ACTIVOS_CODE}010`,
      EJECUTAR: `${GESTION_ACTIVOS_CODE}011`,
      CHEQUEAR: `${GESTION_ACTIVOS_CODE}012`,
      REPROGRAMAR: `${GESTION_ACTIVOS_CODE}013`,
    },

    RECURSOS: {
      VER: `${GESTION_ACTIVOS_CODE}014`,
      GESTIONAR: `${GESTION_ACTIVOS_CODE}015`,
      ASIGNAR_A_ACTIVIDAD: `${GESTION_ACTIVOS_CODE}016`,
    },

    FORMATOS: {
      GESTIONAR: `${GESTION_ACTIVOS_CODE}017`,
      DILIGENCIAR: `${GESTION_ACTIVOS_CODE}018`,
      REVISAR: `${GESTION_ACTIVOS_CODE}019`,
    },

    CATALOGOS: {
      GESTIONAR: `${GESTION_ACTIVOS_CODE}020`,
    },

    CRONOGRAMA: {
      VER: `${GESTION_ACTIVOS_CODE}021`,
    },
  },

  GESTION_TANQUEOS: {
    TANQUEOS: {
      VER: `${GESTION_TANQUEOS_CODE}001`,
      REGISTRAR: `${GESTION_TANQUEOS_CODE}002`,
      RESOLVER: `${GESTION_TANQUEOS_CODE}003`,
      VER_T_SEDES: `${GESTION_TANQUEOS_CODE}004`,
    },

    INCONSISTENCIAS: {
      VER: `${GESTION_TANQUEOS_CODE}005`,
      RESOLVER: `${GESTION_TANQUEOS_CODE}006`,
    },

    VEHICULOS: {
      VER: `${GESTION_TANQUEOS_CODE}007`,
      GESTIONAR: `${GESTION_TANQUEOS_CODE}008`,
    },

    ESTACIONES: {
      VER: `${GESTION_TANQUEOS_CODE}009`,
      GESTIONAR: `${GESTION_TANQUEOS_CODE}010`,
    },

    REPOSITORIOS: {
      CREAR: `${GESTION_TANQUEOS_CODE}011`,
      RECARGAR: `${GESTION_TANQUEOS_CODE}012`,
      VER: `${GESTION_TANQUEOS_CODE}013`,
    },
  },
};
