/* Ejecutar manualmente en la base del contexto HPN. No se ejecuta desde la aplicación. */
CREATE TABLE EKHPNCIREST (
  OID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  CODIGO VARCHAR(50) NOT NULL UNIQUE,
  NOMBRE VARCHAR(100) NOT NULL,
  ORDEN INT NOT NULL UNIQUE,
  ESALTERNATIVO BIT NOT NULL CONSTRAINT DF_CIRUGIAESTADO_ALTERNATIVO DEFAULT 0,
  ESTERMINAL BIT NOT NULL CONSTRAINT DF_CIRUGIAESTADO_TERMINAL DEFAULT 0,
  ACTIVO BIT NOT NULL CONSTRAINT DF_CIRUGIAESTADO_ACTIVO DEFAULT 1
);
GO
INSERT INTO EKHPNCIREST (CODIGO, NOMBRE, ORDEN, ESALTERNATIVO, ESTERMINAL) VALUES
('EN_PREPARACION', 'En preparación', 1, 0, 0),
('INICIA_CIRUGIA', 'Inicia cirugía', 2, 0, 0),
('FINALIZA_CIRUGIA', 'Finaliza cirugía', 3, 0, 0),
('EN_SALA_RECUPERACION', 'En sala de recuperación', 4, 0, 0),
('SALIDA_PACIENTE', 'Salida del paciente', 5, 0, 1),
('CIRUGIA_SUSPENDIDA', 'Cirugía suspendida', 90, 1, 1),
('ACERCARSE_INFORMACION', 'Acercarse a información', 91, 1, 0),
('ACERCARSE_FACTURACION', 'Acercarse a facturación', 92, 1, 0);
GO
CREATE TABLE EKHPNCIRSEG (
  OID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PCNCONSEC VARCHAR(50) NOT NULL,
  ESTADOACTUAL VARCHAR(50) NOT NULL,
  FECHAINICIOPREPARACION DATETIME NULL,
  FECHAINICIOCIRUGIA DATETIME NULL,
  FECHAINICIORECUPERACION DATETIME NULL,
  FECHAFINALIZACION DATETIME NULL,
  USUARIOMODIFICACIONID BIGINT NOT NULL,
  USUARIOMODIFICACIONNOMBRE VARCHAR(150) NOT NULL CONSTRAINT DF_CIRUGIASEGUIMIENTO_USUARIO DEFAULT '',
  CREATEDAT DATETIME NOT NULL CONSTRAINT DF_CIRUGIASEGUIMIENTO_CREATED DEFAULT GETDATE(),
  UPDATEDAT DATETIME NOT NULL CONSTRAINT DF_CIRUGIASEGUIMIENTO_UPDATED DEFAULT GETDATE(),
  CONSTRAINT UX_CIRUGIASEGUIMIENTO_CONSEC UNIQUE (PCNCONSEC),
  CONSTRAINT FK_CIRUGIASEGUIMIENTO_ESTADO FOREIGN KEY (ESTADOACTUAL) REFERENCES EKHPNCIREST(CODIGO)
);
GO
CREATE TABLE EKHPNCIRHIS (
  OID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PCNCONSEC VARCHAR(50) NOT NULL,
  ESTADOANTERIOR VARCHAR(50) NOT NULL,
  ESTADONUEVO VARCHAR(50) NOT NULL,
  USUARIOID BIGINT NOT NULL,
  USUARIONOMBRE VARCHAR(150) NOT NULL CONSTRAINT DF_CIRUGIAHISTORIAL_USUARIO DEFAULT '',
  FECHAHORA DATETIME NOT NULL CONSTRAINT DF_CIRUGIAHISTORIAL_FECHA DEFAULT GETDATE(),
  CONSTRAINT FK_CIRUGIAHISTORIAL_ANTERIOR FOREIGN KEY (ESTADOANTERIOR) REFERENCES EKHPNCIREST(CODIGO),
  CONSTRAINT FK_CIRUGIAHISTORIAL_NUEVO FOREIGN KEY (ESTADONUEVO) REFERENCES EKHPNCIREST(CODIGO)
);
GO
CREATE INDEX IX_CIRUGIAHISTORIAL_CONSEC ON EKHPNCIRHIS (PCNCONSEC);
GO
