IF OBJECT_ID('dbo.EKHPNCIRAGR', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EKHPNCIRAGR (
    OID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(150) NOT NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_EKHPNCIRAGR_ACTIVO DEFAULT (1),
    CREATEDAT DATETIME NOT NULL CONSTRAINT DF_EKHPNCIRAGR_CREATEDAT DEFAULT (GETDATE()),
    UPDATEDAT DATETIME NULL,
    CONSTRAINT UQ_EKHPNCIRAGR_NOMBRE UNIQUE (NOMBRE)
  );
END;
GO

IF OBJECT_ID('dbo.EKHPNCIRAGRSAL', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EKHPNCIRAGRSAL (
    OID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    AGRUPADOR INT NOT NULL,
    SALAQX VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_EKHPNCIRAGRSAL_AGRUPADOR_SALA UNIQUE (AGRUPADOR, SALAQX),
    CONSTRAINT FK_EKHPNCIRAGRSAL_AGRUPADOR
      FOREIGN KEY (AGRUPADOR) REFERENCES dbo.EKHPNCIRAGR(OID) ON DELETE CASCADE
  );
END;
GO
