/* Ejecutar manualmente después de seguimiento-quirurgico.sql. */
ALTER TABLE EKHPNCIREST ADD ESEVENTO BIT NOT NULL CONSTRAINT DF_CIREST_ESEVENTO DEFAULT 0;
GO
UPDATE EKHPNCIREST SET ESEVENTO = 1 WHERE CODIGO IN ('ACERCARSE_INFORMACION', 'ACERCARSE_FACTURACION');
GO
