INSERT INTO EKHPNCIREST (CODIGO, NOMBRE, ORDEN, ESALTERNATIVO, ESTERMINAL, ESEVENTO, ACTIVO)
SELECT 'PROGRAMADO', 'Programado', 0, 0, 0, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM EKHPNCIREST WHERE CODIGO = 'PROGRAMADO');
GO
