export const EQUIPOS_REPOSITORY = Symbol('EQUIPOS_REPOSITORY');
export const SOLICITUD_APROBACION_REPOSITORY = Symbol('SOLICITUD_APROBACION_REPOSITORY');
export const COMPRA_REPOSITORY = Symbol('COMPRA_REPOSITORY');
export const ACCESORIO_UNIDAD_REPOSITORY = Symbol('ACCESORIO_UNIDAD_REPOSITORY');

export const PARTES_REPOSITORY = Symbol('PARTES_REPOSITORY');
export const EVENTO_AUDIT_EQUIPO_REPOSITORY = Symbol('EVENTO_AUDIT_EQUIPO_REPOSITORY');

export const UNIDAD_MEDIDA_REPOSITORY = Symbol('UNIDAD_MEDIDA_REPOSITORY');

export const TIPO_ACTIVO_REPOSITORY = Symbol('TIPO_ACTIVO_REPOSITORY');
export const CLASE_EQUIPO_REPOSITORY = Symbol('CLASE_EQUIPO_REPOSITORY');
export const SUBCLASE_EQUIPO_REPOSITORY = Symbol('SUBCLASE_EQUIPO_REPOSITORY');
export const TIPO_EQUIPO_REPOSITORY = Symbol('TIPO_EQUIPO_REPOSITORY');
export const TIPO_DOC_CATEGORIA_ACTIVO_REPOSITORY = Symbol('TIPO_DOC_CATEGORIA_ACTIVO_REPOSITORY');
export const ACCESORIO_TIPO_EQUIPO_REPOSITORY = Symbol('ACCESORIO_TIPO_EQUIPO_REPOSITORY');
export const AUDIT_TIPO_EQUIPO_REPOSITORY = Symbol('AUDIT_TIPO_EQUIPO_REPOSITORY');
export const PLAN_DEFAULT_TIPO_EQUIPO_REPOSITORY = Symbol('PLAN_DEFAULT_TIPO_EQUIPO_REPOSITORY');
export const DOCUMENTO_TIPO_EQUIPO_REPOSITORY = Symbol('DOCUMENTO_TIPO_EQUIPO_REPOSITORY');

export const MARCA_REPOSITORY = Symbol('MARCA_REPOSITORY');
export const MODELO_REPOSITORY = Symbol('MODELO_REPOSITORY');

export const FORMATO_REPOSITORY = Symbol('FORMATO_MANTENIMIENTO');
export const REGISTRO_ACTIVIDAD_REPOSITORY = Symbol('REGISTRO_ACTIVIDAD_REPOSITORY');
export const REPROGRAMACION_ACTIVIDAD_REPOSITORY = Symbol('REPROGRAMACION_ACTIVIDAD_REPOSITORY');

export const EJECUCION_EXTERNA_REPOSITORY = Symbol('EJECUCION_EXTERNA_REPOSITORY');
export const RECURSO_REPOSITORY = Symbol('RECURSO_REPOSITORY');
export const CRONOGRAMA_REPOSITORY = Symbol('CRONOGRAMA_REPOSITORY');
