export * from './medida.vo';
export * from './periodo-tiempo.vo';
export * from './variables-calibracion.vo';
export * from './registro-fotografico.vo';
export * from './clasificacion-biomedica.vo';
export * from './datos-calibracion.vo';
export * from './datos-tecnicos.vo';
export * from './ficha-tecnica-tipo-equipo.vo';
export * from './reglas-obligatoriedad-tipo-activo.vo';