import { SLN_MODULES } from './common';

export const SLN_AUTHORITIES = {
  CODE: SLN_MODULES.CODE,
  INFORMES_GERENCIALES: {
    CODE: SLN_MODULES.SUBS.INFORMES_GERENCIALES,
    FACTURACION_PERIODO: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}001`,
    ESTADISTICO_PFGP: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}002`,
    ESTADISTICO_RADICACION: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}003`,
    FACTURACION_TERCEROS: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}004`,
    PUEDE_VER_X_FACT_ENTIDADES: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}005`,
    FACT_TERCEROS_INSTITUCION: `${SLN_MODULES.SUBS.INFORMES_GERENCIALES}006`,
  },
  PRODUCTOS: {
    CODE: SLN_MODULES.SUBS.PRODUCTOS,
    CAMBIAR_CONCEPTO_FACTURACION: `${SLN_MODULES.SUBS.PRODUCTOS}001`,
  },
  CONTROL_EGRESOS: {
    CODE: SLN_MODULES.SUBS.CONTROL_EGRESOS,
    CREAR_PENDIENTES: `${SLN_MODULES.SUBS.CONTROL_EGRESOS}001`,
    ASIGNAR_USUARIO: `${SLN_MODULES.SUBS.CONTROL_EGRESOS}002`,
    VER_EGRESOS: `${SLN_MODULES.SUBS.CONTROL_EGRESOS}003`,
  },
  CUENTA_ALTO_COSTO: {
    CODE: SLN_MODULES.SUBS.CUENTA_ALTO_COSTO,
    GESTIONAR: `${SLN_MODULES.SUBS.CUENTA_ALTO_COSTO}001`,
  },
};
