import { MODULES } from './principal';

export const HCN_AUTHORITIES = {
  CODE: MODULES.HISTORIA_CLINICA.CODE,
  BALANCES_ENFERMERIA: {
    CODE: MODULES.HISTORIA_CLINICA.SUBS.BALANCES_ENFERMERIA,
    SABANAS_UCI: `${MODULES.HISTORIA_CLINICA.SUBS.BALANCES_ENFERMERIA}001`,
    REPORTE_SABANAS: `${MODULES.HISTORIA_CLINICA.SUBS.BALANCES_ENFERMERIA}002`,
  },
  EPICRISIS: {
    CODE: MODULES.HISTORIA_CLINICA.SUBS.EPICRISIS,
    DESCONFIRMAR: `${MODULES.HISTORIA_CLINICA.SUBS.EPICRISIS}001`,
  },
  INTERCONSULTAS: {
    CODE: MODULES.HISTORIA_CLINICA.SUBS.INTERCONSULTAS,
    MOSTRAR_PENDIENTES: `${MODULES.HISTORIA_CLINICA.SUBS.INTERCONSULTAS}001`,
    MOSTRAR_TODAS_PENDIENTES_MOBILE: `${MODULES.HISTORIA_CLINICA.SUBS.INTERCONSULTAS}002`,
  },
};
