import { MODULES } from './principal';

export const HPN_AUTHORITIES = {
  CODE: MODULES.HOSPITALIZACION.CODE,
  DIETAS: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}`,
    REGISTRAR: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}001`,
    VER_JORNADA: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}002`,
    FUNCIONES_PROVEEDOR: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}003`,
    ASIGNAR_EXTRAORDINARIAS: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}004`,
    RECIBIR_EN_DESTINO: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}005`,
    REPORTAR_FALTANTES: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}006`,
    VER_FACTURACION: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}007`,
    REGISTRAR_IGNORA_JORNADA: `${MODULES.HOSPITALIZACION.SUBS.DIETAS}008`,
  },
  GESTION_CLINICA: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}`,
    GESTIONAR_AREAS: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}001`,
    ADMINISTRAR_GESTIONES: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}002`,
    GESTIONAR_PACIENTES: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}003`,
    TIEMPOS_EGRESOS: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}004`,
    REPORTE_VALORES_CRITICOS: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}005`,
    VER_TODOS_REPO_VAL_CRI: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}006`,
    AUDITAR_REPORTE_VALORES_CRITICOS: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}007`,
    GESTIONAR_TRANSLADO_ASIGNADOS: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}008`,
    REGI_ASIGNAR_MOVIL: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}009`,
    ENTREGA_TURNO: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}010`,
    GESTION_TURNO: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}011`,
    AGREGAR_TRASLADO: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}012`,
    GESTION_TRASLADO: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}013`,
    SEGUIMIENTO_TRASLADO: `${MODULES.HOSPITALIZACION.SUBS.GESTION_CLINICA}014`,
  },
  CAMAS: {
    RESERVA: `${MODULES.HOSPITALIZACION.SUBS.CAMAS}001`,
    VER_CAMAS: `${MODULES.HOSPITALIZACION.SUBS.CAMAS}002`,
  },
  CENSOS: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.CENSOS}`,
    PACIENTES: `${MODULES.HOSPITALIZACION.SUBS.CENSOS}001`,
    CAMAS: `${MODULES.HOSPITALIZACION.SUBS.CENSOS}002`,
  },
  TRIAGE: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.TRIAGE}`,
    TABLERO: `${MODULES.HOSPITALIZACION.SUBS.TRIAGE}001`,
  },
  APIS: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.APIS}`,
    RECORDATORIO_CITAS: `${MODULES.HOSPITALIZACION.SUBS.APIS}001`,
  },
  AUDITORIA: {
    CODE: `${MODULES.HOSPITALIZACION.SUBS.AUDITORIA}`,
    GESTIONAR: `${MODULES.HOSPITALIZACION.SUBS.AUDITORIA}001`,
  },
};
