import { MODULES } from './principal';

export const SEC_AUTHORITIES = {
  CODE: MODULES.GENERAL.CODE,
  ADMIN: `${MODULES.GENERAL.CODE}001`,
  SECURITY: {
    ADMIN: `${MODULES.GENERAL.SUBS.SECURITY}001`,
  },
  AUTHORITIES: {
    CODE: MODULES.GENERAL.SUBS.AUTHORITIES,
    MANAGE_ALL_AUTHORITIES: `${MODULES.GENERAL.SUBS.AUTHORITIES}001`,
    CREATE_AUTHORITIES: `${MODULES.GENERAL.SUBS.AUTHORITIES}002`,
  },
};
