export const fetchByConsecutivo = (consecutivo: number) => {
  return `SELECT        
SLNORDSAL.SRACONSEC as SALIDA_NUMERO,
--SLNORDSAL.SRAORDANU AS ANULADO, 
SLNORDSAL.SRAFECSAL AS FECHA_HORA_SALIDA, 
SLNORDSAL.SRAOBSERV AS OBSERVACION, 
ADNINGRESO.AINCONSEC AS INGRESO, 
--ADNINGRESO.AINFECING AS FECHA_INGRESO,
HPNDEFCAM.HCACODIGO AS CAMA,
HPNSUBGRU.HSUNOMBRE AS SERVICIO,
GENUSUARIO.USUNOMBRE AS USUARIO_CREO_ORDEN_SALIDA,
GENUSUARIO.USUDESCRI AS NOMBRE_USUARIO,
GENUSUARIO.OID AS ID_USUARIO,
GENROL.ROLNOMBRE AS ROL, 
GENPACIEN.PACNUMDOC AS PACIENTE,
GENPACIEN.GPAFECNAC AS FECHA_NAC_PACIENTE, 
GENPACIEN.GPANOMCOM AS NOMBRE_PACIENTE,
GENDETCON.GDECODIGO AS COD_PLAN, 
GENDETCON.GDENOMBRE AS NOMBRE_PLAN
FROM SLNORDSAL 
INNER JOIN GENUSUARIO ON SLNORDSAL.GENUSUARIO1 = GENUSUARIO.OID 
INNER JOIN ADNINGRESO ON SLNORDSAL.ADNINGRES1 = ADNINGRESO.OID
INNER JOIN HPNDEFCAM ON ADNINGRESO.HPNDEFCAM = HPNDEFCAM.OID
INNER JOIN HPNSUBGRU ON HPNDEFCAM.HPNSUBGRU = HPNSUBGRU.OID
INNER JOIN GENROL ON GENUSUARIO.GENROL = GENROL.OID 
INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID WHERE SLNORDSAL.SRACONSEC =${consecutivo}`;
};
