/* import { ESTADOS_ASISTENCIA, EstadoAsistenciaTypeCode } from '@hpn/lgc/tas/types/gcn/traslados-asistenciales';

export const ESTADOS_TRASLADO_ASISTENCIAL = {
  CREADO: ESTADOS_ASISTENCIA.CREADO.getCode(),
  ASIGNADO: ESTADOS_ASISTENCIA.ASIGNADO.getCode(),
  ENTREGADO_A_MOVIL: ESTADOS_ASISTENCIA.ENTREGADO.getCode(),
  RECIBIDO_POR_TRIPULACION: ESTADOS_ASISTENCIA.RECIBIDO.getCode(),
  EN_CURSO: ESTADOS_ASISTENCIA.EN_CURSO.getCode(),
  FINALIZADO_POR_TRIPULACION: ESTADOS_ASISTENCIA.FINALIZADO.getCode(),
  PENDIENTE_RETORNO: ESTADOS_ASISTENCIA.PENDIENTE_RETORNO.getCode(),
  PENDIENTE_REVISION_CENTRAL: ESTADOS_ASISTENCIA.FINALIZADO.getCode(),
  CERRADO_OK: ESTADOS_ASISTENCIA.APROBADO.getCode(),
  DEVUELTO_POR_CENTRAL: ESTADOS_ASISTENCIA.DEVUELTO.getCode(),
  SOLICITUD_CANCELACION: ESTADOS_ASISTENCIA.CANCELACION_SOLICITADA.getCode(),
  CANCELACION_RECHAZADA: ESTADOS_ASISTENCIA.CANCELACION_RECHAZADA.getCode(),
  CANCELADO: ESTADOS_ASISTENCIA.CANCELADO.getCode(),
  RECHAZADO_POR_CENTRAL: ESTADOS_ASISTENCIA.RECHAZADO.getCode(),
} as const;

export type EstadoTrasladoAsistencialCode = EstadoAsistenciaTypeCode; */
