export const KEYS = {
  FILE_RESPONSE: 'FILE_RESPONSE',
};

export const MTD = {
  PUBLIC_MTD: 'IS_PUBLIC_MTD',
  ROLES_MTD: 'ROLES_MTD',
  FILE_RESPONSE_MTD: 'FILE_RESPONSE_MTD',
  FILE_FIELD_MTD: 'FILE_FIELD_MTD',
  MULTIPLE_MTD: 'MULTIPLE_MTD',
  DESTINATION_MTD: 'DESTINATION_MTD',
};
