export const CONSECUTIVOS_CODES = {
  SOLICITUD_APROB: 'SOLICITUD_APROB',
  TANQUEOS: 'TAN',
  ABASTECIMIENTO_TAN: 'ABA-TAN',
  ADQUISICION: 'ADQ',
  ACTIVO: 'AF',
  REG_ACTIVIDAD: {
    MANT: 'MNT',
    CALIB: 'CAL',
    NATURALEZA: {
      PREVENTIVA: 'PRV',
      CORRECTIVA: 'CRT',
      PREDICTIVA: 'PRD',
    },
  },
};
