export const boletaQuirurgicaGestorQxQuery = () => `
    SELECT * FROM GCMCIRDERINTRAHOSPGESTORQ WHERE INGRESO = @0 AND FOLIO = @1
`;

//response----> INGRESO	FECHA_RECEPCION	OTRAS_VALORACIONES	OBSERVACION	estado_AUTORIZACION	folio	REQ_MAOS	OBSERVACION	estado_PROG	folio	PENDIENTE6	PENDIENTE7	SERVICIO	OBSERVACION	FECHA_FIN	cambio_cups	usuario	folio
