import { Injectable } from '@nestjs/common';
import { BaseSource } from '@sln/old/common/infrastructure/bases';
import { GcmContexts } from '@common/application/constants';

@Injectable()
export class PgpFacturado extends BaseSource {
  /**
   *
   * @param fechaInicio Fecha Inical
   * @param fechaFin Fecha Final
   * @returns Consumido Por cada Contrato PFPG
   */
  async consumido(fechaInicio: string, fechaFin: string, centro1: number, centro2: number) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `Select
        GENDETCON.GDECODIGO As NContrato,
        GENDETCON.GDENOMBRE As Contrato,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
        SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
        ISNULL(G.LIMITE, 0) TotalFacturado,
        COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
        ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
        ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
       ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
      Where 
    CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 AND @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO = 'I202'
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE;`,
        [fechaInicio, fechaFin]
      );
    }
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      return await this.consolidadoConsumido(fechaInicio, fechaFin, centro1, centro2);
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      return this.conn.query(
        `Select
        GENDETCON.GDECODIGO As NContrato,
        GENDETCON.GDENOMBRE As Contrato,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
        SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
        ISNULL(G.LIMITE, 0) TotalFacturado,
        COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
        ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
        ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
        ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
      Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO IN ('8000', '8001', '8002', '8005')
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
      UNION
       Select
        '8003 - 8004' As NContrato,
        'PGP ASMET SALUD SUBS - CONTR' As Contrato,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
        SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
        ISNULL(G.LIMITE, 0) TotalFacturado,
        COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
        ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
        ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
        ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8004'
      Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO IN('8003',  '8004')
      GROUP BY G.LIMITE;`,
        [fechaInicio, fechaFin]
      );
    }
  }

  /**
   *
   * @param contrato1 Contrato Inicial
   * @param contrato2 Contrato Final
   * @param fechaInicio Fecha Inicial
   * @param fechaFin Fecha Final
   * @returns Agrupadores Correspondientes a un Contrato
   */
  async Agrupadores(
    contrato1: string,
    contrato2: string,
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `SELECT 
        F.AGRUPADOR Agrupador,
        ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
        F.TOTALFACTURADO TotalFacturado,
        COUNT(CONS.AINCONSEC) Iteraciones, 
        F.NEVENTOS Eventos,
        (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
        ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
        (F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)) CmeFacturado,
        ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
        ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
        ISNULL(ROUND((SUM(CONS.SFAVALCAR)/NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
         FROM ADNINGRESO RIGHT JOIN 
        (
        SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
           ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
           ADNINGRESO.AINCONSEC,
          SLNFACTUR.SFAVALCAR,
          SLNFACTUR.SFAVALREC
            FROM SLNFACTUR
             INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
             INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
             INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
             LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
             LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
             LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
             LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
             LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODCUP)) = G.COD_CUPS	
             AND G.CONTRATO = @2  
            WHERE 
            SLNFACTUR.SFATIPDOC = 17
            AND SLNFACTUR.SFADOCANU = N'0' 
            AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
            AND GENDETCON.GDECODIGO = @2
            AND SLNORDSER.SOSESTADO = 1
            GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
            ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
            )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
            RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
            WHERE F.GDECODIGO =  @2
            GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
            ORDER BY F.ORDEN DESC;`,
        [fechaInicio, fechaFin, contrato1]
      );
    }
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      if (contrato1 == '8005') {
        return await this.conn.query(
          `SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.EVENTOS Eventos,
          (F.EVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.EVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
      SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
              SLNFACTUR.SFAVALCAR,
              SLNFACTUR.SFAVALREC
                  FROM SLNFACTUR
                   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                   LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                   LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                     AND G.CONTRATO = @3   
                  WHERE 
                  SLNFACTUR.SFATIPDOC = 17
                  AND SLNFACTUR.SFADOCANU = N'0' 
                  AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                  AND GENDETCON.GDECODIGO IN(@2, @3)
                  AND SLNORDSER.SOSESTADO = 1
                  GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
                  ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
                  )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                  RIGHT JOIN GCMFICHCON2 F ON F.AGRUPADOR = CONS.AGRUPADOR
                  LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO =  @3
				          AND ADNINGRESO.ADNCENATE IN(@4, @5)
                  GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.EVENTOS
                  ORDER BY F.ORDEN DESC;
          `,
          [fechaInicio, fechaFin, contrato1, contrato2, centro1, centro2]
        );
      } else if (contrato1 == '8009') {
        return await this.conn.query(
          `SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.EVENTOS Eventos,
          (F.EVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.EVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
      SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
              SLNFACTUR.SFAVALCAR,
              SLNFACTUR.SFAVALREC
                  FROM SLNFACTUR
                   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                   LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                   LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                     AND G.CONTRATO = '8010'   
                  WHERE 
                  SLNFACTUR.SFATIPDOC = 17
                  AND SLNFACTUR.SFADOCANU = N'0' 
                  AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                  AND GENDETCON.GDECODIGO IN(@2)
                  AND SLNORDSER.SOSESTADO = 1
                  GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
                  ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
          )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                  RIGHT JOIN GCMFICHCON2 F ON F.AGRUPADOR = CONS.AGRUPADOR
                  LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO =  '8010'
				          AND ADNINGRESO.ADNCENATE IN(@3, @4)
                  GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.EVENTOS
                  ORDER BY F.ORDEN DESC;
          `,
          [fechaInicio, fechaFin, contrato1, centro1, centro2]
        );
      } else if (contrato1 == '2020') {
        return await this.conn.query(
          `SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.EVENTOS Eventos,
          (F.EVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.EVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
          SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
              FROM SLNFACTUR
               INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
               INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
               INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
               LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
               LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
               LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
               LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
               LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS	
               AND G.CONTRATO = @2   
              WHERE 
              SLNFACTUR.SFATIPDOC = 17
              AND SLNFACTUR.SFADOCANU = N'0' 
              AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 And @1
              AND GENDETCON.GDECODIGO IN(@3, @2)
              AND SLNORDSER.SOSESTADO = 1
              GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
              ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
              )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
              RIGHT JOIN GCMFICHCON2 F ON F.AGRUPADOR = CONS.AGRUPADOR
              LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO = @2
				          AND ADNINGRESO.ADNCENATE IN(@4, @5)
              GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.EVENTOS
              ORDER BY F.ORDEN DESC;
`,
          [fechaInicio, fechaFin, contrato1, contrato2, centro1, centro2]
        );
      } else {
        return await this.conn.query(
          `	SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.EVENTOS Eventos,
          (F.EVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.EVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
          SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
              FROM SLNFACTUR
               INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
               INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
               INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
               LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
               LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
               LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
               LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
               LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS	
               AND G.CONTRATO = @2   
              WHERE 
              SLNFACTUR.SFATIPDOC = 17
              AND SLNFACTUR.SFADOCANU = N'0' 
              AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
              AND GENDETCON.GDECODIGO IN(@2)
              AND SLNORDSER.SOSESTADO = 1
              GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
              ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
              )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
              RIGHT JOIN GCMFICHCON2 F ON F.AGRUPADOR = CONS.AGRUPADOR
              LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO =  @2
				          AND ADNINGRESO.ADNCENATE IN(@3, @4)
              GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.EVENTOS
              ORDER BY F.ORDEN DESC;
              `,
          [fechaInicio, fechaFin, contrato1, centro1, centro2]
        );
      }
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      if (contrato1 === '8003 - 8004') {
        return await this.conn.query(
          `SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.NEVENTOS Eventos,
          (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
      SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
              SLNFACTUR.SFAVALCAR,
              SLNFACTUR.SFAVALREC
                  FROM SLNFACTUR
                   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                   LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                   LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                     AND G.CONTRATO = '8004'  
                  WHERE 
                  SLNFACTUR.SFATIPDOC = 17
                  AND SLNFACTUR.SFADOCANU = N'0' 
                  AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                  AND GENDETCON.GDECODIGO IN('8003', '8004')
                  AND SLNORDSER.SOSESTADO = 1
                  GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
                  ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
          )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                  RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
                  LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO =  '8004'
                  GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
                  ORDER BY F.ORDEN DESC`,
          [fechaInicio, fechaFin]
        );
      } else {
        return await this.conn.query(
          `SELECT 
          F.AGRUPADOR Agrupador,
          ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
          ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
          COUNT(CONS.AINCONSEC) Iteraciones, 
          F.NEVENTOS Eventos,
          (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
          ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
          ISNULL((F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)), 0) CmeFacturado,
          ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
          ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
          ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
           FROM ADNINGRESO RIGHT JOIN 
          (
      SELECT  
          TOP 1 WITH TIES
          ISNULL(G.ORDEN, 0) ORDEN,
             ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
             ADNINGRESO.AINCONSEC,
              SLNFACTUR.SFAVALCAR,
              SLNFACTUR.SFAVALREC
                  FROM SLNFACTUR
                   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                   LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                   LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                     AND G.CONTRATO = @2 
                  WHERE 
                  SLNFACTUR.SFATIPDOC = 17
                  AND SLNFACTUR.SFADOCANU = N'0' 
                  AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                  AND GENDETCON.GDECODIGO IN(@2)
                  AND SLNORDSER.SOSESTADO = 1
                  GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
                  ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
          )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                  RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
                  LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                  WHERE F.GDECODIGO = @2 
                  GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
                  ORDER BY F.ORDEN DESC`,
          [fechaInicio, fechaFin, contrato1]
        );
      }
    }
  }

  async HistorialAgrupadores(
    contrato1: string,
    ingreso: string,
    fechaInicio: string,
    fechaFin: string
  ) {
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      if (
        contrato1 === '8001' ||
        contrato1 === '8010' ||
        contrato1 === '8013' ||
        contrato1 === '8018' ||
        contrato1 === '8021'
      ) {
        return await this.conn.query(
          `SELECT 
          ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
          SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
         FROM SLNFACTUR SLNFACTUR
          INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
          INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
          INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
          LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
          LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
          LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
         AND G.CONTRATO = @0
        WHERE 
         SLNFACTUR.SFATIPDOC = 17
         AND SLNFACTUR.SFADOCANU = N'0' 
         AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
         AND GENDETCON.GDECODIGO BETWEEN '8001' AND '8021'
         AND SLNORDSER.SOSESTADO = 1
         AND ADNINGRESO.AINCONSEC = @1
         GROUP BY 
         ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
         ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC;`,
          [contrato1, ingreso, fechaInicio, fechaFin]
        );
      }
      if (contrato1 === '8005' || contrato1 === '8005 - 8006' || contrato1 === '8009') {
        return await this.conn.query(
          `SELECT 
        ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
        SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
       FROM SLNFACTUR SLNFACTUR
        INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
        INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
        LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
        LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
       AND G.CONTRATO = '8006'
      WHERE 
       SLNFACTUR.SFATIPDOC = 17
       AND SLNFACTUR.SFADOCANU = N'0' 
       AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @1 AND @2
       AND GENDETCON.GDECODIGO BETWEEN '8001' AND '8021'
       AND SLNORDSER.SOSESTADO = 1
       AND ADNINGRESO.AINCONSEC = @0	
       GROUP BY 
       ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
       ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC`,
          [ingreso, fechaInicio, fechaFin]
        );
      }
      if (contrato1 === '8019 - 8020') {
        return await this.conn.query(
          `SELECT 
          ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
          SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
         FROM SLNFACTUR SLNFACTUR
          INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
          INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
          INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
          LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
          LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
          LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
         AND G.CONTRATO = '8020'
        WHERE 
         SLNFACTUR.SFATIPDOC = 17
         AND SLNFACTUR.SFADOCANU = N'0' 
         AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @1 AND @2
         AND GENDETCON.GDECODIGO BETWEEN '8001' AND '8021'
         AND SLNORDSER.SOSESTADO = 1
         AND ADNINGRESO.AINCONSEC = @0	
         GROUP BY 
         ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
         ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC`,
          [ingreso, fechaInicio, fechaFin]
        );
      }
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      if (contrato1 === '8000' || contrato1 === '8005') {
        return await this.conn.query(
          `SELECT 
          ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
          SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
         FROM SLNFACTUR SLNFACTUR
          INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
          INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
          INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
          LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
          LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
          LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
         AND G.CONTRATO = @0
        WHERE 
         SLNFACTUR.SFATIPDOC = 17
         AND SLNFACTUR.SFADOCANU = N'0' 
         AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
         AND GENDETCON.GDECODIGO BETWEEN '8000' AND '8005'
         AND SLNORDSER.SOSESTADO = 1
         AND ADNINGRESO.AINCONSEC = @1	
         GROUP BY 
         ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
         ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC`,
          [contrato1, ingreso, fechaInicio, fechaFin]
        );
      }
      if (contrato1 === '8003 - 8004') {
        return await this.conn.query(
          `SELECT 
          ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
          SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
         FROM SLNFACTUR SLNFACTUR
          INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
          INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
          INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
          LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
          LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
          LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
         AND G.CONTRATO = '8004'
        WHERE 
         SLNFACTUR.SFATIPDOC = 17
         AND SLNFACTUR.SFADOCANU = N'0' 
         AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @1 AND @2
         AND GENDETCON.GDECODIGO BETWEEN '8000' AND '8005'
         AND SLNORDSER.SOSESTADO = 1
         AND ADNINGRESO.AINCONSEC = @0	
         GROUP BY 
         ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
         ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC`,
          [ingreso, fechaInicio, fechaFin]
        );
      }
    }
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `SELECT 
        ISNULL(G.AGRUPADOR, 'EVENTOS')Agrupador,
        SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
       FROM SLNFACTUR SLNFACTUR
        INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
        INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
        LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
        LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODCUP)) = G.COD_CUPS
       AND G.CONTRATO = 'I202'
      WHERE 
       SLNFACTUR.SFATIPDOC = 17
       AND SLNFACTUR.SFADOCANU = N'0' 
       AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @1 AND @2
       AND GENDETCON.GDECODIGO = 'I202'
       AND SLNORDSER.SOSESTADO = 1
       AND ADNINGRESO.AINCONSEC = @0	
       GROUP BY 
       ADNINGRESO.AINCONSEC, G.AGRUPADOR, G.ORDEN
       ORDER BY ADNINGRESO.AINCONSEC, G.ORDEN DESC`,
        [ingreso, fechaInicio, fechaFin]
      );
    }
  }

  /**
   *
   * @param agrupador Agrupador para buscar al paciente
   * @param contrato1 contrato Inicial
   * @param contrato2 Contrato Final
   * @param fechaInicio Fecha Inicial
   * @param fechaFinal Fecha Final
   * @returns Pacientes que pertenecen a un agrupador de un contrato facturado
   */
  async Pacientes(
    agrupador: string,
    contrato1: string,
    contrato2: string,
    fechaInicio: string,
    fechaFinal: string,
    centro1: number,
    centro2: number
  ) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @2) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteraciones
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODCUP)) = G.COD_CUPS
                 AND G.CONTRATO = @2
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO = @2 --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                WHERE CONS.Agrupador = @3 --Agrupador
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC`,
        [fechaInicio, fechaFinal, contrato1, agrupador]
      );
    }
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      if (contrato1 == '8005') {
        return await this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON2 WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @2) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteracinoes
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
           ISNULL(G.ORDEN, 0) ORDEN,
           ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @2 
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @3 AND @4
                AND GENDETCON.GDECODIGO BETWEEN @1 AND @2 --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
				        AND ADNINGRESO.ADNCENATE IN(@5, @6)
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;
        `,
          [agrupador, contrato1, contrato2, fechaInicio, fechaFinal, centro1, centro2]
        );
      } else if (contrato1 == '8009') {
        return await this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON2 WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @2) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteracinoes
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
           ISNULL(G.ORDEN, 0) ORDEN,
           ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = '8010'
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @3 AND @4
                AND GENDETCON.GDECODIGO BETWEEN @1 AND @2 --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
				        AND ADNINGRESO.ADNCENATE IN(@5, @6)
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;
        `,
          [agrupador, contrato1, contrato2, fechaInicio, fechaFinal, centro1, centro2]
        );
      } else if (contrato1 == '8020') {
        return await this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON2 WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @1) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteracinoes
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
           ISNULL(G.ORDEN, 0) ORDEN,
           ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @1
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @3 AND @4
                AND GENDETCON.GDECODIGO IN(@2, @1) --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
				        AND ADNINGRESO.ADNCENATE IN(@5, @6)
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;
        `,
          [agrupador, contrato1, contrato2, fechaInicio, fechaFinal, centro1, centro2]
        );
      } else {
        return await this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON2 WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @1) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteraciones
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @1
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
                AND GENDETCON.GDECODIGO = @1 --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
				        AND ADNINGRESO.ADNCENATE IN(@4, @5)
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;
        `,
          [agrupador, contrato1, fechaInicio, fechaFinal, centro1, centro2]
        );
      }
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      if (contrato1 === '8003 - 8004') {
        return this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = '8004') Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteraciones
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = '8004'
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
                AND GENDETCON.GDECODIGO IN('8004', '8003') --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;`,
          [agrupador, contrato1, fechaInicio, fechaFinal]
        );
      } else {
        return this.conn.query(
          `SELECT 
        CONS.AINCONSEC Ingreso,
        CONS.GPANOMCOM Paciente,
        CONS.Agrupador,
        SUM(CONS.SFAVALCAR) AS TotalEjecutado,
        DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) As DiasEstancia,
        (SELECT CME FROM GCMFICHCON WHERE AGRUPADOR = CONS.Agrupador AND GDECODIGO = @1) Cme,
        SUM(CONS.SFAVALREC) AS TotalAnticipo,
        COUNT(CONS.AINCONSEC) Iteraciones
         FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC,
           GENPACIEN.GPANOMCOM,
            SLNFACTUR.SFAVALCAR,
            SLNFACTUR.SFAVALREC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @1
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
                AND GENDETCON.GDECODIGO = @1 --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC, GPANOMCOM
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE CONS.Agrupador = @0 --Agrupador
                GROUP BY CONS.Agrupador, CONS.AINCONSEC, CONS.GPANOMCOM, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE
                ORDER BY TotalEjecutado DESC;`,
          [agrupador, contrato1, fechaInicio, fechaFinal]
        );
      }
    }
  }

  /**
   *
   * @param ingreso Ingreso del paciente
   * @param contrato Contrato(no es necesario)
   * @param fechaInicio Fecha Inicial
   * @param fechaFin Fecha Final
   * @returns Servicios de un paciente de cualquier contrato
   */
  async ServiciosPaciente(
    ingreso: number,
    contrato: string,
    fechaInicio: string,
    fechaFin: string
  ) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `SELECT 
        IsNull(GENSERIPS.SIPCODCUP, 'MEDICAMENTOS') AS ServicioCodigo,
        IsNull(GENSERIPS.SIPNOMBRE, 'MEDICAMENTOS') AS ServicioNombre,
        GENARESER.GASCODIGO AS AreaCodigo,
        GENARESER.GASNOMBRE AS AreaNombre, 
     SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
    FROM SLNFACTUR SLNFACTUR
     INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
     INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
     LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
     INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
     INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
     LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
     LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
     LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
   WHERE 
    SLNFACTUR.SFATIPDOC = 17
    AND SLNFACTUR.SFADOCANU = N'0' 
    AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
    AND GENDETCON.GDECODIGO = @3
    AND SLNORDSER.SOSESTADO = 1
    AND ADNINGRESO.AINCONSEC = @2
    GROUP BY 
    GENARESER.GASCODIGO,
    GENARESER.GASNOMBRE,
    GENSERIPS.SIPCODCUP,
    GENSERIPS.SIPNOMBRE
    ORDER BY 
    TotalEjecutado DESC `,
        [fechaInicio, fechaFin, ingreso, contrato]
      );
    }
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      return await this.conn.query(
        `SELECT 
      IsNull(GENSERIPS.SIPCODIGO, 'MEDICAMENTOS') AS ServicioCodigo,
      IsNull(GENSERIPS.SIPNOMBRE, 'MEDICAMENTOS') AS ServicioNombre,
      GENARESER.GASCODIGO AS AreaCodigo,
      GENARESER.GASNOMBRE AS AreaNombre, 
	 SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
  FROM SLNFACTUR SLNFACTUR
   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
   LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
   INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
 WHERE 
	SLNFACTUR.SFATIPDOC = 17
	AND SLNFACTUR.SFADOCANU = N'0' 
	AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @2 AND @3
	AND GENDETCON.GDECODIGO BETWEEN '8001' AND '8021'
	AND SLNORDSER.SOSESTADO = 1
	AND ADNINGRESO.AINCONSEC = @0	
	GROUP BY 
	GENARESER.GASCODIGO,
	GENARESER.GASNOMBRE,
	GENSERIPS.SIPCODIGO,
	GENSERIPS.SIPNOMBRE
  ORDER BY 
	TotalEjecutado DESC `,
        [ingreso, contrato, fechaInicio, fechaFin]
      );
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      return this.conn.query(
        `SELECT 
        IsNull(GENSERIPS.SIPCODIGO, 'MEDICAMENTOS') AS ServicioCodigo,
        IsNull(GENSERIPS.SIPNOMBRE, 'MEDICAMENTOS') AS ServicioNombre,
        GENARESER.GASCODIGO AS AreaCodigo,
        GENARESER.GASNOMBRE AS AreaNombre, 
     SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) AS TotalEjecutado
    FROM SLNFACTUR SLNFACTUR
     INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
     INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
     LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
     INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
     INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
     LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
     LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
     LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
   WHERE 
    SLNFACTUR.SFATIPDOC = 17
    AND SLNFACTUR.SFADOCANU = N'0' 
    AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @1 AND @2
    AND GENDETCON.GDECODIGO BETWEEN '8000' AND '8005'
    AND SLNORDSER.SOSESTADO = 1
    AND ADNINGRESO.AINCONSEC = @0	
    GROUP BY 
    GENARESER.GASCODIGO,
    GENARESER.GASNOMBRE,
    GENSERIPS.SIPCODIGO,
    GENSERIPS.SIPNOMBRE
    ORDER BY 
    TotalEjecutado DESC `,
        [ingreso, fechaInicio, fechaFin]
      );
    }
  }

  /**
   *
   * @param fechaInicio Fecha Inicial
   * @param fechaFin Fecha Final
   * @param contrato Contrato
   * @returns Total ejecutado por cada dia Del agrupador escogido
   */
  async TotalEjecutadoDiario(fechaInicio: string, fechaFin: string, contrato: string) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `SELECT 
        ISNULL(CONS.NContrato, 'I202') NContrato,
        ISNULL(CONS.Contrato, 'PGP NUEVA EPS S.A.S')Contrato,
        G.DayNumberOfMonth Dia,
        ISNULL(CONS.TotalEjecutado, 0) TotalEjecutado
        FROM 
        GCMDIMFECHA G LEFT JOIN(
         Select
          GENDETCON.GDECODIGO As NContrato,
          GENDETCON.GDENOMBRE As Contrato,
          (G.LIMITE/30) VMedio,
          DAY(SLNFACTUR.SFAFECFAC) Dia,
          SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado
        From SLNFACTUR SLNFACTUR
          Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
          Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
          LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
          LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
          LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
        Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
          AND  SLNFACTUR.SFADOCANU = N'0'
          and SLNFACTUR.SFATIPDOC = 17
          AND GENDETCON.GDECODIGO = @2
        GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, day(SLNFACTUR.SFAFECFAC), G.LIMITE
        )AS CONS ON CONS.Dia = G.DayNumberOfMonth
        WHERE CONVERT(DATE, G.Date, 103) BETWEEN @0 AND @1
        `,
        [fechaInicio, fechaFin, contrato]
      );
    }
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      return await this.conn.query(
        `SELECT 
      ISNULL(CONS.NContrato, '8001') NContrato,
      ISNULL(CONS.Contrato, 'PGP NUEVA EPS- CONTRIBUTIVO')Contrato,
      G.DayNumberOfMonth Dia,
      ISNULL(CONS.TotalEjecutado, 0) TotalEjecutado
      FROM 
      GCMDIMFECHA G LEFT JOIN(
       Select
        GENDETCON.GDECODIGO As NContrato,
        GENDETCON.GDENOMBRE As Contrato,
        (G.LIMITE/30) VMedio,
        DAY(SLNFACTUR.SFAFECFAC) Dia,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
      Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO = @2
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, day(SLNFACTUR.SFAFECFAC), G.LIMITE
      )AS CONS ON CONS.Dia = G.DayNumberOfMonth
      WHERE CONVERT(DATE, G.Date, 103) Between @0 And @1;
       
    `,
        [fechaInicio, fechaFin, contrato]
      );
    }
  }

  /**
   *
   * @param fechaInicio Fecha Inicial
   * @param fechaFin Fecha Final
   * @param contrato Contrato
   * @returns Total ejecutado diario para el contrato de asmet salud
   */
  async TotalEjecutadoDiarioAsmet(fechaInicio: string, fechaFin: string, contrato: string) {
    if (this.auth.context === GcmContexts.ALTACENTRO) {
      return await this.conn.query(
        `SELECT 
      ISNULL(CONS.NContrato, 'ASMET') NContrato,
      ISNULL(CONS.Contrato, 'PGP ASMET SALUD SUBS - CONTR' )Contrato,
      G.DayNumberOfMonth Dia,
      ISNULL(CONS.TotalEjecutado, 0) TotalEjecutado
      FROM 
      GCMDIMFECHA G LEFT JOIN(
       Select
        'ASMET' As NContrato,
        'PGP ASMET SALUD SUBS - CONTR ' As Contrato,
        DAY(SLNFACTUR.SFAFECFAC) Dia,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
      Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO BETWEEN '8019' AND '8020'
      GROUP BY day(SLNFACTUR.SFAFECFAC)
      ) AS CONS ON CONS.Dia = G.DayNumberOfMonth
      WHERE CONVERT(DATE, G.Date, 103) Between @0 And @1; 
    `,
        [fechaInicio, fechaFin, contrato]
      );
    }
    if (this.auth.context === GcmContexts.AGUACHICA) {
      return this.conn.query(
        `SELECT 
      ISNULL(CONS.NContrato, '8003 - 8004') NContrato,
      ISNULL(CONS.Contrato, 'PGP ASMET SALUD EPS - SUBS - CONTR')Contrato,
      G.DayNumberOfMonth Dia,
      ISNULL(CONS.TotalEjecutado, 0) TotalEjecutado
      FROM 
      GCMDIMFECHA G LEFT JOIN(
       Select
        '8003 - 8004' As NContrato,
        'PGP ASMET SALUD EPS - SUBS - CONTR' As Contrato,
        (G.LIMITE/30) VMedio,
        DAY(SLNFACTUR.SFAFECFAC) Dia,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8004'
      Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO IN('8003', '8004')
      GROUP BY day(SLNFACTUR.SFAFECFAC), G.LIMITE
      )AS CONS ON CONS.Dia = G.DayNumberOfMonth
      WHERE CONVERT(DATE, G.Date, 103) Between @0 And @1;`,
        [fechaInicio, fechaFin]
      );
    }
  }

  async largasEstancias(
    fechaInicio: string,
    fechaFin: string,
    contrato1: number,
    contrato2: number
  ) {
    if (this.auth.context === GcmContexts.VALLEDUPAR) {
      return await this.conn.query(
        `
      SELECT 
        CONS.Agrupador,
	    	COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = 'I202'
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO = 'I202' --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
                order by cons.ORDEN DESC`,
        [fechaInicio, fechaFin]
      );
    } else if (this.auth.context === GcmContexts.ALTACENTRO) {
      if (contrato1 == 8005 && contrato2 == 8006) {
        return await this.conn.query(
          `
        SELECT 
        CONS.Agrupador,
		    COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @3
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO in (@3, @2) --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
				        order by cons.ORDEN DESC`,
          [fechaInicio, fechaFin, contrato1, contrato2]
        );
      } else if (contrato1 == 8020 && contrato2 == 8019) {
        return await this.conn.query(
          `
        SELECT 
        CONS.Agrupador,
		    COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @2
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO in (@3, @2) --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
				        order by cons.ORDEN DESC`,
          [fechaInicio, fechaFin, contrato1, contrato2]
        );
      } else {
        return await this.conn.query(
          `
        SELECT 
        CONS.Agrupador,
		    COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP2 G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @2
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO in (@2) --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
				        order by cons.ORDEN DESC`,
          [fechaInicio, fechaFin, contrato1]
        );
      }
    } else if (this.auth.context === GcmContexts.AGUACHICA) {
      if (contrato1 == 8003 && contrato2 == 8004) {
        return await this.conn.query(
          `SELECT 
        CONS.Agrupador,
		    COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = '8004'
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO IN('8003', '8004') --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
				        order by cons.ORDEN DESC`,
          [fechaInicio, fechaFin]
        );
      } else {
        return await this.conn.query(
          `SELECT 
        CONS.Agrupador,
		    COUNT(*) PACIENTES
        FROM ADNINGRESO RIGHT JOIN 
        (SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
           ADNINGRESO.AINCONSEC
                FROM SLNFACTUR
                 INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
                 INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                 INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
                 INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
                 LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
                 LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
                 LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
                 LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
                 LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
                 AND G.CONTRATO = @2
                WHERE 
                SLNFACTUR.SFATIPDOC = 17
                AND SLNFACTUR.SFADOCANU = N'0' 
                AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
                AND GENDETCON.GDECODIGO IN(@2) --Contrato
                AND SLNORDSER.SOSESTADO = 1
                GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
                ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
                LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
                WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
                GROUP BY CONS.Agrupador, CONS.ORDEN
				        order by cons.ORDEN DESC`,
          [fechaInicio, fechaFin, contrato1]
        );
      }
    }
  }

  async consumidoNuevaEpsNuevo(
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    return await this.conn.query(
      `Select
      GENDETCON.GDECODIGO As NContrato,
      GENDETCON.GDENOMBRE As Contrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
      ISNULL(G.LIMITE, 0) TotalFacturado,
      COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
      ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
      ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
      ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8013', '8018')
      AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE`,
      [fechaInicio, fechaFin, centro1, centro2]
    );
  }

  async consumidoNuevaEpsAntiguo(
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    return await this.conn.query(
      `Select
      GENDETCON.GDECODIGO As NContrato,
      GENDETCON.GDENOMBRE As Contrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
      ISNULL(G.LIMITE, 0) TotalFacturado,
      COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
      ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
      ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
      ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8001')
      AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE`,
      [fechaInicio, fechaFin, centro1, centro2]
    );
  }

  async consumidoAsmetNuevo(
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    return await this.conn.query(
      `Select
      GENDETCON.GDECODIGO As NContrato,
      GENDETCON.GDENOMBRE As Contrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
      ISNULL(G.LIMITE, 0) TotalFacturado,
      COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
      ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
      ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
      ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8021')
      AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  UNION
    Select
      '8019 - 8020' As NContrato,
      'PGP ASMET SALUD EPS SAS' As Contrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
      ISNULL(G.LIMITE, 0) TotalFacturado,
      COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
      ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
      ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
      ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8020'
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8019', '8020')
      AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
    GROUP BY G.LIMITE;`,
      [fechaInicio, fechaFin, centro1, centro2]
    );
  }

  async consumidoAsmetAntiguo(
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    return await this.conn.query(
      `Select
      GENDETCON.GDECODIGO As NContrato,
      GENDETCON.GDENOMBRE As Contrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
      ISNULL(G.LIMITE, 0) TotalFacturado,
      COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
      ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
      ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
      ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8010')
      AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  UNION
  Select
  '8005 - 8006' As NContrato,
  'PGP ASMET SALUD SUBS - CONTR' As Contrato,
  SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
  SUM(SLNFACTUR.SFAVALREC) ValorAnticipo,
  ISNULL(G.LIMITE, 0) TotalFacturado,
  COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
  ISNULL((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)), 0) ErrorAbsoluto,
  ISNULL(((G.LIMITE - SUM(SLNFACTUR.SFAVALCAR)) / G.LIMITE)*100, 0) ErrorRelativo,
  ISNULL(ROUND(((SUM(SLNFACTUR.SFAVALCAR) / G.LIMITE)*100), 2),0) Porcentaje
From SLNFACTUR SLNFACTUR
  Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
  Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
  LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
  LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
  LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8006'
Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
  AND  SLNFACTUR.SFADOCANU = N'0'
  and SLNFACTUR.SFATIPDOC = 17
  AND GENDETCON.GDECODIGO IN('8005', '8006')
  AND ADNINGRESO.ADNCENATE BETWEEN @2 AND @3
GROUP BY G.LIMITE;`,
      [fechaInicio, fechaFin, centro1, centro2]
    );
  }

  async consolidadoConsumido(
    fechaInicio: string,
    fechaFin: string,
    centro1: number,
    centro2: number
  ) {
    const reglaAsmet = new Date('2022-10-01');
    const reglaNuevaEps = new Date('2022-09-01');
    const fechaInicioDate = new Date(fechaInicio);
    if (fechaInicioDate >= reglaAsmet) {
      const asmetNuevo = await this.consumidoAsmetNuevo(fechaInicio, fechaFin, centro1, centro2);
      const nuevaEpsNuevo = await this.consumidoNuevaEpsNuevo(
        fechaInicio,
        fechaFin,
        centro1,
        centro2
      );
      return [...asmetNuevo, ...nuevaEpsNuevo];
    } else if (fechaInicioDate >= reglaNuevaEps) {
      const asmetAntiguo = await this.consumidoAsmetAntiguo(
        fechaInicio,
        fechaFin,
        centro1,
        centro2
      );
      const nuevaEpsNuevo = await this.consumidoNuevaEpsNuevo(
        fechaInicio,
        fechaFin,
        centro1,
        centro2
      );
      return [...asmetAntiguo, ...nuevaEpsNuevo];
    } else {
      const asmetAntiguo = await this.consumidoAsmetAntiguo(
        fechaInicio,
        fechaFin,
        centro1,
        centro2
      );
      const nuevaEpsAntiguo = await this.consumidoNuevaEpsAntiguo(
        fechaInicio,
        fechaFin,
        centro1,
        centro2
      );
      return [...asmetAntiguo, ...nuevaEpsAntiguo];
    }
  }
}
