select * from EKSLNAGRUSERVTIP where GENSERIPS IN(select GENSERIPS.OID as GENSERIPS from GCMAGRUPGP2
inner join GENSERIPS on GENSERIPS.SIPCODIGO = GCMAGRUPGP2.COD_SERIPS
where contrato = '8018' and orden = 18)


update EKSLNAGRUSERVTIP set EKSLNAGRUPD = 26 where GENSERIPS IN(select GENSERIPS.OID as GENSERIPS from GCMAGRUPGP2
inner join GENSERIPS on GENSERIPS.SIPCODIGO = GCMAGRUPGP2.COD_SERIPS
where contrato = '8018' and orden = 21)
