IF OBJECT_ID(N'dbo.CHATSEGURIDAD', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CHATSEGURIDAD (
    OID INT IDENTITY(1,1) NOT NULL,
    CHATUSUREG INT NOT NULL,
    PINHASH VARCHAR(100) NULL,
    FECCRE DATETIME2 NOT NULL CONSTRAINT DF_CHATSEGURIDAD_FECCRE DEFAULT SYSUTCDATETIME(),
    FECACT DATETIME2 NOT NULL CONSTRAINT DF_CHATSEGURIDAD_FECACT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CHATSEGURIDAD PRIMARY KEY (OID),
    CONSTRAINT UQ_CHATSEGURIDAD_CHATUSUREG UNIQUE (CHATUSUREG),
    CONSTRAINT FK_CHATSEGURIDAD_CHATUSUREG
      FOREIGN KEY (CHATUSUREG) REFERENCES dbo.CHATUSUREG(OID) ON DELETE CASCADE
  );
END;

IF OBJECT_ID(N'dbo.CHATSEGURIDAD', N'U') IS NOT NULL
BEGIN
  ALTER TABLE dbo.CHATSEGURIDAD ALTER COLUMN PINHASH VARCHAR(100) NULL;
END;
