export * from './ambulancia-estado';
export * from './asistencia-tipo';
export * from './tipo-sexo';
export * from './tipo-remision';
export * from './estado-paciente';
export * from './grupo-sanguineo';
export * from './estado-asistencia';
export * from './motivo-cancelacion';
export * from './cups';
