export enum MotivoReprogramacionActividad {
  NO_DISPONIBILIDAD_ASISTENCIAL = 'NO_DISPONIBILIDAD_ASISTENCIAL',
  PROCESO_PROVEEDOR_EXTERNO = 'PROCESO_PROVEEDOR_EXTERNO',
  PROCESOS_ADMINISTRATIVOS = 'PROCESOS_ADMINISTRATIVOS',
}

export enum MotivoAsignacionRecursoUsuario {
  INGRESO_NUEVO = 'INGRESO_NUEVO',
  TRASLADO = 'TRASLADO',
  APOYO_TEMPORAL = 'APOYO_TEMPORAL',
  REQUERIMIENTO_OPERATIVO = 'REQUERIMIENTO_OPERATIVO',
  ROTACION_PLANEADA = 'ROTACION_PLANEADA',
}

export enum MotivoFinalizacionAsignacionRecursoUsuario {
  REASIGNACION = 'REASIGNACION',
  REMOCION_MANUAL = 'REMOCION_MANUAL',
  RECURSO_DESACTIVADO = 'RECURSO_DESACTIVADO',
  USUARIO_INACTIVO = 'USUARIO_INACTIVO',
  CAMBIO_OPERATIVO = 'CAMBIO_OPERATIVO',
  FIN_DISPONIBILIDAD = 'FIN_DISPONIBILIDAD',
}

export enum MotivoFinalizacionAsignacionActividad {
  FINALIZACION_ACTIVIDAD = 'FINALIZACION_ACTIVIDAD',
  REEMPLAZO_RECURSO = 'REEMPLAZO_RECURSO',
  REASIGNACION = 'REASIGNACION',
  INDISPONIBILIDAD = 'INDISPONIBILIDAD',
  FALLA_RECURSO = 'FALLA_RECURSO',
  SOLICITUD_SUPERVISOR = 'SOLICITUD_SUPERVISOR',
  CANCELACION_ACTIVIDAD = 'CANCELACION_ACTIVIDAD',
}

export enum MotivoAsignacionActividad {
  ASIGNACION_INICIAL = 'ASIGNACION_INICIAL',
  REEMPLAZO = 'REEMPLAZO',
  APOYO = 'APOYO',
  REASIGNACION_OPERATIVA = 'REASIGNACION_OPERATIVA',
  PRIORIDAD_ALTA = 'PRIORIDAD_ALTA',
  CONTINUIDAD_OPERATIVA = 'CONTINUIDAD_OPERATIVA',
  DISPONIBILIDAD = 'DISPONIBILIDAD',
}

export enum MotivoEjecucionExternaExcepcional {
  INDISPONIBILIDAD_TECNICO = 'INDISPONIBILIDAD_TECNICO',
  COMPLEJIDAD_TECNICA = 'COMPLEJIDAD_TECNICA',
  DECISION_ADMINISTRATIVA = 'DECISION_ADMINISTRATIVA',
  GARANTIA_FABRICANTE = 'GARANTIA_FABRICANTE',
  OTRO = 'OTRO',
}

export enum MotivoAnulacionActividad {
  BAJA_DEFINITIVA = 'BAJA_DEFINITIVA',
  BAJA_INDEFINIDA = 'BAJA_INDEFINIDA',
  CANCELACION_MANUAL = 'CANCELACION_MANUAL',
}

export enum MotivoCambioEstadoEquipo {
  DANO = 'DANO',
  MANTENIMIENTO = 'MANTENIMIENTO',
  REUBICACION = 'REUBICACION',
  SOBRANTE_INVENTARIO = 'SOBRANTE_INVENTARIO',
  DEVOLUCION_PROVEEDOR = 'DEVOLUCION_PROVEEDOR',
  CORRECCION_ADMINISTRATIVA = 'CORRECCION_ADMINISTRATIVA',
}
