export const fetchDietasByFechaQuery = () => {
  return `
  SELECT G.OID,
    G.HPNESTANC,
    H.HSUCODIGO CODIGOSUBGRUPO,
    H.HSUNOMBRE SUBGRUPO,
    H.HCACODIGO CAMA,
    H.GPANOMPAC,
    PC.GPAFECNAC,
    G.GENUSUREG,
    G.DIEGRUTIP TIPO,
    G.DIEGRUCON CONSISTENCIA,
    G.DIEESTADO ESTADO,
    G.DIEESTMOT MOTIVODEVOLUCION,
    G.DIEGRUOBS OBSERVACION,
    G.DIEESTOBS OBSERVACIONDEVOLUCION,
    G.ENAISLAMIENTO
    FROM PDYDIEEST G
    INNER JOIN GCVHOSCENPAC H ON H.HPNESTANC = G.HPNESTANC
    INNER JOIN GENPACIEN PC ON PC.OID = H.GENPACIEN
    WHERE G.ELIMINADO IS NULL AND G.PDYDIEJOR = @0 ORDER BY CAMA ASC;`;
};
