export interface Query1Res {
  HSUNOMBRE: string;
  GASCODIGO: string;
  GASNOMBRE: string;
  CAMA: string;
  INGRESO: string;
  FECHA: Date;
  IDENTIFICACION: string;
  NOMBRE_PACIENTE: string;
  EDAD: number;
  SEXO: 'M' | 'F';
  DIAS: string;
  ENTIDAD: string;
  NIVEL: string;
  BENEF: string | null;
  TIPO_INGRESO: string;
  SUBGRUCAMA: string;
  ACACODIGO: string;
  MUNICIPIO: string;
  NOMBRE_ACOMPANIANTE: string;
  TEL_ACOMPANIANTE: string;
  NOMBRE_ACUDIENTE: string;
  TEL_ACUDIENTE: string | null;
  USUARIO_CREA: string;
  CANTIDAD_CAMAS: number;
  CANTIDAD_OCUPADAS: number;
  CANTIDAD_LIBRES: number;
  CANTIDAD_CAMAS_REALES: number;
  HGRNOMBRE: string;
  CANTIDAD_CAMAS_REALES_GRUPO: number;
  TOTAL: number;
  CANTIDAD_TOTAL_CAMAS: number;
  TERNOMCOM: string;
}

export interface Query2Res {
  CAMAOID: number;
  HSUNOMBRE: string;
  GASCODIGO: string;
  GASNOMBRE: string;
  CAMA: string;
  INGRESO: number;
  FECHA: Date;
  IDENTIFICACION: string;
  NOMBRE_PACIENTE: string;
  EDAD: number;
  SEXO: 'M' | 'F';
  DIAS: number;
  ENTIDAD: string;
  NIVEL: number;
  BENEF: string;
  TIPO_INGRESO: string;
  SUBGRUCAMA: string;
  ACACODIGO: string;
  MUNICIPIO: string;
  NOMBRE_ACOMPANIANTE: string;
  TEL_ACOMPANIANTE: string;
  NOMBRE_ACUDIENTE: string;
  TEL_ACUDIENTE: string;
  USUARIO_CREA: string;
  CANTIDAD_CAMAS: number;
  CANTIDAD_OCUPADAS: number;
  CANTIDAD_LIBRES: number;
  CANTIDAD_CAMAS_REALES: number;
  HGRNOMBRE: string;
  CANTIDAD_CAMAS_REALES_GRUPO: number;
  CANTIDAD_OCUPADAS_REALES_GRUPO: number;
  CANTIDAD_OCUPADAS_TOTAL: number;
  CANTIDAD_TOTAL_CAMAS: number;
}

export const query = (centroId: number) => {
  return `SELECT
  B.OID CAMAOID,
  H.HSUNOMBRE,
  I.GASCODIGO,
  I.GASNOMBRE,
  B.HCACODIGO CAMA,
  C.AINCONSEC INGRESO,
  C.AINFECING FECHA,
  D.PACNUMDOC IDENTIFICACION,
  D.GPANOMCOM NOMBRE_PACIENTE,
  DATEDIFF(YEAR, D.GPAFECNAC, GETDATE()) EDAD,
  CASE WHEN D.GPASEXPAC = 1 THEN 'M' WHEN D .GPASEXPAC = 2 THEN 'F' END AS SEXO,
  DATEDIFF(DAY, C.AINFECING, GETDATE()) DIAS,
  E.GDENOMBRE ENTIDAD,
  F.GETNOMEST NIVEL,
  CASE WHEN D .GPATIPAFI = 2 THEN 'SI' END AS BENEF,
  Case c.AINURGCON When '3' THEN 'Remitido' ELSE ' ' End TIPO_INGRESO,
  H.HSUCODIGO AS SUBGRUCAMA,
  ADNCENATE.ACACODIGO,
  GENMUNICI.MUNNOMMUN MUNICIPIO,
  C.AINOMACOMPA NOMBRE_ACOMPANIANTE,
  C.AITELACOMPA TEL_ACOMPANIANTE,
  C.AINACUDIE NOMBRE_ACUDIENTE,
  C.AINTELACU TEL_ACUDIENTE,
  GENUSUARIO.USUDESCRI USUARIO_CREA,
  CACCCANTCAMSER.CANTIDAD_CAMAS,
  CACCCANTCAMSER.CANTIDAD_OCUPADAS,
  CACCCANTCAMSER.CANTIDAD_LIBRES,
  CACCCANTCAMSER.CANTIDAD_CAMAS_REALES,
  HPNGRUPOS.HGRNOMBRE,
  (SELECT COUNT(HCANOMBRE) Expr1 FROM dbo.HPNDEFCAM WHERE (HPNDEFCAM.HPNGRUPOS = dbo.HPNGRUPOS.OID) AND (HCAESTADO <> '6') AND (HPNTIPOCA IN (1,2,3,4))) AS CANTIDAD_CAMAS_REALES_GRUPO,
  (SELECT COUNT(HCANOMBRE) Expr1 FROM dbo.HPNDEFCAM WHERE (HPNDEFCAM.HPNGRUPOS = dbo.HPNGRUPOS.OID) AND (HCAESTADO = '2') ) AS CANTIDAD_OCUPADAS_REALES_GRUPO,
	(SELECT COUNT(HCANOMBRE) Expr1 FROM dbo.HPNDEFCAM WHERE (HCAESTADO = '2') ${
    centroId ? `and ADNCENATE=${centroId}` : ''
  }) AS TOTAL,
	(SELECT COUNT(HCANOMBRE) Expr1 FROM dbo.HPNDEFCAM WHERE (HCAESTADO <> '6') ${
    centroId ? `and ADNCENATE=${centroId}` : ''
  } AND (HPNTIPOCA IN (1,2,3,4))) AS CANTIDAD_TOTAL_CAMAS,
	gentercer.TERNOMCOM FROM HPNESTANC AS A INNER JOIN
  HPNDEFCAM B ON A.HPNDEFCAM = B.OID INNER JOIN
  ADNINGRESO C ON A.ADNINGRES = C.OID INNER JOIN
  GENPACIEN D ON C.GENPACIEN = D.OID INNER JOIN
  GENESTRATO F ON D.GENESTRATO = F.OID LEFT OUTER JOIN
  GENDIAGNO G ON C.DGNDIAGNO = G.OID INNER JOIN
  GENDETCON E ON C.GENDETCON = E.OID INNER JOIN
  HPNSUBGRU H ON B.HPNSUBGRU = H.OID INNER JOIN
  GENARESER I ON H.GENARESER = I.OID INNER JOIN
  ADNCENATE ON ADNCENATE.OID = B.ADNCENATE INNER JOIN
  GENMUNICI ON GENMUNICI.OID = D.DGNMUNICIPIO INNER JOIN
  GENUSUARIO ON GENUSUARIO.OID = C.GEENUSUARIO INNER JOIN
  CACCCANTCAMSER ON H.HSUCODIGO = CACCCANTCAMSER.HSUCODIGO
	INNER JOIN HPNGRUPOS ON HPNGRUPOS.OID=B.HPNGRUPOS
	INNER JOIN GENCONTRA on GENCONTRA.oid =e.GENCONTRA1
	INNER JOIN GENTERCER on GENTERCER.oid=GENCONTRA.GENTERCER1
  WHERE (B.HCAESTADO < 3)
  ${centroId ? `AND ADNCENATE.OID = ${centroId}` : ''}
  AND LTRIM(RTRIM(UPPER(HPNGRUPOS.HGRNOMBRE))) <> 'HOSPICASA'
  AND (A.HESFECSAL IS NULL) ORDER BY CAMA`;
};
