export const getAll = `SELECT 
G.OID,
G.GENUSUARIO OIDGENUSUARIO,
U.USUDESCRI GENUSUARIO,
G.FECHA,
G.GENTERCER OIDGENTERCER,
T.TERNOMCOM GENTERCER,
G.TELEFTERC,
G.RESPTERC,
G.MOTLLAMAD,
G.OBSERVACION,
G.FECHCONCI,
G.TIPCONCI
FROM GCMGESCART G
INNER JOIN GENUSUARIO U  ON U.OID = G.GENUSUARIO
INNER JOIN GENTERCER T ON T.OID = G.GENTERCER
ORDER BY G.FECHA DESC`;

export const getAllByUser = `SELECT 
G.OID,
G.GENUSUARIO OIDGENUSUARIO,
U.USUDESCRI GENUSUARIO,
G.FECHA,
G.GENTERCER OIDGENTERCER,
T.TERNOMCOM GENTERCER,
G.TELEFTERC,
G.RESPTERC,
G.MOTLLAMAD,
G.OBSERVACION,
G.FECHCONCI,
G.TIPCONCI
FROM GCMGESCART G
INNER JOIN GENUSUARIO U  ON U.OID = G.GENUSUARIO
INNER JOIN GENTERCER T ON T.OID = G.GENTERCER
WHERE G.GENUSUARIO = @0
ORDER BY G.FECHA DESC`;
