export const fetchPacientesByContratoQuery = (codigosContratos: string[], idCentro: number) => {
  let contratos = '';

  codigosContratos.map((codigo, i) => {
    if (!i) contratos = `'${codigo}'`;
    else contratos = `${contratos}, '${codigo}'`;
  });

  const filterByCentro = idCentro ? `AND ADNINGRESO.ADNCENATE IN(${idCentro})` : '';

  return `
      SELECT 
      'ACOSTADO' estado,
        ADNINGRESO.AINCONSEC ingreso,
        GENPACIEN.PACNUMDOC documentoPaciente,
        GENPACIEN.GPANOMCOM nombrePaciente,
        ADNINGRESO.AINFECING fechaIngreso,
         DateDiff(DAY, ADNINGRESO.AINFECING, GetDate()) diasEstancia,
        CASE ADNINGRESO.AINURGCON
          WHEN -1 THEN 'NINGUNO'
          WHEN 0 THEN 'URGENCIAS'
          WHEN 1 THEN 'CONSULTA EXTERNA'
          WHEN 2 THEN 'NACIDO EN LA IPS'
          WHEN 3 THEN 'REMITIDO'
          WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
          WHEN 5 THEN 'HOSPITALIZACION'
          WHEN 6 THEN 'IMAGENES'
          WHEN 7 THEN 'LABORATORIO'
          WHEN 8 THEN 'URGENCIA GINECOLOGIA'
          WHEN 9 THEN 'QUIROFANO'
          WHEN 10 THEN 'CIRUGIA AMBULATORIA'
          WHEN 11 THEN 'CIRUGIA PROGRAMADA'
          WHEN 12 THEN 'UCI NEONATAL'
          WHEN 13 THEN 'UCI ADULTO'
          END tipoIngreso,
         HPNDEFCAM.HCACODIGO CodigoCama,
        HPNDEFCAM.HCANOMBRE nombreCama,
        SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) totalEjecutado
        FROM HPNESTANC
          INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
          INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
          INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
          INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
          LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        WHERE GENDETCON.GDECODIGO  IN (${contratos})
          AND SLNORDSER.SOSESTADO <> 2
          AND ADNINGRESO.AINESTADO = 0
          AND HPNDEFCAM.HCAESTADO = 2
          AND ADNINGRESO.ADNCENATE IS NOT NULL ${filterByCentro}
          AND HPNESTANC.HESFECSAL IS NULL
        GROUP BY 
          ADNINGRESO.AINCONSEC, 
          ADNINGRESO.AINURGCON,
          GENPACIEN.PACNUMDOC,
          GENPACIEN.GPANOMCOM,
          HPNDEFCAM.HCACODIGO,
          HPNDEFCAM.HCANOMBRE,
          ADNINGRESO.AINFECING
  UNION
  SELECT  
    'FACTURADO' estado,
     ADNINGRESO.AINCONSEC ingreso,
     GENPACIEN.PACNUMDOC documentoPaciente,
     GENPACIEN.GPANOMCOM nombrePaciente,
     ADNINGRESO.AINFECING fechaIngreso,
      DateDiff(DAY, ADNINGRESO.AINFECING, GetDate()) diasEstancia,
      CASE ADNINGRESO.AINURGCON
          WHEN -1 THEN 'NINGUNO'
          WHEN 0 THEN 'URGENCIAS'
          WHEN 1 THEN 'CONSULTA EXTERNA'
          WHEN 2 THEN 'NACIDO EN LA IPS'
          WHEN 3 THEN 'REMITIDO'
          WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
          WHEN 5 THEN 'HOSPITALIZACION'
          WHEN 6 THEN 'IMAGENES'
          WHEN 7 THEN 'LABORATORIO'
          WHEN 8 THEN 'URGENCIA GINECOLOGIA'
          WHEN 9 THEN 'QUIROFANO'
          WHEN 10 THEN 'CIRUGIA AMBULATORIA'
          WHEN 11 THEN 'CIRUGIA PROGRAMADA'
          WHEN 12 THEN 'UCI NEONATAL'
          WHEN 13 THEN 'UCI ADULTO'
          END AS tipoIngreso,
      'EGRESÓ' codigoCama,
      'EGRESÓ' nombreCama,
      SLNFACTUR.SFAVALCAR totalEjecutado
      --SLNFACTUR.SFAVALREC
          FROM SLNFACTUR
           INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
           INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
           INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
           INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
           LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
           LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
           LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
           LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
          WHERE 
          SLNFACTUR.SFATIPDOC = 17
          AND SLNFACTUR.SFADOCANU = 0 
          AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
          AND GENDETCON.GDECODIGO IN (${contratos})
          AND SLNORDSER.SOSESTADO = 1
          AND ADNINGRESO.ADNCENATE IS NOT NULL ${filterByCentro}
          GROUP BY ADNINGRESO.AINCONSEC,
               GENPACIEN.PACNUMDOC,
               GENPACIEN.GPANOMCOM,
               ADNINGRESO.AINFECING,
               ADNINGRESO.AINURGCON,
                 SLNFACTUR.SFAVALCAR
          ORDER BY totalEjecutado DESC;`;
};
