export const fetchAgrupadoresByContratoQuery = (codigosContratos: string[], idCentro: number) => {
  //const filterByCentro = idCentro ? `AND ADNINGRESO.ADNCENATE IN(${idCentro})` : '';

  let contratos = '';

  codigosContratos.map((codigo, i) => {
    if (!i) contratos = `'${codigo}'`;
    else contratos = `${contratos}, '${codigo}'`;
  });

  return `
      SELECT 
	F.GDECODIGO codigoContrato,
    CONS.Agrupador agrupador,
    SUM(CONS.TotalCargado) totalCargado,
    CONS.TotalFacturado totalContratado,
    CONS.TotalFacturado-SUM(CONS.TotalCargado) errorAbsoluto,
	ROUND(((CONS.TotalFacturado-SUM(CONS.TotalCargado))/NULLIF(CONS.TotalFacturado, 0))*100, 2) errorRelativo,
    isnull(ROUND(SUM(NULLIF(CONS.TotalCargado, 0)/NULLIF(CONS.TotalFacturado, 0))*100, 2), 0) porcentajeEjecutado
    FROM GCMFICHCON F RIGHT JOIN(
    SELECT 
    F.ORDEN,
    F.AGRUPADOR Agrupador,
    ISNULL(CONS.TotalCargado, 0) TotalCargado,
    F.TOTALFACTURADO TotalFacturado
    FROM GCMFICHCON F LEFT JOIN
    (SELECT  
       ISNULL(G.ORDEN, 0) ORDEN,
       ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
       SUM(SLNSERPRO.SERVALPRO * SLNSERPRO.SERCANTID) TotalCargado
            FROM HPNESTANC
            INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
            INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = HPNESTANC.ADNINGRES
            INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
            LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
            LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
            LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
            LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
            LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
            WHERE 
               ADNINGRESO.AINESTADO = 0 
              AND SLNORDSER.SOSESTADO <> 2
              AND HPNDEFCAM.HCAESTADO = 2
              AND HPNESTANC.HESFECSAL IS NULL
              AND GENDETCON.GDECODIGO IN (${contratos})
            GROUP BY 
            G.AGRUPADOR, G.ORDEN
            )AS CONS ON F.AGRUPADOR = CONS.AGRUPADOR
            WHERE F.GDECODIGO IN (${contratos})
            union
            SELECT 
            F.ORDEN,
    F.AGRUPADOR Agrupador,
    ISNULL(SUM(CONS.SFAVALCAR),0) TotalCargado,
    F.TOTALFACTURADO TotalFacturado
     FROM ADNINGRESO RIGHT JOIN 
    (SELECT  
    TOP 1 WITH TIES
    ISNULL(G.ORDEN, 0) ORDEN,
       ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
       ADNINGRESO.AINCONSEC,
        SLNFACTUR.SFAVALCAR,
        SLNFACTUR.SFAVALREC
            FROM SLNFACTUR
             INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
             INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
             INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
             LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
             LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
             LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
             LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
             LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS		   
            WHERE 
            SLNFACTUR.SFATIPDOC = 17
            AND SLNFACTUR.SFADOCANU = 0
            AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
            AND GENDETCON.GDECODIGO IN (${contratos})
            AND SLNORDSER.SOSESTADO = 1
            GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
            ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
            RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
            WHERE F.GDECODIGO IN (${contratos})
            GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS) AS CONS ON CONS.Agrupador = F.AGRUPADOR
            WHERE F.GDECODIGO IN (${contratos})
            GROUP BY F.GDECODIGO, CONS.Agrupador, CONS.ORDEN, CONS.TotalFacturado
            ORDER BY CONS.ORDEN DESC`;
};
