import { DEFAULT_TYPE, CtmType } from '@common/domain/types';

export type AfnClaseSerTecCode =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 31
  | 32
  | 33
  | 34
  | 35
  | 36
  | 37
  | 38
  | 39
  | 40
  | 41
  | 42
  | 43
  | 44
  | 45
  | 46;

export class AfnClaseSerTecType extends CtmType<AfnClaseSerTecCode> {}

const MTO_PLOMERIA = new AfnClaseSerTecType(1, 'PLOMERIA');
const MTO_MAMPOSERIA = new AfnClaseSerTecType(2, 'MAMPOSERÍA');
const MTO_ELECTRICO = new AfnClaseSerTecType(3, 'ELÉCTRICO');
const MTO_REFRIGERACION = new AfnClaseSerTecType(4, 'REFRIGERACIÓN');
const MTO_INFRASTRUCTURA = new AfnClaseSerTecType(5, 'INFRASTRUCTURA');
const MTO_RESTAURACION = new AfnClaseSerTecType(6, 'RESTAURACIÓN');

const TIC_SOPORTE_TECNICO = new AfnClaseSerTecType(21, 'SOPORTE TECNICO');
const TIC_DESARROLLO = new AfnClaseSerTecType(22, 'DESARROLLO');
const TIC_SEGURIDAD = new AfnClaseSerTecType(23, 'SEGURIDAD');
const TIC_BIG_DATA = new AfnClaseSerTecType(24, 'BIG DATA');
const TIC_INFRASTRUCTURA = new AfnClaseSerTecType(25, 'INFRASTRUCTURA');
const TIC_APLICACIONES = new AfnClaseSerTecType(26, 'APLICACIONES');
const TIC_PLATAFORMAS_WEB = new AfnClaseSerTecType(27, 'PLATAFORMAS WEB');
const TIC_GESTION_TIC = new AfnClaseSerTecType(28, 'GESTION TIC');
const TIC_DIRECCION_TIC = new AfnClaseSerTecType(29, 'DIRECCIÓN TIC');

const CLD_CREA_AJUSTE_DOCUME = new AfnClaseSerTecType(30, 'CREACIÓN O AJUSTE DE DOCUMENTOS');
const CLD_CREA_AJUSTE_INDICADORES = new AfnClaseSerTecType(31, 'CREACIÓN O AJUSTE DE INDICADORES');
const CLD_ELIMINA_DOCUMENTO = new AfnClaseSerTecType(32, 'ELIMINACIÓN DE DOCUMENTOS');
const CLD_ELIMINA_INDICADOR = new AfnClaseSerTecType(33, 'ELIMINACIÓN DE INDICADORES');
const CLD_ASISTENCIA_TECNICA = new AfnClaseSerTecType(34, 'ASISTENCIA TÉCNICA');
const CLD_CAPACITACIONES_SOCIALIZACIONES = new AfnClaseSerTecType(
  35,
  'CAPACITACIONES / SOCIALIZACIONES'
);
const CLD_CREA_AJUSTE_USUARIOS_ALMERA = new AfnClaseSerTecType(
  36,
  'CREACIÓN O AJUSTE DE USUARIOS EN ALMERA'
);
const CLD_CREA_AJUSTE_MECANISMOS_INTEGRACION = new AfnClaseSerTecType(
  37,
  'CREACIÓN O AJUSTE DE MECANISMOS DE INTEGRACIÓN (COMITÉS, ACTAS, REUNIONES)'
);
const CLD_DESACT_MECANI_INT = new AfnClaseSerTecType(
  38,
  'DESACTIVACIÓN DE MECANISMOS DE INTEGRACIÓN'
);
const CLD_CREA_AJUSTE_ENCUENTAS_ALMERA = new AfnClaseSerTecType(
  39,
  'CREACIÓN O AJUSTE DE ENCUESTAS (LISTAS DE CHEQUEO) EN ALMERA'
);
const CLD_INACTIVACION_ENCUESTAS = new AfnClaseSerTecType(40, 'INACTIVACIÓN DE ENCUESTAS');
const CLD_PQR_PROCESO_CALIDAD = new AfnClaseSerTecType(41, 'PQR PARA EL PROCESO DE CALIDAD');
const CLD_SUGERENCIAS_FELICITACIONES = new AfnClaseSerTecType(42, 'SUGERENCIAS Y FELICITACIONES');

const CLD_SOLICITUD_DOCUMENTO_EDITABLE = new AfnClaseSerTecType(
  43,
  'SOLICITUD DE DOCUMENTO EDITABLE'
);
const CLD_SOLICITUD_ESTUDIOS_METODOS_TIEMPOS = new AfnClaseSerTecType(
  44,
  'SOLICITUD DE ESTUDIOS DE MÉTODOS Y TIEMPOS PARA PROCESOS'
);
const CLD_SOLICITUD_AUDITORIA_INTERNA = new AfnClaseSerTecType(
  45,
  'SOLICITUD DE AUDITORÍA INTERNA A PROCESO / PROGRAMA'
);
const CLD_SOLICITUD_INFORMACION_ESPECIFICA = new AfnClaseSerTecType(
  46,
  'SOLICITUD DE INFORMACIÓN ESPECÍFICA (DILIGENCIAR UN FORMATO EXTERNO, ENVIAR UN DOCUMENTO ESPECÍFICO)'
);

export function afnClaseSerTecTypeFactory(
  code: AfnClaseSerTecCode,
  thowErr = true
): AfnClaseSerTecType {
  switch (code) {
    case 1:
      return MTO_PLOMERIA;
    case 2:
      return MTO_MAMPOSERIA;
    case 3:
      return MTO_ELECTRICO;
    case 4:
      return MTO_REFRIGERACION;
    case 5:
      return MTO_INFRASTRUCTURA;
    case 6:
      return MTO_RESTAURACION;
    case 21:
      return TIC_SOPORTE_TECNICO;
    case 22:
      return TIC_DESARROLLO;
    case 23:
      return TIC_SEGURIDAD;
    case 24:
      return TIC_BIG_DATA;
    case 25:
      return TIC_INFRASTRUCTURA;
    case 26:
      return TIC_APLICACIONES;
    case 27:
      return TIC_PLATAFORMAS_WEB;
    case 28:
      return TIC_GESTION_TIC;
    case 29:
      return TIC_DIRECCION_TIC;
    case 30:
      return CLD_CREA_AJUSTE_DOCUME;
    case 31:
      return CLD_CREA_AJUSTE_INDICADORES;
    case 32:
      return CLD_ELIMINA_DOCUMENTO;
    case 33:
      return CLD_ELIMINA_INDICADOR;
    case 34:
      return CLD_ASISTENCIA_TECNICA;
    case 35:
      return CLD_CAPACITACIONES_SOCIALIZACIONES;
    case 36:
      return CLD_CREA_AJUSTE_USUARIOS_ALMERA;
    case 37:
      return CLD_CREA_AJUSTE_MECANISMOS_INTEGRACION;
    case 38:
      return CLD_DESACT_MECANI_INT;
    case 39:
      return CLD_CREA_AJUSTE_ENCUENTAS_ALMERA;
    case 40:
      return CLD_INACTIVACION_ENCUESTAS;
    case 41:
      return CLD_PQR_PROCESO_CALIDAD;
    case 42:
      return CLD_SUGERENCIAS_FELICITACIONES;
    case 43:
      return CLD_SOLICITUD_DOCUMENTO_EDITABLE;
    case 44:
      return CLD_SOLICITUD_ESTUDIOS_METODOS_TIEMPOS;
    case 45:
      return CLD_SOLICITUD_AUDITORIA_INTERNA;
    case 46:
      return CLD_SOLICITUD_INFORMACION_ESPECIFICA;
    default: {
      if ([null, undefined].indexOf(code) >= 0) return null;
      else if (thowErr) throw new Error('No existe clase de servicio tecnico con este codigo');
      else return DEFAULT_TYPE;
    }
  }
}

export const AFN_MTO_CASE_SER_TEC = {
  PLOMERIA: MTO_PLOMERIA,
  MAMPOSERIA: MTO_MAMPOSERIA,
  ELECTRICO: MTO_ELECTRICO,
  REFRIGERACION: MTO_REFRIGERACION,
  INFRASTRUCTURA: MTO_INFRASTRUCTURA,
  RESTAURACION: MTO_RESTAURACION,
};

export const AFN_MTO_CASE_SER_TEC_VALUES = [
  MTO_PLOMERIA,
  MTO_MAMPOSERIA,
  MTO_ELECTRICO,
  MTO_REFRIGERACION,
  MTO_INFRASTRUCTURA,
  MTO_RESTAURACION,
];

export const AFN_TIC_CASE_SER_TEC = {
  SOPORTE_TECNICO: TIC_SOPORTE_TECNICO,
  DESARROLLO: TIC_DESARROLLO,
  SEGURIDAD: TIC_SEGURIDAD,
  BIG_DATA: TIC_BIG_DATA,
  INFRASTRUCTURA: TIC_INFRASTRUCTURA,
  APLICACIONES: TIC_APLICACIONES,
  PLATAFORMAS_WEB: TIC_PLATAFORMAS_WEB,
  GESTION_TIC: TIC_GESTION_TIC,
  DIRECCION_TIC: TIC_DIRECCION_TIC,
};

export const AFN_TIC_CASE_SER_TEC_VALUES = [
  TIC_SOPORTE_TECNICO,
  TIC_DESARROLLO,
  TIC_SEGURIDAD,
  TIC_BIG_DATA,
  TIC_INFRASTRUCTURA,
  TIC_APLICACIONES,
  TIC_PLATAFORMAS_WEB,
  TIC_GESTION_TIC,
  TIC_DIRECCION_TIC,
];

export const AFN_CLD_CASE_SER_TEC = {
  ASISTENCIA_TECNIC: CLD_ASISTENCIA_TECNICA,
  CAPACITACIONES: CLD_CAPACITACIONES_SOCIALIZACIONES,
  CREA_ACTUA_DOCUME: CLD_CREA_AJUSTE_DOCUME,
  CREA_INDICADORES: CLD_CREA_AJUSTE_INDICADORES,
  CREA_AJUS_ENCUT_ALMERA: CLD_CREA_AJUSTE_ENCUENTAS_ALMERA,
  CREA_MECANI_INTEG: CLD_CREA_AJUSTE_MECANISMOS_INTEGRACION,
  CREA_ASIGNA_USUA: CLD_CREA_AJUSTE_USUARIOS_ALMERA,
  ELIMINA_DOCUMENTO: CLD_ELIMINA_DOCUMENTO,
  ELIMINA_INDICADOR: CLD_ELIMINA_INDICADOR,
  INICTI_ENCUT: CLD_INACTIVACION_ENCUESTAS,
  DESACT_MECANI_INT: CLD_DESACT_MECANI_INT,
  PQR_PROC_CALID: CLD_PQR_PROCESO_CALIDAD,
  SUGERENCIAS_FELICITACIONES: CLD_SUGERENCIAS_FELICITACIONES,
  SOLT_DOCUT_EDIT: CLD_SOLICITUD_DOCUMENTO_EDITABLE,
  SOLT_ESTU_METODOS_PROCESOS: CLD_SOLICITUD_ESTUDIOS_METODOS_TIEMPOS,
  SOLT_AUDIT_INTER_PROGRAMA: CLD_SOLICITUD_AUDITORIA_INTERNA,
  SOLT_INFO_ESPECIF: CLD_SOLICITUD_INFORMACION_ESPECIFICA,
};

export const AFN_CLD_CASE_SER_TEC_VALUES = [
  CLD_ASISTENCIA_TECNICA,
  CLD_CAPACITACIONES_SOCIALIZACIONES,
  CLD_CREA_AJUSTE_DOCUME,
  CLD_CREA_AJUSTE_INDICADORES,
  CLD_CREA_AJUSTE_ENCUENTAS_ALMERA,
  CLD_CREA_AJUSTE_MECANISMOS_INTEGRACION,
  CLD_CREA_AJUSTE_USUARIOS_ALMERA,
  CLD_ELIMINA_DOCUMENTO,
  CLD_ELIMINA_INDICADOR,
  CLD_INACTIVACION_ENCUESTAS,
  CLD_DESACT_MECANI_INT,
  CLD_PQR_PROCESO_CALIDAD,
  CLD_SUGERENCIAS_FELICITACIONES,
  CLD_SOLICITUD_DOCUMENTO_EDITABLE,
  CLD_SOLICITUD_ESTUDIOS_METODOS_TIEMPOS,
  CLD_SOLICITUD_AUDITORIA_INTERNA,
  CLD_SOLICITUD_INFORMACION_ESPECIFICA,
];
