// export const fetchEstancias = async (consecutivo: number) => {};

export const fetchCamasDisponiblesQuery = () => {
  return `
    SELECT
    C.OID,
    C.ADNCENATE,
    CA.ACANOMBRE,
    C.HPNTIPOCA,
  -- C.HCAAISLAMIEN,
  -- C.HCABLOPOR,
  --C.HCAOBSHOS,
  C.HCACODIGO,C.HCAESTADO,C.HCANOMBRE,C.HCANUMHABI,
  C.HPNGRUPOS,G.HGRCODIGO, G.HGRNOMBRE,
  C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE, C.HCABLOPOR
  FROM HPNDEFCAM C
  INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
  INNER JOIN ADNCENATE CA ON C.ADNCENATE = CA.OID
  INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
  WHERE C.HCAESTADO IN(1,2,3,4,5,6) ORDER BY C.ADNINGRESO DESC`;
};
export const fetchCamasQuery = () => {
  //   return `
  //   SELECT
  //     C.OID,
  //     C.ADNCENATE,
  //     CA.ACANOMBRE,
  //     C.HCANOMBRE,
  //     AD.AINCONSEC,
  //     PR.ACTIVO AS ACTIVOPREALTA,
  //     AD.AINFECING,
  //     GP.OID AS OID_PACIENTE,
  //     GP.GPANOMCOM,
  //     GP.PACNUMDOC,
  //     GP.GPASEXPAC,
  //     GP.GPAFECNAC,
  //     (SELECT TOP 1 D.DIANOMBRE
  //       FROM HCNFOLIO F
  //       INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
  //       INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
  //       WHERE F.ADNINGRESO = AD.OID
  //     ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
  //     C.HPNTIPOCA,
  //     GDT.GDENOMBRE,
  //     T.HTINOMBRE AS TIPO_CAMA,
  //     C.HCACODIGO,
  //     C.HCAESTADO,
  //     CASE GP.GPASEXPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXPAC,
  //     CASE C.HCAESTADO WHEN 0 THEN 'NINGUNO' WHEN 1 THEN 'DESOCUPADA' WHEN 2 THEN 'OCUPADA' WHEN 3 THEN 'BLOQUEADA' WHEN 4 THEN 'DESBLOQUEADA' WHEN 5 THEN 'ALISTAMIENTO' WHEN 6 THEN 'INACTIVA' END AS ESTADOCAMA,
  //     C.HCANOMBRE,
  //     C.HCANUMHABI,
  //     C.HPNGRUPOS, G.HGRCODIGO, G.HGRNOMBRE,
  //     C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE, C.HCABLOPOR,

  //     -- ✅ ESTA ES LA NUEVA COLUMNA CON TODAS LAS EVOLUCIONES EN FORMATO JSON
  //     EV.EVOLUCIONES

  // FROM HPNDEFCAM C
  //     LEFT JOIN EKHPNPREALTA PR ON PR.HPNDEFCAM = C.OID AND PR.ACTIVO = 1
  //     LEFT JOIN ADNINGRESO AD ON C.ADNINGRESO = AD.OID
  //     LEFT JOIN GENPACIEN GP ON AD.GENPACIEN = GP.OID
  //     LEFT JOIN GENDETCON GDT ON AD.GENDETCON = GDT.OID

  //     -- Usamos OUTER APPLY para ejecutar una subconsulta por cada cama y agregar sus evoluciones
  //     OUTER APPLY (
  //         SELECT
  //             ( -- Inicio de la subconsulta que genera el JSON
  //                 SELECT
  //                     HF.HCFECFOL AS FECHA_FOLIO,
  //                     HE.HCCM09N12 AS SEGUIMIENTO,
  //                     GE_TRATANTE.GEEDESCRI AS ESPECIALIDAD_TRATANTE,
  //                     GA.GASNOMBRE AS AREASERVICIO,
  //                     GE.GEEDESCRI AS ESPECIALIDAD,
  //                     GM.GMECODIGO AS CEDULA_MEDICO,
  //                     GM.GMENOMCOM AS MEDICO,
  //                     HF.OID AS OIDFOLIO
  //                 FROM HCNFOLIO HF
  //                     INNER JOIN HCMEVOHOS HE ON HF.OID = HE.HCNFOLIO
  //                     INNER JOIN GENARESER GA ON HF.GENARESER = GA.OID
  //                     INNER JOIN GENMEDICO GM ON HF.GENMEDICO = GM.OID
  //                     INNER JOIN GENESPECI GE ON HF.GENESPECI = GE.OID
  //                     INNER JOIN GENESPECI AS GE_TRATANTE ON HE.HCCM22N06 = GE_TRATANTE.OID
  //                 WHERE
  //                     HF.ADNINGRESO = AD.OID -- Cruza con el ingreso del paciente de la consulta principal
  //                 ORDER BY
  //                     HF.HCFECFOL DESC -- Ordena las evoluciones de la más nueva a la más antigua
  //                 FOR JSON PATH -- La magia: convierte el resultado en un array JSON
  //             ) AS EVOLUCIONES
  //     ) EV

  //     INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
  //     INNER JOIN ADNCENATE CA ON C.ADNCENATE = CA.OID
  //     INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
  //     INNER JOIN HPNTIPOCA T ON T.OID = C.HPNTIPOCA

  // -- Filtramos por el/los contextos que necesitas.
  // WHERE C.ADNCENATE IN (1,2) -- Aquí tu aplicación debe pasar el array de contextos.

  // ORDER BY C.ADNCENATE, G.HGRCODIGO, C.HPNSUBGRU, C.HCACODIGO;`;
  return `
SELECT
  C.OID,
  C.ADNCENATE,
  CA.ACANOMBRE,  
  C.HCANOMBRE,
  AD.AINCONSEC,
  PR.ACTIVO AS ACTIVOPREALTA,
  AD.AINFECING,
  GP.OID AS OID_PACIENTE,
  GP.GPANOMCOM,
  GP.PACNUMDOC,
  GP.GPASEXPAC,
  GP.GPAFECNAC, 
C.HPNTIPOCA,
GDT.GDENOMBRE,
T.HTINOMBRE AS TIPO_CAMA,
C.HCACODIGO,C.HCAESTADO,
CASE GP.GPASEXPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXPAC,
CASE C.HCAESTADO WHEN 0 THEN 'NINGUNO' WHEN 1 THEN 'DESOCUPADA' WHEN 2 THEN 'OCUPADA' WHEN 3 THEN 'BLOQUEADA' WHEN 4 THEN 'DESBLOQUEADA' WHEN 5 THEN 'ALISTAMIENTO' WHEN 6 THEN 'INACTIVA' END AS ESTADOCAMA,
C.HCANOMBRE,
C.HCANUMHABI,
C.HPNGRUPOS,G.HGRCODIGO, G.HGRNOMBRE,
DIAGNOSTICO.DIAGNOSTICO,
C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE, C.HCABLOPOR
FROM HPNDEFCAM C
LEFT JOIN EKHPNPREALTA PR ON PR.HPNDEFCAM = C.OID AND PR.ACTIVO = 1
    LEFT JOIN ADNINGRESO AD ON C.ADNINGRESO = AD.OID
    LEFT JOIN GENPACIEN GP ON AD.GENPACIEN = GP.OID
    LEFT JOIN GENDETCON GDT ON AD.GENDETCON = GDT.OID    
    OUTER APPLY (
        SELECT TOP 1
            D.DIANOMBRE AS DIAGNOSTICO
        FROM HCNFOLIO F
        INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
        INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
        WHERE F.ADNINGRESO = AD.OID        
        ORDER BY F.HCFECFOL DESC, F.HCNUMFOL DESC
    ) AS DIAGNOSTICO

    INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
    INNER JOIN ADNCENATE CA ON C.ADNCENATE = CA.OID
    INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
    INNER JOIN HPNTIPOCA T ON T.OID = C.HPNTIPOCA
ORDER BY C.ADNCENATE, G.HGRCODIGO, C.HPNSUBGRU, C.HCACODIGO;
  `;
  //   return `
  //    SELECT
  //   C.OID,
  //   C.ADNCENATE,
  //   CA.ACANOMBRE,
  //   C.HCANOMBRE,
  //   AD.AINCONSEC,
  //   AD.AINFECING,
  //   GP.GPANOMCOM,
  //   GP.PACNUMDOC,
  //   GP.GPASEXPAC,
  //   GP.GPAFECNAC,
  //   C.HPNTIPOCA,
  //   GDT.GDENOMBRE,
  //   T.HTINOMBRE AS TIPO_CAMA,
  // C.HCACODIGO,C.HCAESTADO,
  // CASE GP.GPASEXPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXPAC,
  // CASE C.HCAESTADO WHEN 0 THEN 'NINGUNO' WHEN 1 THEN 'DESOCUPADA' WHEN 2 THEN 'OCUPADA' WHEN 3 THEN 'BLOQUEADA' WHEN 4 THEN 'DESBLOQUEADA' WHEN 5 THEN 'ALISTAMIENTO' WHEN 6 THEN 'INACTIVA' END AS ESTADOCAMA,
  // C.HCANOMBRE,
  // C.HCANUMHABI,
  // C.HPNGRUPOS,G.HGRCODIGO, G.HGRNOMBRE,
  // C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE, C.HCABLOPOR
  // FROM HPNDEFCAM C
  // LEFT JOIN ADNINGRESO AD ON C.ADNINGRESO = AD.OID
  // LEFT JOIN GENPACIEN GP ON AD.GENPACIEN = GP.OID
  // LEFT JOIN GENDETCON GDT ON AD.GENDETCON = GDT.OID
  // INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
  // INNER JOIN ADNCENATE CA ON C.ADNCENATE = CA.OID
  // INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
  // INNER JOIN HPNTIPOCA T ON T.OID = C.HPNTIPOCA
  // ORDER BY C.ADNCENATE,G.HGRCODIGO,C.HPNSUBGRU, C.HCACODIGO`;
};

export const fetchPacientes = (ids: number[]) => {
  return `Select 2 AS ORIGEN, HCNREFERSOL.OID, HCNREFERSOL.HCCONSEC As CONSECUTIVO,
  ISNULL(HCNREFERSOL.HCPRINOMPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGNOMPAC,'') + ' ' +
  ISNULL(HCNREFERSOL.HCPRIAPEPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGAPEPAC,'') As PACIENTE,
  (SELECT TOP 1 D.DIANOMBRE
   FROM HCNFOLIO F
   INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
   INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
   WHERE F.ADNINGRESO = (SELECT TOP(1) ADNINGRESO.OID 
                         FROM ADNINGRESO 
                         INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                         WHERE GENPACIEN.PACNUMDOC = HCNREFERSOL.HCNUMDOCPAC
                         ORDER BY AINFECING DESC)
   ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
  HCNREFENT.HCNOMBRE As ENTI_REFERENCIA,
  GENMUNICI1.MUNNOMMUN As MUNICIPIO,
  HCNREFMOTREM.HCNOMBRE As MOT_REMI,
  HCNREFTRAM.HCAMPMOT MOT_REMI2
  From HCNREFERSOL
    Inner Join HCNREFTRAM On HCNREFTRAM.OID = HCNREFERSOL.HCNREFTRAM And
      HCNREFERSOL.OID = HCNREFTRAM.HCNREFERSOL
    Left Join HCNREFTRAMDS On HCNREFTRAMDS.OID = HCNREFTRAM.HCNREFTRAMDS1
    Inner Join HCNREFMOTREM On HCNREFMOTREM.OID = HCNREFTRAM.HCNREFMOTREM
    Inner Join HCNREFENT On HCNREFENT.OID = HCNREFERSOL.HCNREFENT
    Inner Join GENMUNICI On GENMUNICI.OID = HCNREFERSOL.GENMUNICI1
    Inner Join GENDETCON On GENDETCON.OID = HCNREFERSOL.GENDETCON
    Inner Join GENESPECI On GENESPECI.OID = HCNREFTRAM.GENESPECI
    Inner Join GENMUNICI GENMUNICI1 On GENMUNICI1.OID = HCNREFERSOL.GENMUNICI2
    Left Join GENUSUARIO On GENUSUARIO.OID = HCNREFTRAMDS.GENUSUARIO
    WHERE HCNREFERSOL.OID IN(${ids})
  order by 1 desc`;
};

export const fetchPacientesHospitalizados = (ids: number[]) => {
  // return `select
  // 1 as ORIGEN,
  // ADNINGRESO OID,
  // AINCONSEC CONSECUTIVO,
  // GPANOMPAC PACIENTE,
  // GPADOCPAC CEDULA,
  // GDENOMBRE ENTI_REFERENCIA,
  // GPAMUNPAC MUNICIPIO,
  // AINFECING,
  //     CASE AINURGCON
  //     WHEN -1 THEN 'NINGUNO'
  //     WHEN 0 THEN 'URGENCIAS'
  //     WHEN 1 THEN 'CONSULTA EXTERNA'
  //     WHEN 2 THEN 'NACIDO EN LA IPS'
  //     WHEN 3 THEN 'REMITIDO'
  //     WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
  //     WHEN 5 THEN 'HOSPITALIZACION'
  //     WHEN 6 THEN 'IMAGENES'
  //     WHEN 7 THEN 'LABORATORIO'
  //     WHEN 8 THEN 'URGENCIA GINECOLOGIA'
  //     WHEN 9 THEN 'QUIROFANO'
  //     WHEN 10 THEN 'CIRUGIA AMBULATORIA'
  //     WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //     WHEN 12 THEN 'UCI NEONATAL'
  //     WHEN 13 THEN 'UCI ADULTO'
  //     END AS MOT_REMI,
  //     CASE AINCAUING
  //     WHEN 0 THEN 'NINGUNA'
  //     WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
  //     WHEN 2 THEN 'HERIDOS EN COMBATE'
  //     WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
  //     WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
  //     WHEN 5 THEN 'ODONTOLOGIA'
  //     WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
  //     WHEN 7 THEN 'CATASTROFE DE FISALUD'
  //     WHEN 8 THEN 'QUEMADOS'
  //     WHEN 9 THEN 'MATERNIDAD'
  //     WHEN 10 THEN 'ACCIDENTE LABORAL'
  //     WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //     END AS MOT_REMI2 FROM GCVHOSCENPAC WHERE ADNINGRESO IN(${ids})`;
  return `
  select
		1 as ORIGEN,
    I.OID OID,
    I.AINCONSEC CONSECUTIVO,
    P.GPANOMCOM PACIENTE,
    P.PACNUMDOC CEDULA,
   GDENOMBRE ENTI_REFERENCIA,
   (SELECT TOP 1 D.DIANOMBRE
    FROM HCNFOLIO F
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    WHERE F.ADNINGRESO = I.OID
    ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
    M.MUNNOMMUN MUNICIPIO,
    I.AINFECING,
	CASE I.AINURGCON
        WHEN -1 THEN 'NINGUNO'
        WHEN 0 THEN 'URGENCIAS'
        WHEN 1 THEN 'CONSULTA EXTERNA'
        WHEN 2 THEN 'NACIDO EN LA IPS'
        WHEN 3 THEN 'REMITIDO'
        WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
        WHEN 5 THEN 'HOSPITALIZACION'
        WHEN 6 THEN 'IMAGENES'
        WHEN 7 THEN 'LABORATORIO'
        WHEN 8 THEN 'URGENCIA GINECOLOGIA'
        WHEN 9 THEN 'QUIROFANO'
        WHEN 10 THEN 'CIRUGIA AMBULATORIA'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        WHEN 12 THEN 'UCI NEONATAL'
        WHEN 13 THEN 'UCI ADULTO'
        END AS MOT_REMI,
        CASE AINCAUING
        WHEN 0 THEN 'NINGUNA'
        WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
        WHEN 2 THEN 'HERIDOS EN COMBATE'
        WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
        WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
        WHEN 5 THEN 'ODONTOLOGIA'
        WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
        WHEN 7 THEN 'CATASTROFE DE FISALUD'
        WHEN 8 THEN 'QUEMADOS'
        WHEN 9 THEN 'MATERNIDAD'
        WHEN 10 THEN 'ACCIDENTE LABORAL'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        END AS MOT_REMI2
        FROM     GENPACIEN P
		LEFT JOIN ADNINGRESO I ON I.GENPACIEN = P.OID
		LEFT JOIN GENDETCON G ON G.OID = I.GENDETCON
		LEFT JOIN GENMUNICI M ON M.OID = P.DGNMUNICIPIO
    WHERE I.OID IN(${ids})`;
};
export const fetchCamasOcupadasQuery = (codigo: string) => {
  return `SELECT 
C.HCACODIGO, 
C.HCANOMBRE, 
P.GPANOMCOM, 
P.PACNUMDOC, 
I.AINCONSEC, 
I.AINFECING, 
DCT.GDENOMBRE 
FROM HPNDEFCAM C 
INNER JOIN ADNINGRESO I ON C.ADNINGRESO = I.OID 
INNER JOIN GENPACIEN P ON I.GENPACIEN = P.OID
INNER JOIN GENDETCON DCT ON I.GENDETCON = DCT.OID
WHERE C.HCACODIGO = '${codigo}'`;
};

export const getExamenesQuery = (consecutivo: number) => {
  return ` 
  SELECT 
    AI.AINCONSEC AS CONSECUTIVO,
    OS.SOSORDSER AS ORDENSERVICIO,
    OS.SOSFECCON AS FECHACONFIRMACION,
    --CA.ACANOMBRE AS CentroNombre,
    --GP.PACNUMDOC AS PacienteCodigo,
    --GP.GPANOMCOM AS NombrePaciente,
    SP.SERFECSER AS FECHASERVICIO,
    SI.SIPCODCUP AS SERVICIOCODIGO,
    SI.SIPNOMBRE AS SERVICIONOMBRE,
    SG.GSUNOMBRE AS SUBGRUPONOMBRE,
    SG.GSUCODIGO AS SUBGRUPOCODIGO,
    DC.GDENOMBRE AS PLANNOMBRE,
    EX.HCNRESEXA AS RESULTADOSEXAMENES,
    SP.SERCANTID AS CANTIDAD,
    CASE OS.SOSESTADO
        WHEN 0 THEN 'REGISTRADO'
        WHEN 1 THEN 'CONFIRMADO'
        WHEN 2 THEN 'ANULADO'
    END AS ESTADO_ORDEN_SERVICIO,

	 CASE AI.AINURGCON
        WHEN 0 THEN 'URGENCIA'
        WHEN 1 THEN 'CONSULTA EXTERNA'
        WHEN 2 THEN 'NACIDO HOSPITAL'
        WHEN 3 THEN 'REMITIDO'
        WHEN 4 THEN 'HOSPITALIZACIÓN URGENCIA'
        WHEN 5 THEN 'HOSPITALIZACION'
        WHEN 6 THEN 'IMAGENES'
        WHEN 7 THEN 'LABORATORIO'
        WHEN 8 THEN 'URGENCIA GINECOLOGICA'
        WHEN 9 THEN 'QUIROFANO'
        WHEN 10 THEN 'CIRUGÍA AMBULATORIA'
        WHEN 11 THEN 'CIRUGÍA PROGRAMADA'
    END AS INGRESO_POR,

    CASE AI.AINTIPING 
        WHEN 0 THEN 'NINGUNO' 
        WHEN 1 THEN 'AMBULATORIO' 
        WHEN 2 THEN 'HOSPITALARIO'  
    END AS CLASE_INGRESO,
    SP.SERAPLPRO AS APLICADO_A_PX
FROM SLNSERPRO AS SP
INNER JOIN ADNINGRESO AS AI ON AI.OID = SP.ADNINGRES1
INNER JOIN GENPACIEN AS GP ON GP.OID = AI.GENPACIEN
INNER JOIN GENDETCON AS DC ON DC.OID = SP.GENDETCON1
INNER JOIN SLNSERHOJ AS SH ON SH.OID = SP.OID
LEFT JOIN  HCNSOLEXA AS EX ON EX.SLNSERHOJ = SH.OID
INNER JOIN GENSERIPS AS SI ON SH.GENSERIPS1 = SI.OID
INNER JOIN GENSUBGRU AS SG ON SG.OID = SI.GENSUBGRU1
INNER JOIN ADNCENATE AS CA ON CA.OID = AI.ADNCENATE
INNER JOIN SLNORDSER AS OS ON OS.OID = SP.SLNORDSER1
WHERE 
    AI.AINCONSEC = ${consecutivo}
    AND OS.SOSESTADO IN (0,1,2)
    AND SG.GSUCODIGO IN ('0707','0501','502','0702', '0503', '0504', '0505')
ORDER BY SP.SERFECSER DESC`;
};
export const getInterconsultasQuery = (documento: number) => {
  return `SELECT 
    ADNINGRESO.AINCONSEC AS NUM_INGRESO,
    GENPACIEN.OID AS OID_PACIENTE,
    GENPACIEN.PACNUMDOC AS PACIENTE,
    GENPACIEN.GPANOMCOM AS NOMBRE_PACIENTE,
    HCNFOLIO.HCFECFOL AS FECHA_FOLIO,
    GENESPECI_1.GEEDESCRI AS ESPECIALIDAD_TRATANTE,
    HCMEVOHOS.HCCM09N12 AS SEGUIMIENTO,
    GENARESER.GASNOMBRE AS AREA_SERVICIO,
    GENESPECI.GEEDESCRI AS ESPECIALIDAD,
    GENMEDICO.GMECODIGO AS CEDULA_MEDICO,
    GENMEDICO.GMENOMCOM AS MEDICO,
    HPNDEFCAM.HCACODIGO,
    ADNCENATE.ACANOMBRE,
    HPNSUBGRU.OID AS OID_SUBGRUPO,
    HPNSUBGRU.HSUNOMBRE,
    HPNSUBGRU.HSUCODIGO,
    HPNGRUPOS.OID AS OID_GRUPO,
    HPNGRUPOS.HGRCODIGO,
    HPNGRUPOS.HGRNOMBRE,
    HCNFOLIO.OID AS OID_FOLIO
FROM HCNFOLIO
INNER JOIN ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
INNER JOIN HCMEVOHOS ON HCNFOLIO.OID = HCMEVOHOS.HCNFOLIO
INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID
INNER JOIN GENARESER ON HCNFOLIO.GENARESER = GENARESER.OID
INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO = GENMEDICO.OID
INNER JOIN GENESPECI ON HCNFOLIO.GENESPECI = GENESPECI.OID
INNER JOIN GENESPECI AS GENESPECI_1 ON HCMEVOHOS.HCCM22N06 = GENESPECI_1.OID
INNER JOIN HPNDEFCAM ON ADNINGRESO.HPNDEFCAM = HPNDEFCAM.OID
INNER JOIN ADNCENATE ON ADNINGRESO.ADNCENATE = ADNCENATE.OID
INNER JOIN HPNSUBGRU ON HPNDEFCAM.HPNSUBGRU = HPNSUBGRU.OID
INNER JOIN HPNGRUPOS ON HPNDEFCAM.HPNGRUPOS = HPNGRUPOS.OID
WHERE GENPACIEN.PACNUMDOC = ${documento}
`;
};

export const getMedicamentosQuery = (consecutivo: number) => {
  return `SELECT 'SUMINISTRO' AS TIPO,AINCONSEC AS INGRESO,INNDOCUME.IDFECDOC AS FEC_SOLICITUD,
DATEDIFF(HOUR,INNDOCUME.IDFECDOC,GETDATE()) as HORAS,
INNDOCUME.IDCONSEC AS SUMINISTRO, INNPRODUC.IPRCODIGO AS PRODUCTO, INNPRODUC.IPRDESCOR AS NOMBRE_PRODUCTO, INNMSUMPA.IDDCANTID AS SOLICITADO, INNMSUMPA.ISMCANDEV AS DEVUELTA,INNMSUMPA.ISMCANAPL AS APLICADA,INNMSUMPA.IDDCANTID - INNMSUMPA.ISMCANDEV - INNMSUMPA.ISMCANAPL as PENDIENTE,INNALMACE.IALNOMBRE AS ALMACEN_SOLICITADO, GENARESER.GASNOMBRE AS AREA_SOLICITO,INNMSUMPA.oid as od_INNMSUMPA,CASE adningreso.ADNCENATE WHEN 1 THEN 'CENTRO' WHEN 2 THEN 'ALTA' END AS SEDE,HPNDEFCAM.HCACODIGO AS CAMA,HPNSUBGRU.HSUNOMBRE AS SERVICIO,GENPACIEN.PACNUMDOC AS IDENTIFICACION, GENPACIEN.GPANOMCOM AS PACIENTE
FROM INNMSUMPA 
LEFT OUTER JOIN INNCSUMPA ON INNMSUMPA.INNCSUMPA = INNCSUMPA.OID 
LEFT OUTER JOIN INNDOCUME ON INNCSUMPA.OID = INNDOCUME.OID 
LEFT OUTER JOIN INNPRODUC ON INNMSUMPA.INNPRODUC = INNPRODUC.OID
inner join adningreso on adningreso.OID= INNCSUMPA.ADNINGRESO
INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
INNER JOIN INNALMACE ON INNALMACE.OID = INNCSUMPA.INNALMACE
left JOIN GENARESER ON GENARESER.OID = INNCSUMPA.GENARESER
left join HPNDEFCAM on adningreso.HPNDEFCAM = HPNDEFCAM.oid
left join  HPNSUBGRU on HPNDEFCAM.HPNSUBGRU = HPNSUBGRU.oid
WHERE adningreso.AINESTADO='0' and ainfecing>'2020-12-31'
AND ADNINGRESO.AINCONSEC = ${consecutivo}
AND (INNDOCUME.IDESTADO = 1) 
AND (INNMSUMPA.IDDCANTID - INNMSUMPA.ISMCANDEV - INNMSUMPA.ISMCANAPL > 0) 
AND (NOT (INNMSUMPA.HCNSOLMEDD IS NULL))
union

SELECT 'MEDICAMENTO',AINCONSEC AS INGRESO,INNDOCUME.IDFECDOC AS FEC_SOLICITUD, 
DATEDIFF(HOUR,INNDOCUME.IDFECDOC,GETDATE()) as HORAS,
INNDOCUME.IDCONSEC AS SUMINISTRO, INNPRODUC.IPRCODIGO AS PRODUCTO, INNPRODUC.IPRDESCOR AS NOMBRE_PRODUCTO, INNMSUMPA.IDDCANTID AS SOLICITADO, INNMSUMPA.ISMCANDEV AS DEVUELTA,INNMSUMPA.ISMCANAPL AS APLICADA,INNMSUMPA.IDDCANTID - INNMSUMPA.ISMCANDEV - INNMSUMPA.ISMCANAPL as PENDIENTE,INNALMACE.IALNOMBRE AS ALMACEN_SOLICITADO, GENARESER.GASNOMBRE AS AREA_SOLICITO,INNMSUMPA.oid as od_INNMSUMPA,CASE adningreso.ADNCENATE WHEN 1 THEN 'CENTRO' WHEN 2 THEN 'ALTA' END AS SEDE,HPNDEFCAM.HCACODIGO AS CAMA,HPNSUBGRU.HSUNOMBRE AS SERVICIO,GENPACIEN.PACNUMDOC AS IDENTIFICACION, GENPACIEN.GPANOMCOM AS PACIENTE
FROM INNMSUMPA 
LEFT OUTER JOIN INNCSUMPA ON INNMSUMPA.INNCSUMPA = INNCSUMPA.OID 
LEFT OUTER JOIN INNDOCUME ON INNCSUMPA.OID = INNDOCUME.OID 
LEFT OUTER JOIN INNPRODUC ON INNMSUMPA.INNPRODUC = INNPRODUC.OID
inner join adningreso on adningreso.OID= INNCSUMPA.ADNINGRESO
INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
INNER JOIN INNALMACE ON INNALMACE.OID = INNCSUMPA.INNALMACE
left JOIN GENARESER ON GENARESER.OID = INNCSUMPA.GENARESER
left join HPNDEFCAM on adningreso.HPNDEFCAM = HPNDEFCAM.oid
left join  HPNSUBGRU on HPNDEFCAM.HPNSUBGRU = HPNSUBGRU.oid
left join HCNMEDPAC on hcnmedpac.OID = INNMSUMPA.HCNMEDPAC
WHERE  adningreso.AINESTADO='0' and ainfecing>'2020-12-31' 
AND ADNINGRESO.AINCONSEC = ${consecutivo}
AND (INNDOCUME.IDESTADO = 1) 
AND (INNMSUMPA.IDDCANTID - INNMSUMPA.ISMCANDEV - INNMSUMPA.ISMCANAPL > 0)
AND (NOT (INNMSUMPA.HCNMEDPAC IS NULL)) 
order by 3`;
};

export const getProcedimientosQuery = (consecutivo: number) => {
  return `SELECT 
SI.SIPCODIGO,
SI.SIPNOMBRE, 
'QUIRURGICO' AS TIPO,
PX.HCSOBSERV, 
PX.HCSFECSOL AS FECHAPROCEDIMIENTO,
CASE PX.HCSESTADO
WHEN 0 THEN  'URGENTE'
WHEN 1 THEN 'RUTINARIO'
WHEN 2 THEN 'ELECTIVA'
WHEN 3 THEN 'PRIORITARIA'
END AS ESTADO,
F.GENMEDICO, 
M.GMENOMCOM 
FROM HCNSOLPQX PX
INNER JOIN HCNFOLIO F ON PX.HCNFOLIO = F.OID
INNER JOIN GENMEDICO M ON F.GENMEDICO = M.OID
INNER JOIN GENSERIPS  SI ON PX.GENSERIPS = SI.OID
INNER JOIN ADNINGRESO I ON PX.ADNINGRESO = I.OID
WHERE I.AINCONSEC = ${consecutivo}
UNION

SELECT 
SI.SIPCODIGO,
SI.SIPNOMBRE, 
'NO QUIRURGICO' AS TIPO,
PX.HCSOBSERV,
PX.HCSFECSOL AS FECHAPROCEDIMIENTO,
CASE PX.HCSESTADO
WHEN 0 THEN  'URGENTE'
WHEN 1 THEN 'RUTINARIO'
WHEN 2 THEN 'ELECTIVA'
WHEN 3 THEN 'PRIORITARIA'
END AS ESTADO, 
F.GENMEDICO, 
M.GMENOMCOM 
FROM HCNSOLPNQX PX
INNER JOIN HCNFOLIO F ON PX.HCNFOLIO = F.OID
INNER JOIN GENMEDICO M ON F.GENMEDICO = M.OID
INNER JOIN GENSERIPS  SI ON PX.GENSERIPS = SI.OID
INNER JOIN ADNINGRESO I ON PX.ADNINGRESO = I.OID
WHERE I.AINCONSEC = ${consecutivo}`;
};

export const getEvolucionesByPaciente = (consecutivo: number) => {
  return `
  SELECT
HF.HCFECFOL AS FECHA_FOLIO,
HE.HCCM09N12 AS SEGUIMIENTO,
GE_TRATANTE.GEEDESCRI AS ESPECIALIDAD_TRATANTE,
GA.GASNOMBRE AS AREA_SERVICIO,
GE.GEEDESCRI AS ESPECIALIDAD,
GM.GMECODIGO AS CEDULA_MEDICO,
GM.GMENOMCOM AS MEDICO,
S.HSUNOMBRE,
CA.HCACODIGO,
S.HSUCODIGO,
HF.OID AS OID_FOLIO
FROM HCNFOLIO HF
INNER JOIN HCMEVOHOS HE ON HF.OID = HE.HCNFOLIO
INNER JOIN GENARESER GA ON HF.GENARESER = GA.OID
INNER JOIN GENMEDICO GM ON HF.GENMEDICO = GM.OID
INNER JOIN GENESPECI GE ON HF.GENESPECI = GE.OID
INNER JOIN GENESPECI AS GE_TRATANTE ON HE.HCCM22N06 = GE_TRATANTE.OID
INNER JOIN ADNINGRESO AD ON HF.ADNINGRESO = AD.OID
INNER JOIN HPNDEFCAM CA ON HF.HPNDEFCAM = CA.OID
INNER JOIN HPNSUBGRU S ON CA.HPNSUBGRU = S.OID
WHERE AD.AINCONSEC = ${consecutivo}
ORDER BY HF.HCFECFOL DESC
  `;
};

export const getListaEsperaQuery2 = () => {
  return `
  SELECT ADNCENATE.ACANOMBRE,--HCNORDHOSP.OID,
  AINCONSEC AS INGRESO, 
  AINFECING AS FECHA_INGRESO,DATEDIFF(HOUR,AINFECING,GETDATE()) AS HORAS_DESDE_INGRESO,
  GENPACIEN.GPANOMCOM AS NOMBREPACIENTE,
  GENPACIEN.PACNUMDOC AS PACIENTEDOCU,
  DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, GETDATE()) AS EDAD,
  CASE GENPACIEN.GPASEXPAC WHEN 1 THEN 'M' WHEN 2 THEN 'F' END AS SEXO,
  GENDETCON.GDENOMBRE AS EPS,
  (SELECT TOP 1 D.DIANOMBRE
    FROM HCNFOLIO F
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    WHERE F.ADNINGRESO = ADNINGRESO.OID
    ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
  HPNDEFCAM.HCACODIGO AS CAMA,
  HPNSUBGRU.HSUNOMBRE,
  CASE ADNINGRESO.AINURGCON 
    WHEN '0' THEN 'Urgencias' 
    WHEN '1' THEN 'Consulta_Externa' 
    WHEN '2' THEN 'Nacido_Hospital' 
    WHEN '3' THEN 'Remitido'   
    WHEN '4' THEN 'Hosp_Urgencias' 
    WHEN '5' THEN 'Hospitalizacion' 
    WHEN '6' THEN 'Imagenes'     
    WHEN '7' THEN 'Laboratorio' 
    WHEN '8' THEN 'Urgencia_Ginecologica' 
    WHEN '9' THEN 'Quirofano'     
    WHEN '10' THEN 'Cirugia_Ambulatoria' 
    WHEN '11' THEN 'Cirugia_Programada' 
    WHEN '12' THEN 'Uci_Neonatal'     
    WHEN '13' THEN 'Uci_Adulto' 
  END TIPO_INGRESO,
  ADNINGRESO.AINURGCON AS TIPO_INGRESO_CODE,
  CASE AINESTADO 
    WHEN 0 THEN 'REGISTRADO' 
    WHEN 1 THEN 'FACTURADO' 
    WHEN 2 THEN 'ANULADO' 
    WHEN 3 THEN 'BLOQUEADO' 
    WHEN 4 THEN 'CIERRE ADMINISTRATIVO' 
  END AS ESTADO_INGRESO,
  AINESTADO AS ESTADO_INGRESO_CODE,
 -- HCOCONSEC AS ORDEN_HOSP_PENDIENTE,
  --CASE HCOTIPHOSP     WHEN 1 THEN 'Hospitalizacion'      WHEN 2 THEN 'Urgencias_Observacion'     WHEN 3 THEN 'Traslado'     WHEN 4 THEN 'Hospitalizacion_Recien_Nacido'   END AS TIPO_ORDEN_HOSP,
  --HCOTIPHOSP AS TIPO_ORDEN_HOSP_CODE,
  --HCOFECDOC AS FECHA_HOSP_PENDIENTE ,
  (select top(1) HCOCONSEC  from HCNORDHOSP as orden where orden.ADNINGRESO = ADNINGRESO.OID ORDER BY orden.OID aSC) as ORDEN_HOSP_PENDIENTE,
  (select top(1) HCOTIPHOSP  from HCNORDHOSP as orden where orden.ADNINGRESO = ADNINGRESO.OID ORDER BY orden.OID aSC   ) as primer_tipo_orden_hosp,
  (select top(1) HCOFECDOC  from HCNORDHOSP as orden where orden.ADNINGRESO = ADNINGRESO.OID ORDER BY orden.OID aSC   ) as primer_orden_hosp,
  (select TOP(1) HCCM09N79 as REQUIERE_TRASLADO from HCMEVOURG AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_URG_SI,
(select TOP(1) HCCM10N80 as REQUIERE_TRASLADO from HCMEVOURG AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_URG_DESTINO,
(select TOP(1) HCCM09N68 as REQUIERE_TRASLADO from HCMEVOHOS AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_HOSP_SI,
(select TOP(1) HCCM09N133 as REQUIERE_TRASLADO from HCMEVOUCI AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_UCI_SI

FROM adningreso
  left JOIN HCNORDHOSP ON ADNINGRESO.OID=HCNORDHOSP.ADNINGRESO
  INNER JOIN GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
  INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  LEFT JOIN HPNDEFCAM ON HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
  LEFT JOIN ADNCENATE ON ADNCENATE.OID =ADNINGRESO.ADNCENATE
  LEFT JOIN HPNSUBGRU ON HPNSUBGRU.OID=HPNDEFCAM.HPNSUBGRU
  WHERE 1=1 
  and HCOESTADO='0' 
  and  ADNINGRESO.AINURGCON <> '1'
  and AINESTADO = 0
  AND  DATEDIFF(DAY, AINFECING, GETDATE()) < 10
  group by acanombre,AINCONSEC,AINFECING,GENPACIEN.GPANOMCOM,GENPACIEN.PACNUMDOC,GENPACIEN.GPAFECNAC,GENPACIEN.GPASEXPAC,GENDETCON.GDENOMBRE,adningreso.OID,HPNDEFCAM.HCACODIGO,HPNSUBGRU.HSUNOMBRE,adningreso.AINURGCON,adningreso.AINESTADO
  ORDER BY 2 DESC
  `;
};
export const getListaEsperaQuery = () => {
  return `
  SELECT ADNCENATE.ACANOMBRE,--HCNORDHOSP.OID,
  AINCONSEC AS INGRESO, 
  AINFECING AS FECHA_INGRESO,DATEDIFF(HOUR,AINFECING,GETDATE()) AS HORAS_DESDE_INGRESO,
  GENPACIEN.GPANOMCOM AS NOMBREPACIENTE,
  GENPACIEN.PACNUMDOC AS PACIENTEDOCU,
  DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, GETDATE()) AS EDAD,
  CASE GENPACIEN.GPASEXPAC WHEN 1 THEN 'M' WHEN 2 THEN 'F' END AS SEXO,
  GENDETCON.GDENOMBRE AS EPS,
  (SELECT TOP 1 D.DIANOMBRE
    FROM HCNFOLIO F
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    WHERE F.ADNINGRESO = ADNINGRESO.OID
    ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
  HPNDEFCAM.HCACODIGO AS CAMA,
  HPNSUBGRU.HSUNOMBRE,
  CASE ADNINGRESO.AINURGCON 
    WHEN '0' THEN 'Urgencias' 
    WHEN '1' THEN 'Consulta_Externa' 
    WHEN '2' THEN 'Nacido_Hospital' 
    WHEN '3' THEN 'Remitido'   
    WHEN '4' THEN 'Hosp_Urgencias' 
    WHEN '5' THEN 'Hospitalizacion' 
    WHEN '6' THEN 'Imagenes'     
    WHEN '7' THEN 'Laboratorio' 
    WHEN '8' THEN 'Urgencia_Ginecologica' 
    WHEN '9' THEN 'Quirofano'     
    WHEN '10' THEN 'Cirugia_Ambulatoria' 
    WHEN '11' THEN 'Cirugia_Programada' 
    WHEN '12' THEN 'Uci_Neonatal'     
    WHEN '13' THEN 'Uci_Adulto' 
  END TIPO_INGRESO,
  ADNINGRESO.AINURGCON AS TIPO_INGRESO_CODE,
  CASE AINESTADO 
    WHEN 0 THEN 'REGISTRADO' 
    WHEN 1 THEN 'FACTURADO' 
    WHEN 2 THEN 'ANULADO' 
    WHEN 3 THEN 'BLOQUEADO' 
    WHEN 4 THEN 'CIERRE ADMINISTRATIVO' 
  END AS ESTADO_INGRESO,
  AINESTADO AS ESTADO_INGRESO_CODE,
  HCOCONSEC AS ORDEN_HOSP_PEND,
  (SELECT TOP(1) HCOCONSEC  from HCNORDHOSP AS ORDEN WHERE ORDEN.ADNINGRESO = ADNINGRESO.OID ORDER BY ORDEN.OID ASC) as ORDEN_HOSP_PENDIENTE,
  CASE HCOTIPHOSP 
    WHEN 1 THEN 'Hospitalizacion' 
    WHEN 2 THEN 'Urgencias_Observacion' 
    WHEN 3 THEN 'Traslado' 
    WHEN 4 THEN 'Hospitalizacion_Recien_Nacido' 
  END AS TIPO_ORDEN_HOSP,
  HCOTIPHOSP AS TIPO_ORDEN_HOSP_CODE,
  HCOFECDOC AS FECHA_HOSP_PENDIENTE ,
  (select top(1) HCOTIPHOSP  from HCNORDHOSP as orden where orden.ADNINGRESO = ADNINGRESO.OID ORDER BY orden.OID aSC   ) as PRIMER_TIPO_ORDEN_HOSP,
  (select top(1) HCOFECDOC  from HCNORDHOSP as orden where orden.ADNINGRESO = ADNINGRESO.OID ORDER BY orden.OID aSC   ) as PRIMER_ORDEN_HOSP,
  (select TOP(1) HCCM09N79 as REQUIERE_TRASLADO from HCMEVOURG AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_URG_SI,
(select TOP(1) HCCM10N80 as REQUIERE_TRASLADO from HCMEVOURG AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_URG_DESTINO,
(select TOP(1) HCCM09N68 as REQUIERE_TRASLADO from HCMEVOHOS AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_HOSP_SI,
(select TOP(1) HCCM09N133 as REQUIERE_TRASLADO from HCMEVOUCI AS HCB INNER JOIN HCNFOLIO AS HC ON HC.OID = HCB.HCNFOLIO WHERE HC.ADNINGRESO=ADNINGRESO.OID ORDER BY HC.OID DESC ) AS EVO_UCI_SI

FROM adningreso
  INNER JOIN HCNORDHOSP ON ADNINGRESO.OID=HCNORDHOSP.ADNINGRESO
  INNER JOIN GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
  INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  LEFT JOIN HPNDEFCAM ON HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
  LEFT JOIN ADNCENATE ON ADNCENATE.OID =ADNINGRESO.ADNCENATE
  LEFT JOIN HPNSUBGRU ON HPNSUBGRU.OID=HPNDEFCAM.HPNSUBGRU
  WHERE HCOESTADO='0' AND  DATEDIFF(DAY, AINFECING, GETDATE()) < 10
  ORDER BY 2,1,7 DESC`;
};

export const getListaEsperaReferenciaQuery = () => {
  return `
  SELECT 
  HCNREFERSOL.HCCONSEC AS CONSECUTIVO,
  HCNREFERSOL.HCFECHA AS FECHA_SOL,
  CASE WHEN HCNREFERSOL.HCESTADO = 0 THEN 'NINGUNO'
       WHEN HCNREFERSOL.HCESTADO = 1 THEN 'REGISTRADO'
       WHEN HCNREFERSOL.HCESTADO = 2 THEN 'PENDIENTE'
       WHEN HCNREFERSOL.HCESTADO = 3 THEN 'ACEPTADO'
       WHEN HCNREFERSOL.HCESTADO = 4 THEN 'SUSPENDIDO'
       WHEN HCNREFERSOL.HCESTADO = 5 THEN 'CERRADO' 
  END AS ESTADO,
  
  CASE HCNREFTRAMDS.HCPACACEP 
       WHEN 0 THEN 'NINGUNO' 
       WHEN 1 THEN 'SI' 
       WHEN 2 THEN 'NO' 
       WHEN 3 THEN 'PENDIENTE' 
  END AS PACIENTE_ACEPTADO,

  CASE WHEN HCNREFERSOL.HCPRIOR = 0 THEN 'NINGUNO'
       WHEN HCNREFERSOL.HCPRIOR = 1 THEN 'URGENTE'
       WHEN HCNREFERSOL.HCPRIOR = 2 THEN 'PRIORITARIO'
       WHEN HCNREFERSOL.HCPRIOR = 3 THEN 'REGULAR' 
  END AS PRIORIDAD,

  CASE WHEN HCNREFERSOL.HCTIPDOCPAC = 0 THEN 'NINGUNO'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 1 THEN 'CÉDULA DE CIUDADANÍA'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 2 THEN 'CEDULA DE EXTRANJERIA'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 3 THEN 'TARJETA DE IDENTIDAD'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 4 THEN 'REGISTRO CIVIL'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 5 THEN 'PASAPORTE'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 6 THEN 'ADULTO SIN IDENTIFICACION'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 7 THEN 'MENOR SIN IDENTIFICACIÓN'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 8 THEN 'NUMERO UNICO DE IDENTIFICACION'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 9 THEN 'SALVOCONDUCTO'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 10 THEN 'CERTIFICADO NACIDO VIVO'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 11 THEN 'CARNET DIPLOMATICO'
       WHEN HCNREFERSOL.HCTIPDOCPAC = 12 THEN 'PERMISO ESPECIAL DE PERMANENCIA'
  END AS TIPO_DOC_PAC,

  CASE WHEN HCNREFTRAM.HCSERREM = 0 THEN 'NINGUNO'
       WHEN HCNREFTRAM.HCSERREM = 1 THEN 'CONSULTA EXTERNA AMBULATORIA'
       WHEN HCNREFTRAM.HCSERREM = 2 THEN 'HOSPITALIZACION'
       WHEN HCNREFTRAM.HCSERREM = 3 THEN 'URGENCIAS'
       WHEN HCNREFTRAM.HCSERREM = 4 THEN 'UCI'
       WHEN HCNREFTRAM.HCSERREM = 5 THEN 'OTROS' 
  END AS SERVICIO_QUEREMITE,

  CASE WHEN HCNREFTRAM.HCSERALREM = 0 THEN 'NINGUNO'
       WHEN HCNREFTRAM.HCSERALREM = 1 THEN 'CONSULTA EXTERNA AMBULATORIA'
       WHEN HCNREFTRAM.HCSERALREM = 2 THEN 'HOSPITALIZACION'
       WHEN HCNREFTRAM.HCSERALREM = 3 THEN 'URGENCIAS'
       WHEN HCNREFTRAM.HCSERALREM = 4 THEN 'UCI'
       WHEN HCNREFTRAM.HCSERALREM = 5 THEN 'OTROS' 
  END AS SERVICIO_ALQUEREMITE,

  HCNREFERSOL.HCNUMDOCPAC AS NUM_DOCUMENTO,

   (SELECT TOP(1) AINCONSEC 
   FROM ADNINGRESO 
   INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
   WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC) 
     AND AINFECING >= HCNREFERSOL.HCFECHA
   ORDER BY AINFECING DESC) AS INGRESO,

 
  (SELECT TOP(1) AINFECING 
   FROM ADNINGRESO 
   INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
   WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC) 
     AND AINFECING >= HCNREFERSOL.HCFECHA
   ORDER BY AINFECING DESC) AS FECHA_INGRESO,

 
  (SELECT TOP(1) HPNDEFCAM.HCACODIGO 
   FROM ADNINGRESO 
   INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
   INNER JOIN HPNDEFCAM ON HPNDEFCAM.ADNINGRESO = ADNINGRESO.OID
   WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC) 
     AND AINFECING >= HCNREFERSOL.HCFECHA
     AND HPNDEFCAM.HCAOBSHOS <> 1
   ORDER BY AINFECING DESC) AS NOMBRE_CAMA,


  (SELECT TOP(1) 
    CASE AINURGCON 
      WHEN 0 THEN 'URGENCIAS' 
      WHEN 1 THEN 'CONSULTA_EXTERNA'  
      WHEN 3 THEN 'REMITIDO' 
      ELSE 'OTROS' 
    END 
   FROM ADNINGRESO 
   INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN 
   WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC)  
     AND AINFECING >= HCNREFERSOL.HCFECHA
   ORDER BY AINFECING DESC) AS INGRESO_POR,

  (SELECT TOP 1 D.DIANOMBRE
   FROM HCNFOLIO F
   INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
   INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
   WHERE F.ADNINGRESO = (SELECT TOP(1) ADNINGRESO.OID 
                         FROM ADNINGRESO 
                         INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                         WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC) 
                           AND AINFECING >= HCNREFERSOL.HCFECHA
                         ORDER BY AINFECING DESC)
   ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,

  ISNULL(HCNREFERSOL.HCPRINOMPAC, ' ') AS PRIMER_NOMBRE,
  ISNULL(HCNREFERSOL.HCSEGNOMPAC, ' ') AS SEGUNDO_NOMBRE,
  ISNULL(HCNREFERSOL.HCPRIAPEPAC, ' ') AS PRIMER_APELLIDO,
  ISNULL(HCNREFERSOL.HCSEGAPEPAC, ' ') AS SEGUNDO_APELLIDO,
  DATEDIFF(YEAR, HCNREFERSOL.HCFECNACPAC, GETDATE()) AS EDAD,

  CASE WHEN HCNREFERSOL.HCSEXPAC = 1 THEN 'M'
       WHEN HCNREFERSOL.HCSEXPAC = 2 THEN 'F' 
  END AS SEXO,

  HCNREFENT.HCNOMBRE AS ENTI_REFERENCIA,
  GENDETCON.GDENOMBRE AS EPS,
  GEENENTADM.ENTNOMBRE,
  GENMUNICI.MUNNOMMUN AS MUNICIPIO,
  GENDEPTO.DEPNOMDEP AS DEPARTAMENTO,
  HCNREFERSOL.HCNOMMED AS MEDICO,
  HCNREFERSOL.HCNREFTRAM AS TRAMITE,
  HCNREFMOTREM.HCNOMBRE AS MOT_REMI,
  HCNREFTRAM.HCAMPMOT AS MOT_REMI2,
  HCNREFTRAMDS.HCFUNCONTES AS FUNCIONA_CONTESTA,
  HCNREFTRAMDS.HCOBSERV AS OBS_SEGUIMIENTO,
  HCNREFTRAMDS.HCFECHAACEP AS FEC_ACEPTACION,
  HCNREFTRAMDS.HCOBSERVCC AS OBS_CIERRE,
  GENESPECI.GEEDESCRI AS ESPECIALIDAD,
  HCNREFTRAMDS.HCTRASPACFEC AS FECHA_TRASLADO_PAC,
  GENUSUARIO.USUNOMBRE AS CEDULA,
  GENUSUARIO.USUDESCRI AS NOMBRE

FROM HCNREFERSOL
  INNER JOIN HCNREFTRAM ON HCNREFTRAM.OID = HCNREFERSOL.HCNREFTRAM AND HCNREFERSOL.OID = HCNREFTRAM.HCNREFERSOL
  LEFT JOIN HCNREFTRAMDS ON HCNREFTRAMDS.OID = HCNREFTRAM.HCNREFTRAMDS1
  INNER JOIN HCNREFMOTREM ON HCNREFMOTREM.OID = HCNREFTRAM.HCNREFMOTREM
  INNER JOIN HCNREFENT ON HCNREFENT.OID = HCNREFERSOL.HCNREFENT
  INNER JOIN GENMUNICI ON GENMUNICI.OID = HCNREFERSOL.GENMUNICI1
  INNER JOIN GENDETCON ON GENDETCON.OID = HCNREFERSOL.GENDETCON
  LEFT JOIN GENCONTRA ON GENCONTRA.OID = GENDETCON.GENCONTRA1
  LEFT JOIN GEENENTADM ON GEENENTADM.OID = GENCONTRA.DGNENTADM1
  INNER JOIN GENESPECI ON GENESPECI.OID = HCNREFTRAM.GENESPECI
  LEFT JOIN GENUSUARIO ON GENUSUARIO.OID = HCNREFTRAMDS.GENUSUARIO
  INNER JOIN GENDEPTO ON GENDEPTO.OID = GENMUNICI.GENDEPTO

WHERE HCNREFERSOL.HCESTADO IN (1, 2, 3)
  AND  DATEDIFF(DAY, HCNREFERSOL.HCFECHA, GETDATE()) < 3
  AND (
    HCNREFERSOL.HCESTADO IN (1, 2)
    OR (
      HCNREFERSOL.HCESTADO = 3
      AND EXISTS (
        SELECT 1
        FROM ADNINGRESO 
        INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
        INNER JOIN HPNDEFCAM ON HPNDEFCAM.ADNINGRESO = ADNINGRESO.OID
        WHERE GENPACIEN.PACNUMDOC = TRIM(HCNREFERSOL.HCNUMDOCPAC)
          AND ADNINGRESO.AINFECING >= HCNREFERSOL.HCFECHA
          AND HPNDEFCAM.HCAOBSHOS <> 1
      )
    )
  );`;
};

export const listaReservaQuery = () => {
  return `
SELECT 
  GP.OID AS OID_PACIENTE,
  R.ORIGENSOLICI AS ORIGEN,
  GP.GPANOMCOM AS NOMBRE_PACIENTE,
  GP.PACNUMDOC AS DOCUMENTO_PACIENTE,
  AD.AINCONSEC AS CONSECUTIVO,
  (SELECT TOP 1 D.DIANOMBRE
   FROM HCNFOLIO F
   INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
   INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
   WHERE F.ADNINGRESO = AD.OID
 ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
  CASE GP.GPASEXPAC
      WHEN 1 THEN 'MASCULINO'
      WHEN 2 THEN 'FEMENINO'
  END AS SEXO, 
  R.CREATEDAT AS FECHA_CREACION,
  R.OBSERVACION AS OBSERVACION,
  R.CREATEDBY AS CREADO_POR_ID,
  U.USUDESCRI AS NOMBRE_CREADO_POR,
  R.ANULAOBSERVACION AS OBSERVACION_ANULACION,
  R.TIPOAISLAMIENTOS AS TIPO_AISLAMIENTO,
  R.HPNDEFCAM AS CAMA,
  C.HCACODIGO AS NOMBRE_CAMA,
  M.MUNNOMMUN AS MUNICIPIO,
  GDT.GDENOMBRE AS CONTRATO,
  CA.ACANOMBRE AS CENTRO,
  CASE AD.AINURGCON
        WHEN -1 THEN 'NINGUNO'
        WHEN 0 THEN 'URGENCIAS'
        WHEN 1 THEN 'CONSULTA EXTERNA'
        WHEN 2 THEN 'NACIDO EN LA IPS'
        WHEN 3 THEN 'REMITIDO'
        WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
        WHEN 5 THEN 'HOSPITALIZACION'
        WHEN 6 THEN 'IMAGENES'
        WHEN 7 THEN 'LABORATORIO'
        WHEN 8 THEN 'URGENCIA GINECOLOGIA'
        WHEN 9 THEN 'QUIROFANO'
        WHEN 10 THEN 'CIRUGIA AMBULATORIA'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        WHEN 12 THEN 'UCI NEONATAL'
        WHEN 13 THEN 'UCI ADULTO'
END AS MOT_REMI,
CASE AINCAUING
        WHEN 0 THEN 'NINGUNA'
        WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
        WHEN 2 THEN 'HERIDOS EN COMBATE'
        WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
        WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
        WHEN 5 THEN 'ODONTOLOGIA'
        WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
        WHEN 7 THEN 'CATASTROFE DE FISALUD'
        WHEN 8 THEN 'QUEMADOS'
        WHEN 9 THEN 'MATERNIDAD'
        WHEN 10 THEN 'ACCIDENTE LABORAL'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        END AS MOT_REMI2
FROM EKHPNRESERCAM R
INNER JOIN ADNINGRESO AD ON R.VARENTITYOID = AD.OID
INNER JOIN GENPACIEN GP ON AD.GENPACIEN = GP.OID
INNER JOIN HPNDEFCAM C ON R.HPNDEFCAM = C.OID
INNER JOIN GENUSUARIO U ON R.CREATEDBY = U.OID
INNER JOIN ADNCENATE CA ON C.ADNCENATE = CA.OID
INNER JOIN GENDETCON GDT ON AD.GENDETCON = GDT.OID
INNER JOIN GENMUNICI M ON M.OID = GP.DGNMUNICIPIO
WHERE R.ACTIVA = 1 AND DATEDIFF(DAY, R.CREATEDAT, GETDATE()) < 30
ORDER BY R.CREATEDAT DESC`;
};
