import { MODULES } from './principal';

export const INN_AUTHORITIES = {
  CODE: MODULES.INVENTARIO.CODE,
  RECEPCION_TECNICA: {
    CODE: MODULES.INVENTARIO.SUBS.RECEPCION_TECNICA,
    GENERAR_CONSULTAR_RECEPC_TECN: `${MODULES.INVENTARIO.SUBS.RECEPCION_TECNICA}001`,
  },
  DOCUMENTOS: {
    CODE: MODULES.INVENTARIO.SUBS.DOCUMENTOS,
    GENERAR_RECIBO_ORDEN_DESPACHO: `${MODULES.INVENTARIO.SUBS.DOCUMENTOS}002`,
  },
  SUMINISTROS: {
    CODE: MODULES.INVENTARIO.SUBS.SUMINISTROS,
    VER: `${MODULES.INVENTARIO.SUBS.SUMINISTROS}001`,
    RECIBIR: `${MODULES.INVENTARIO.SUBS.SUMINISTROS}002`,
  },
  CENTRAL_COMPRAS: {
    CODE: MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS,
    VER_SOLICITUDES: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}001`,
    CREAR_SOLICITUD: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}002`,
    APROBAR_RECHAZAR_SOLICITUD: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}003`,
    COTIZAR_SOLICITUD: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}004`,
    APROBAR_ITEM_COT_SOLICITUD: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}005`,
    APROBAR_RECHAZAR_COT_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}006`,
    AGREGAR_ORDEN_COMPRA_SOLICI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}007`,
    PROGRAMAR_ORDEN_COMPRA_SOLICI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}008`,
    CONTABILIZAR_ORDEN_COMPRA_SOLICI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}009`,
    PAGAR_ORDEN_COMPRA_SOLICI: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}010`,
    CONFIRMAR_OC_EN_COT: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}011`,
    REPORTAR_ITEMS_LISTOS_ENTREGA: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}012`,
    CAJA_MENOR_EXPRESS: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}013`,
    ELIMINAR_SOLICITUDES: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}014`,
    CARGO_1_APROBAR_RECHAZAR_COT_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}015`,
    CARGO_2_APROBAR_RECHAZAR_COT_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}016`,
    CARGO_3_APROBAR_RECHAZAR_COT_RECOMEN: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}017`,
    MOVER_A_OTRO_CENTRO: `${MODULES.INVENTARIO.SUBS.CENTRAL_COMPRAS}018`,
  },
  PRODUCTOS: {
    CODE: MODULES.INVENTARIO.SUBS.PRODUCTOS,
    GESTION_REPORTES: `${MODULES.INVENTARIO.SUBS.PRODUCTOS}001`,
  },
  COTIZACIONES_PREFABRICADAS: {
    CODE: MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS,
    REGISTRAR_SET: `${MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS}001`,
    ADD_PROVEEDOR_TO_SET: `${MODULES.INVENTARIO.SUBS.COTIZACIONES_PREFABRICADAS}002`,
  },
};
