/* Ejecutar en ALTACENTRO, VALLEDUPAR, SANJUAN y AGUACHICA. */
SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.EKINNSOLPEPROD', 'CANTIDADRECHAZADA') IS NULL
BEGIN
  ALTER TABLE dbo.EKINNSOLPEPROD
    ADD CANTIDADRECHAZADA DECIMAL(10, 4) NOT NULL
      CONSTRAINT DF_EKINNSOLPEPROD_CANTRECH DEFAULT (0) WITH VALUES;
END;

IF COL_LENGTH('dbo.EKINNSOLPEPROD', 'OBSERVACIONRECHAZO') IS NULL
  ALTER TABLE dbo.EKINNSOLPEPROD ADD OBSERVACIONRECHAZO VARCHAR(1000) NULL;

IF COL_LENGTH('dbo.EKINNSOLPEPROD', 'FECHARECHAZO') IS NULL
  ALTER TABLE dbo.EKINNSOLPEPROD ADD FECHARECHAZO DATETIME NULL;

IF COL_LENGTH('dbo.EKINNSOLPEPROD', 'GENUSRECHAZO') IS NULL
  ALTER TABLE dbo.EKINNSOLPEPROD ADD GENUSRECHAZO INT NULL;

COMMIT TRANSACTION;
