/* Ejecutar en ALTACENTRO, VALLEDUPAR, SANJUAN y AGUACHICA. */
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/*
 * Antes de esta migracion el codigo 4 de EKINNSOLPEPROD significaba RECHAZADO.
 * El cambio se ejecuta solo al crear CANTIDADSOBREPEDIDO, de modo que una
 * segunda ejecucion no transforme los nuevos SOBREPEDIDO (4) en RECHAZADO (5).
 */
IF COL_LENGTH('dbo.EKINNSOLPEPROD', 'CANTIDADSOBREPEDIDO') IS NULL
BEGIN
  UPDATE dbo.EKINNSOLPEPROD
  SET ESTADODESPACHO = 5
  WHERE ESTADODESPACHO = 4;

  ALTER TABLE dbo.EKINNSOLPEPROD
    ADD CANTIDADSOBREPEDIDO DECIMAL(10, 4) NOT NULL
      CONSTRAINT DF_EKINNSOLPEPROD_CANTSOBRE DEFAULT (0) WITH VALUES;
END;

IF OBJECT_ID('dbo.EKINNSOLPESOBRE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EKINNSOLPESOBRE (
    OID INT IDENTITY(1, 1) NOT NULL
      CONSTRAINT PK_EKINNSOLPESOBRE PRIMARY KEY,
    SOLICITUDANTERIORID INT NOT NULL,
    PRODUCTOANTERIORID INT NOT NULL,
    SOLICITUDNUEVAID INT NOT NULL,
    PRODUCTONUEVOID INT NULL,
    TIPOCIERRE VARCHAR(24) NOT NULL,
    CANTIDADCERRADA DECIMAL(10, 4) NOT NULL,
    OBSERVACION VARCHAR(1000) NOT NULL,
    FECHACREACION DATETIME NOT NULL,
    USUARIOID INT NOT NULL,
    CONSTRAINT CK_EKINNSOLPESOBRE_TIPO
      CHECK (TIPOCIERRE IN ('REEMPLAZADO', 'CERRADO_SIN_TRASLADO')),
    CONSTRAINT FK_EKINNSOLPESOBRE_SOLANT
      FOREIGN KEY (SOLICITUDANTERIORID) REFERENCES dbo.EKINNSOLPE(OID),
    CONSTRAINT FK_EKINNSOLPESOBRE_PRODANT
      FOREIGN KEY (PRODUCTOANTERIORID) REFERENCES dbo.EKINNSOLPEPROD(OID),
    CONSTRAINT FK_EKINNSOLPESOBRE_SOLNUEVA
      FOREIGN KEY (SOLICITUDNUEVAID) REFERENCES dbo.EKINNSOLPE(OID),
    CONSTRAINT FK_EKINNSOLPESOBRE_PRODNUEVO
      FOREIGN KEY (PRODUCTONUEVOID) REFERENCES dbo.EKINNSOLPEPROD(OID)
  );

  CREATE INDEX IX_EKINNSOLPESOBRE_ANTERIOR
    ON dbo.EKINNSOLPESOBRE (SOLICITUDANTERIORID);
  CREATE INDEX IX_EKINNSOLPESOBRE_NUEVA
    ON dbo.EKINNSOLPESOBRE (SOLICITUDNUEVAID);
  CREATE UNIQUE INDEX UX_EKINNSOLPESOBRE_PRODUCTOANTERIOR
    ON dbo.EKINNSOLPESOBRE (PRODUCTOANTERIORID);
END;

COMMIT TRANSACTION;
