import { GCM_CONTEXTS, GcmContextType } from '@common/domain/types';

export const getResumenPeriodoPorEntidadQuery = (ctx: GcmContextType, centro = 0) => {
  return `
  SELECT 
  ISNULL(SUM(SFATOTFAC),0)-ISNULL(SUM(CASE WHEN CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END), 0) facturado,

  ISNULL(SUM(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) < @0 AND SFATIPDOC != 17 THEN SFATOTFAC ELSE NULL END), 0) refacturado,

  ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) OR ADNCENATE IS NULL THEN SFATOTFAC ELSE NULL END),0)
- ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 OR ADNCENATE IS NULL
AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END),0) facturadoPGP,

ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND CONVERT(DATE, SRFFECFAC, 103) < @0 AND SFATIPDOC IN(1,16) OR ADNCENATE IS NULL THEN SFATOTFAC ELSE NULL END),0)
- ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND CONVERT(DATE, SRFFECFAC, 103) < @0 AND SFATIPDOC IN(1,16) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 OR ADNCENATE IS NULL
AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END),0) refacturadoPGP,

ISNULL(SUM(CASE WHEN SFADOCANU = 0 AND SFATIPDOC IN(17) THEN SFATOTFAC ELSE NULL END),0) registroPGP,

ISNULL(SUM(CASE WHEN SFADOCANU = 0 AND CONVERT(DATE, SRFFECFAC, 103) < @0 AND SFATIPDOC IN(17) THEN SFATOTFAC ELSE NULL END),0) refacturadoRegistroPGP,

(ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) OR ADNCENATE IS NULL THEN SFATOTFAC ELSE NULL END),0) -
ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 OR ADNCENATE IS NULL
AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END),0) -
ISNULL(SUM(CASE WHEN GCVUSUFACTUR.SFADOCANU = 0 AND SFATIPDOC IN(17) THEN SFATOTFAC ELSE NULL END),0)
) deficitPGP

FROM GCVUSUFACTUR INNER JOIN GENDETCON C ON C.OID = GCVUSUFACTUR.GENDETCON
WHERE CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1 AND SFACANANU < 1
${
  centro
    ? 'AND ADNCENATE IN(' + centro + ')'
    : ctx === GCM_CONTEXTS.ALTACENTRO
    ? 'AND ADNCENATE IS NULL'
    : ''
} 
`;
};

export const getResumenPeriodoQuery = (centro: number) => {
  return `SELECT
ISNULL(SUM(SFATOTFAC),0)-ISNULL(SUM(CASE WHEN CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END), 0) totalFacturado,

ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) OR ADNCENATE IS NULL THEN SFATOTFAC ELSE NULL END),0)
- ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 OR ADNCENATE IS NULL
AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END),0) facturadoPGP,

ISNULL(SUM(CASE WHEN SFADOCANU = 0 AND SFATIPDOC IN(17) THEN SFATOTFAC ELSE NULL END),0) registroPGP,

(ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) OR ADNCENATE IS NULL THEN SFATOTFAC ELSE NULL END),0) -
ISNULL(SUM(CASE WHEN GDECODIGO LIKE '8%' AND SFATIPDOC IN(1,16) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 OR ADNCENATE IS NULL
AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END),0) -
ISNULL(SUM(CASE WHEN GCVUSUFACTUR.SFADOCANU = 0 AND SFATIPDOC IN(17) THEN SFATOTFAC ELSE NULL END),0)
) deficitPGP,

ISNULL(SUM(CASE WHEN SFADOCANU = 1 AND CONVERT(DATE, SFAFECANU, 103) > @1 THEN SFATOTFAC ELSE NULL END),0) anulacionesPosterioresTotalFacturado,

ISNULL(SUM(CASE WHEN SFADOCANU = 1 AND SFATIPDOC IN(17) AND CONVERT(DATE, SFAFECANU, 103) > @1 THEN SFATOTFAC ELSE NULL END),0) anulacionesPosterioresRegistroPGP,

ISNULL(SUM(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) < @0 AND SFATIPDOC != 17 THEN SFATOTFAC ELSE NULL END), 0) totalRefacturado

FROM GCVUSUFACTUR INNER JOIN GENDETCON C ON C.OID = GCVUSUFACTUR.GENDETCON
WHERE CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1 AND SFACANANU < 1
  ${centro ? 'AND ADNCENATE IN(' + centro + ')' : ''} 
`;
};
