export const getFacturasPendientesQuery = (anteriores: boolean) => {
  return `SELECT
  CONVERT(DATE, ADNEGRESO.ADEFECSAL) fecha,
  ADNINGRESO.ADNCENATE idCentro,
  ADNINGRESO.AINESTADO estado,
  SUM(dbo.SLNSERPRO.SERVALPRO * dbo.SLNSERPRO.SERCANTID) total
  FROM SLNSERPRO
  INNER JOIN ADNINGRESO ON ADNINGRESO.OID = SLNSERPRO.ADNINGRES1
  INNER JOIN ADNEGRESO ON ADNEGRESO.ADNINGRESO = ADNINGRESO.OID
  INNER JOIN SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
  AND SLNORDSER.SOSESTADO <> 2 AND CONVERT(DATE, ADNEGRESO.ADEFECSAL, 103) ${
    anteriores ? '< @0' : 'BETWEEN @0 AND @1'
  } AND AINESTADO NOT IN (1,2)
   GROUP BY 
  ADNEGRESO.ADEFECSAL,
  ADNEGRESO.ADENUMEGR,
  ADNINGRESO.ADNCENATE, 
  ADNINGRESO.AINESTADO`;
};
