SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.EKHPNROTULOMEDICAMENTOS', 'TIPOROTULO') IS NULL
BEGIN
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS
    ADD TIPOROTULO nvarchar(20) NOT NULL
      CONSTRAINT DF_EKHPNROTULOMEDICAMENTOS_TIPOROTULO DEFAULT ('MEDICAMENTO');
END;

IF COL_LENGTH('dbo.EKHPNROTULOMEDICAMENTOS', 'MEZCLA') IS NULL
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ADD MEZCLA nvarchar(250) NULL;

IF COL_LENGTH('dbo.EKHPNROTULOMEDICAMENTOS', 'PREPARACION') IS NULL
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ADD PREPARACION nvarchar(10) NULL;

IF COL_LENGTH('dbo.EKHPNROTULOMEDICAMENTOS', 'VELOCIDADINFUSION') IS NULL
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ADD VELOCIDADINFUSION nvarchar(100) NULL;

IF COL_LENGTH('dbo.EKHPNROTULOMEDICAMENTOS', 'FINALIZACION') IS NULL
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ADD FINALIZACION nvarchar(10) NULL;

UPDATE dbo.EKHPNROTULOMEDICAMENTOS
SET TIPOROTULO = 'MEDICAMENTO'
WHERE TIPOROTULO IS NULL OR TIPOROTULO NOT IN ('MEDICAMENTO', 'SOLUCION');

ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ALTER COLUMN DOSIS decimal(18, 2) NULL;
ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS ALTER COLUMN UNIDADMEDIDA nvarchar(20) NULL;

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_EKHPNROTULOMEDICAMENTOS_TIPOROTULO'
)
BEGIN
  ALTER TABLE dbo.EKHPNROTULOMEDICAMENTOS
    ADD CONSTRAINT CK_EKHPNROTULOMEDICAMENTOS_TIPOROTULO
    CHECK (TIPOROTULO IN ('MEDICAMENTO', 'SOLUCION'));
END;

COMMIT TRANSACTION;
