DECLARE @FECHA VARCHAR(10)= '2024-10-30';

SELECT D.GENPACIEN AS FROM01DES, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 1 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM01ALM, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 2 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM01CEN, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 3 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM01DES, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 4 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM01ALM, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 5 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM01CEN, COUNT(D.GENPACIEN)
FROM DGEMPRES01..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 6 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM30DES, COUNT(D.GENPACIEN)
FROM DGEMPRES30..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 1 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM30ALM, COUNT(D.GENPACIEN)
FROM DGEMPRES30..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 2 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM30CEN, COUNT(D.GENPACIEN)
FROM DGEMPRES30..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 3 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM70DES, COUNT(D.GENPACIEN)
FROM DGEMPRES70..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 1 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM70ALM, COUNT(D.GENPACIEN)
FROM DGEMPRES70..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 2 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM70CEN, COUNT(D.GENPACIEN)
FROM DGEMPRES70..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 3 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM80DES, COUNT(D.GENPACIEN)
FROM DGEMPRES80..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 1 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1

SELECT D.GENPACIEN AS FROM80ALM, COUNT(D.GENPACIEN)
FROM DGEMPRES80..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 2 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1


SELECT D.GENPACIEN AS FROM80CEN, COUNT(D.GENPACIEN)
FROM DGEMPRES80..PDYDIEEST D
INNER JOIN PDYDIEGRU G ON G.OID = D.PDYDIEGRU
INNER JOIN PDYDIEJOR J ON J.OID = G.PDYDIEJOR
 WHERE J.DIEFECJOR = @FECHA AND J.DIEHORARIO = 3 AND D.ELIMINADO = 0
GROUP BY D.GENPACIEN
HAVING COUNT(D.GENPACIEN) > 1