-- Ejecutar en cada base clínica antes de desplegar backend y frontend.
-- No modifica las evoluciones generales ni copia ingresos anteriores.
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID('dbo.EKHPNHOJAESPECIALIDAD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EKHPNHOJAESPECIALIDAD (
    OID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ADNINGRESO int NOT NULL REFERENCES dbo.ADNINGRESO(OID),
    GENESPECI int NOT NULL REFERENCES dbo.GENESPECI(OID),
    CONTENIDO nvarchar(max) NOT NULL DEFAULT N'',
    ACTIVA bit NOT NULL DEFAULT 1,
    VERSION int NOT NULL DEFAULT 0 CHECK (VERSION >= 0),
    CREADOPOR int NOT NULL REFERENCES dbo.GENUSUARIO(OID),
    MODIFICADOPOR int NULL REFERENCES dbo.GENUSUARIO(OID),
    FECHACREACION datetime2 NOT NULL,
    FECHAMODIFICACION datetime2 NULL,
    CONSTRAINT UQ_EKHPNHOJA_INGRESO_ESPECIALIDAD UNIQUE (ADNINGRESO, GENESPECI)
  );
END;
IF OBJECT_ID('dbo.EKHPNHOJAESPECIALIDADVERSION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EKHPNHOJAESPECIALIDADVERSION (
    OID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    HOJA int NOT NULL REFERENCES dbo.EKHPNHOJAESPECIALIDAD(OID),
    VERSION int NOT NULL CHECK (VERSION > 0),
    CONTENIDO nvarchar(max) NOT NULL,
    GENUSUARIO int NOT NULL REFERENCES dbo.GENUSUARIO(OID),
    FECHA datetime2 NOT NULL,
    CONSTRAINT UQ_EKHPNHOJAVERSION_HOJA_VERSION UNIQUE (HOJA, VERSION)
  );
END;
COMMIT TRANSACTION;
