import { BaseSource } from '@common/infrastructure/services';
import { Inject, Injectable } from '@nestjs/common';

@Injectable()
export class CensusBedsRepository extends BaseSource {
  async getCensusBeds() {
    return await this.conn.query(
      `SELECT 
      G.OID,
      G.HGRCODIGO,
      G.HGRNOMBRE,
      COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END) CAMAS,
      COUNT(CASE WHEN D.HCAESTADO = 2 THEN D.OID ELSE NULL END) OCUPADAS,
      COUNT(CASE WHEN D.HCAESTADO IN(1, 3, 4, 5) THEN D.OID ELSE NULL END) DESOCUPADAS,
      ROUND(ISNULL(COUNT(CASE WHEN D.HCAESTADO = 2 THEN D.OID ELSE NULL END)*100*1.0
      /NULLIF(COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END), 0), 0), 2) PORCENTAJE_OCUPADAS,
      ROUND(ISNULL((COUNT(CASE WHEN D.HCAESTADO IN(1, 3, 4, 5) THEN D.OID ELSE NULL END)*100 *1.0
      /NULLIF(COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END), 0)), 0), 2) PORCENTAJE_DESOCUPADAS,
      A.ACANOMBRE
      FROM HPNDEFCAM D 
      INNER JOIN HPNGRUPOS G ON D.HPNGRUPOS = G.OID
      INNER JOIN ADNCENATE A ON A.OID = D.ADNCENATE
      GROUP BY G.OID, G.HGRCODIGO, G.HGRNOMBRE, A.ACANOMBRE
      ORDER BY G.OID`
    );
  }

  async getGroupCensusBeds(grupo: string) {
    return await this.conn.query(
      `SELECT 
      G.OID,
      G.HSUCODIGO,
      G.HSUNOMBRE,
      COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END) CAMAS,
      COUNT(CASE WHEN D.HCAESTADO = 2 THEN D.OID ELSE NULL END) OCUPADAS,
      COUNT(CASE WHEN D.HCAESTADO IN(1, 3, 4, 5) THEN D.OID ELSE NULL END) DESOCUPADAS,
      ROUND(ISNULL(COUNT(CASE WHEN D.HCAESTADO = 2 THEN D.OID ELSE NULL END)*100*1.0
      /NULLIF(COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END), 0), 0), 2) PORCENTAJE_OCUPADAS,
      ROUND(ISNULL((COUNT(CASE WHEN D.HCAESTADO IN(1, 3, 4, 5) THEN D.OID ELSE NULL END)*100 *1.0
      /NULLIF(COUNT(CASE WHEN D.HCAESTADO <> 6 THEN D.OID ELSE NULL END), 0)), 0), 2) PORCENTAJE_DESOCUPADAS,
      A.ACANOMBRE
      FROM HPNDEFCAM D 
	    INNER JOIN HPNGRUPOS H ON H.OID = D.HPNGRUPOS
      INNER JOIN HPNSUBGRU G ON D.HPNSUBGRU = G.OID
      INNER JOIN ADNCENATE A ON A.OID = D.ADNCENATE
      WHERE H.HGRCODIGO = @0
      GROUP BY G.OID, G.HSUCODIGO, G.HSUNOMBRE, A.ACANOMBRE
      ORDER BY G.OID`,
      [grupo]
    );
  }

  async getBeds() {
    const res = await this.conn.query(
      `SELECT 
      HCAESTADO,
	    HSUCODIGO,
      HCACODIGO,
      GPADOCPAC,
      GPANOMPAC,
      AINCONSEC,
      GDENOMBRE, 
      ACANOMBRE
      FROM GCVHOSCENCAM
      WHERE HCAESTADO <> 6
      ORDER BY GPADOCPAC DESC`
    );
    return res;
  }

  async getAllCamas() {
    const camas = await this.conn.query(`SELECT C.OID,
    C.ADNCENATE,C.ADNINGRESO,I.AINCONSEC,I.AINFECING,P.PACPRINOM,P.PACSEGNOM,P.PACPRIAPE,P.PACSEGAPE,
    M.MUNNOMMUN,B.GEBNOMBRE,D.PACDIRECCION,
  C.HCAAISLAMIEN,C.HCABLOPOR,C.HCACODIGO,C.HCAESTADO,C.HCANOMBRE,C.HCANUMHABI,C.HCAOBSHOS,C.HPNGRUPOS,
  G.HGRCODIGO, G.HGRNOMBRE,C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE,
  C.HPNTIPOCA, I.GENDETCON, T.GDECODIGO, T.GDENOMBRE, T.GENTERCER1, R.TERNUMDOC, R.TERNOMCOM FROM HPNDEFCAM C
  INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
  INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
  LEFT JOIN ADNINGRESO I ON C.ADNINGRESO = I.OID
  LEFT JOIN GENPACIEN P ON I.GENPACIEN = P.OID
  LEFT JOIN GENDETCON T ON I.GENDETCON = T.OID
  LEFT JOIN GENBARRIO B ON P.GENBARRIO = B.OID
  LEFT JOIN GENPACIEND D ON P.GENPACIEND = D.OID
  LEFT JOIN GENMUNICI M ON P.DGNMUNICIPIO = M.OID
LEFT JOIN GENTERCER R ON T.GENTERCER1 = R.OID WHERE C.HCAESTADO != 6 ORDER BY C.ADNINGRESO DESC;`);

    const gastos = await this.conn.query(`SELECT  C.ADNINGRESO, 
  SUM(SP.SERVALPRO * SP.SERCANTID) AS SUMA
  FROM HPNDEFCAM C
  LEFT JOIN SLNSERPRO SP ON C.ADNINGRESO = SP.ADNINGRES1
  INNER JOIN SLNORDSER O ON SP.SLNORDSER1= O.OID
  WHERE C.HCAESTADO != 6 AND O.SOSESTADO != 2 GROUP BY C.ADNINGRESO ORDER BY SUMA ASC;`);

    camas.map((r: any) => {
      r.PACNOMCOM = `${r.PACPRINOM ? r.PACPRINOM.trim() : ''} ${
        r.PACSEGNOM ? r.PACSEGNOM.trim() : ''
      } ${r.PACPRIAPE ? r.PACPRIAPE.trim() : ''} ${r.PACSEGAPE ? r.PACSEGAPE.trim() : ''}`;
      delete r.PACPRINOM;
      delete r.PACSEGNOM;
      delete r.PACPRIAPE;
      delete r.PACSEGAPE;
      const gasto = gastos.filter((i: any) => r.ADNINGRESO === i.ADNINGRESO);
      r.TOTAL_CONSUMO = gasto[0] ? gasto[0].SUMA : 0;
    });

    return camas;
  }
}
