import { MODULES } from './principal';

export const CRN_AUTHORITIES = {
  CODE: MODULES.CARTERA.CODE,
  GESTIONES_CONCILIACIONES: {
    CODE: MODULES.CARTERA.SUBS.GESTIONES_CONCILIACIONES,
    ADMINISTRAR_GESTIONES: `${MODULES.CARTERA.SUBS.GESTIONES_CONCILIACIONES}001`,
    ADMINISTRAR_CONCILIACIONES: `${MODULES.CARTERA.SUBS.GESTIONES_CONCILIACIONES}002`,
    ELIMINAR_GESTION_CONCILIACION: `${MODULES.CARTERA.SUBS.GESTIONES_CONCILIACIONES}003`,
  },
  RADICACIONES: {
    CODE: MODULES.CARTERA.SUBS.RADICACIONES,
    GESTIONAR_RADICACIONES_GCM: `${MODULES.CARTERA.SUBS.RADICACIONES}001`,
  },
};
