import { MODULES } from './principal';

export const GEN_AUTHORITIES = {
  CODE: MODULES.GENERAL.CODE,
  ADMIN: `${MODULES.GENERAL.CODE}001`,
  SECURITY: {
    ADMIN: `${MODULES.GENERAL.SUBS.SECURITY}001`,
  },
  AUTHORITIES: {
    CODE: MODULES.GENERAL.SUBS.AUTHORITIES,
    MANAGE_ALL_AUTHORITIES: `${MODULES.GENERAL.SUBS.AUTHORITIES}001`,
    CREATE_AUTHORITIES: `${MODULES.GENERAL.SUBS.AUTHORITIES}002`,
  },
  DEPENDENCIAS: {
    CODE: MODULES.GENERAL.SUBS.DEPENDENCIAS,
    GESTIONAR: `${MODULES.GENERAL.SUBS.DEPENDENCIAS}001`,
    INACTIVO_2: `${MODULES.GENERAL.SUBS.DEPENDENCIAS}002`,
    INACTIVO_3: `${MODULES.GENERAL.SUBS.DEPENDENCIAS}003`,
  },
};
