export const fetchPacientesByReferencia = (
  pattern?: string,
  consecutivoId?: number,
  solicitudId?: number
) => {
  return `SELECT ${
    pattern ? 'top(5) ' : ''
  } 2 AS ORIGEN, HCNREFERSOL.OID, HCNREFERSOL.HCCONSEC AS CONSECUTIVO,
    HCNREFERSOL.HCFECHA AS FECHA_SOL,
    CASE WHEN HCNREFERSOL.HCESTADO = 0 THEN 'NINGUNO'
      WHEN HCNREFERSOL.HCESTADO = 1 THEN 'REGISTRADO'
      WHEN HCNREFERSOL.HCESTADO = 2 THEN 'PENDIENTE'
      WHEN HCNREFERSOL.HCESTADO = 3 THEN 'ACEPTADO'
      WHEN HCNREFERSOL.HCESTADO = 4 THEN 'SUSPENDIDO'
      WHEN HCNREFERSOL.HCESTADO = 5 THEN 'CERRADO' END AS ESTADO,
  CASE HCNREFTRAMDS.HCPACACEP WHEN 0 THEN 'NINGUNO' WHEN 1 THEN 'SI' WHEN 2 THEN 'NO' WHEN 3 THEN 'PENDIENTE' END AS PACIENTE_ACEPTADO,
    CASE WHEN HCNREFERSOL.HCPRIOR = 0 THEN 'NINGUNO'
      WHEN HCNREFERSOL.HCPRIOR = 1 THEN 'URGENTE'
      WHEN HCNREFERSOL.HCPRIOR = 2 THEN 'PRIORITARIO'
      WHEN HCNREFERSOL.HCPRIOR = 3 THEN 'REGULAR' END AS PRIORIDAD,
    CASE WHEN HCNREFERSOL.HCTIPDOCPAC = 0 THEN ' NINGUNO'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 4 THEN 'REGISTRO CIVIL'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 3 THEN 'TARJETA DE IDENTIDAD'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 1 THEN 'CÉDULA DE CIUDADANÍA'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 2 THEN 'CEDULA DE EXTRANJERIA'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 5 THEN 'PASAPORTE'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 6 THEN 'ADULTO SIN IDENTIFICACION'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 7 THEN 'MENOR SIN IDENTIFICACIÓN'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 8 THEN 'NUMERO UNICO DE IDENTIFICAION'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 9 THEN 'SALVOCONDUCTO'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 10 THEN 'CERTIFICADO NACIDO VIVO'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 11 THEN 'CARNET DIPLOMATICO'
      WHEN HCNREFERSOL.HCTIPDOCPAC = 12 THEN 'PERMISO ESPECIAL DE PERMANENCIA'
    END AS TIPO_DOC_PAC,
    CASE WHEN HCNREFTRAM.HCSERREM = 0 THEN 'NINGUNO'
      WHEN HCNREFTRAM.HCSERREM = 1 THEN 'CONSULTA EXTERNA AMBULATORIA'
      WHEN HCNREFTRAM.HCSERREM = 2 THEN 'HOSPITALIZACION'
      WHEN HCNREFTRAM.HCSERREM = 3 THEN 'URGENCIAS'
      WHEN HCNREFTRAM.HCSERREM = 4 THEN 'UCI'
      WHEN HCNREFTRAM.HCSERREM = 5 THEN 'OTROS' END AS SERVICIO_QUEREMITE,
    CASE WHEN HCNREFTRAM.HCSERALREM = 0 THEN 'NINGUNO'
      WHEN HCNREFTRAM.HCSERALREM = 1 THEN 'CONSULTA EXTERNA AMBULATORIA'
      WHEN HCNREFTRAM.HCSERALREM = 2 THEN 'HOSPITALIZACION'
      WHEN HCNREFTRAM.HCSERALREM = 3 THEN 'URGENCIAS'
      WHEN HCNREFTRAM.HCSERALREM = 4 THEN 'UCI'
      WHEN HCNREFTRAM.HCSERALREM = 5 THEN 'OTROS' END AS SERVICIO_ALQUEREMITE,
    HCNREFERSOL.HCNUMDOCPAC NUM_DOCUMENTO,
    (SELECT TOP(1)AINCONSEC  FROM ADNINGRESO 
  INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  WHERE GENPACIEN.PACNUMDOC=HCNREFERSOL.HCNUMDOCPAC
  ORDER BY AINFECING DESC) AS INGRESO,
  (SELECT TOP(1)HPNDEFCAM  FROM ADNINGRESO 
  INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  WHERE GENPACIEN.PACNUMDOC=HCNREFERSOL.HCNUMDOCPAC
  ORDER BY AINFECING DESC) AS CAMA,
  (SELECT TOP(1)AINFECING  FROM ADNINGRESO 
  INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  WHERE GENPACIEN.PACNUMDOC=HCNREFERSOL.HCNUMDOCPAC
  ORDER BY AINFECING DESC) AS FECHA_INGRESO,
  (SELECT TOP 1 D.DIANOMBRE
   FROM HCNFOLIO F
   INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
   INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
   WHERE F.ADNINGRESO = (SELECT TOP(1) ADNINGRESO.OID 
                         FROM ADNINGRESO 
                         INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
                         WHERE GENPACIEN.PACNUMDOC = HCNREFERSOL.HCNUMDOCPAC
                         ORDER BY AINFECING DESC)
   ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
    ISNULL(HCNREFERSOL.HCPRINOMPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGNOMPAC,'') + ' ' +
    ISNULL(HCNREFERSOL.HCPRIAPEPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGAPEPAC,'') AS PACIENTE,
    DATEDIFF(YEAR, HCNREFERSOL.HCFECNACPAC, GETDATE()) AS EDAD,
    CASE WHEN HCNREFERSOL.HCSEXPAC = 1 THEN 'M'
      WHEN HCNREFERSOL.HCSEXPAC = 2 THEN 'F' END AS SEXO,
    HCNREFENT.HCNOMBRE AS ENTI_REFERENCIA,
    GENDETCON.GDENOMBRE AS EPS,
    GENMUNICI1.MUNNOMMUN AS MUNICIPIO,
    HCNREFERSOL.HCNOMMED MEDICO,
    HCNREFERSOL.HCNREFTRAM AS TRAMITE,
    HCNREFMOTREM.HCNOMBRE AS MOT_REMI,
    HCNREFTRAM.HCAMPMOT MOT_REMI2,
    HCNREFTRAMDS.HCFUNCONTES AS FUNCIONA_CONTESTA,
    HCNREFTRAMDS.HCOBSERV AS OBS_SEGUIMIENTO,
     HCNREFTRAMDS.HCFECHAACEP AS FEC_ACEPTACION,
    HCNREFTRAMDS.HCOBSERVCC AS OBS_CIERRE,
    GENESPECI.GEEDESCRI AS ESPECIALIDAD,
    HCNREFTRAMDS.HCTRASPACFEC AS FECHA_TRASLADO_PAC,
    GENUSUARIO.USUDESCRI AS NOMBRE,
    HCNREFERSOL.HCNUMDOCPAC AS CEDULA
  FROM HCNREFERSOL
    INNER JOIN HCNREFTRAM ON HCNREFTRAM.OID = HCNREFERSOL.HCNREFTRAM AND
      HCNREFERSOL.OID = HCNREFTRAM.HCNREFERSOL
    LEFT JOIN HCNREFTRAMDS ON HCNREFTRAMDS.OID = HCNREFTRAM.HCNREFTRAMDS1
    INNER JOIN HCNREFMOTREM ON HCNREFMOTREM.OID = HCNREFTRAM.HCNREFMOTREM
    INNER JOIN HCNREFENT ON HCNREFENT.OID = HCNREFERSOL.HCNREFENT
    INNER JOIN GENMUNICI ON GENMUNICI.OID = HCNREFERSOL.GENMUNICI1
    INNER JOIN GENDETCON ON GENDETCON.OID = HCNREFERSOL.GENDETCON
    INNER JOIN GENESPECI ON GENESPECI.OID = HCNREFTRAM.GENESPECI
    INNER JOIN GENMUNICI GENMUNICI1 ON GENMUNICI1.OID = HCNREFERSOL.GENMUNICI2
    LEFT JOIN GENUSUARIO ON GENUSUARIO.OID = HCNREFTRAMDS.GENUSUARIO    
    WHERE  HCNREFERSOL.HCCONSEC LIKE '%${pattern}%' 
    --WHERE  HCNREFERSOL.HCESTADO IN (1,2) AND  HCNREFTRAMDS.HCPACACEP IN (1)
    --AND (SELECT TOP(1)AINCONSEC FROM ADNINGRESO
    --INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
    --WHERE GENPACIEN.PACNUMDOC=HCNREFERSOL.HCNUMDOCPAC ORDER BY AINFECING DESC) IS NULL
    --${pattern ? 'and HCCONSEC like ' + `'%${pattern}%'` : ''}
    --${consecutivoId ? `and HCNREFERSOL.HCCONSEC = ${consecutivoId}` : ''}
    --${solicitudId ? `and HCNREFERSOL.OID = ${solicitudId}` : ''}
  --ORDER BY 1 DESC`;
};

export const fetchPacientesByHospitalizacion = (keyword: string) => {
  // const query = `select top 5
  //   1 as ORIGEN,
  //   ADNINGRESO OID,
  //   AINCONSEC CONSECUTIVO,
  //   GPANOMPAC PACIENTE,
  //   GPADOCPAC CEDULA,
  //   GDENOMBRE ENTI_REFERENCIA,
  //   GPAMUNPAC MUNICIPIO,
  //   AINFECING,
  //       CASE AINURGCON
  //       WHEN -1 THEN 'NINGUNO'
  //       WHEN 0 THEN 'URGENCIAS'
  //       WHEN 1 THEN 'CONSULTA EXTERNA'
  //       WHEN 2 THEN 'NACIDO EN LA IPS'
  //       WHEN 3 THEN 'REMITIDO'
  //       WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
  //       WHEN 5 THEN 'HOSPITALIZACION'
  //       WHEN 6 THEN 'IMAGENES'
  //       WHEN 7 THEN 'LABORATORIO'
  //       WHEN 8 THEN 'URGENCIA GINECOLOGIA'
  //       WHEN 9 THEN 'QUIROFANO'
  //       WHEN 10 THEN 'CIRUGIA AMBULATORIA'
  //       WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //       WHEN 12 THEN 'UCI NEONATAL'
  //       WHEN 13 THEN 'UCI ADULTO'
  //       END AS MOT_REMI,
  //       CASE AINCAUING
  //       WHEN 0 THEN 'NINGUNA'
  //       WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
  //       WHEN 2 THEN 'HERIDOS EN COMBATE'
  //       WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
  //       WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
  //       WHEN 5 THEN 'ODONTOLOGIA'
  //       WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
  //       WHEN 7 THEN 'CATASTROFE DE FISALUD'
  //       WHEN 8 THEN 'QUEMADOS'
  //       WHEN 9 THEN 'MATERNIDAD'
  //       WHEN 10 THEN 'ACCIDENTE LABORAL'
  //       WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //       END AS MOT_REMI2
  //       FROM     GCVHOSCENPAC
  //       WHERE  (HESFECSAL IS NULL)
  //       AND (GPADOCPAC like '%${keyword}%' OR AINCONSEC LIKE '%${keyword}%')
  //       AND (HCAESTADO < 3)
  //       AND AINURGCON <> 1`;

  // return query;
  return `select top 5
		1 as ORIGEN,
    I.OID OID,
    I.AINCONSEC CONSECUTIVO,
    P.GPANOMCOM PACIENTE,
    P.PACNUMDOC CEDULA,
   (SELECT TOP 1 D.DIANOMBRE
    FROM HCNFOLIO F
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    WHERE F.ADNINGRESO = I.OID
    ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
   GDENOMBRE ENTI_REFERENCIA,
    M.MUNNOMMUN MUNICIPIO,
    I.AINFECING,
	CASE I.AINURGCON
        WHEN -1 THEN 'NINGUNO'
        WHEN 0 THEN 'URGENCIAS'
        WHEN 1 THEN 'CONSULTA EXTERNA'
        WHEN 2 THEN 'NACIDO EN LA IPS'
        WHEN 3 THEN 'REMITIDO'
        WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
        WHEN 5 THEN 'HOSPITALIZACION'
        WHEN 6 THEN 'IMAGENES'
        WHEN 7 THEN 'LABORATORIO'
        WHEN 8 THEN 'URGENCIA GINECOLOGIA'
        WHEN 9 THEN 'QUIROFANO'
        WHEN 10 THEN 'CIRUGIA AMBULATORIA'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        WHEN 12 THEN 'UCI NEONATAL'
        WHEN 13 THEN 'UCI ADULTO'
        END AS MOT_REMI,
        CASE AINCAUING
        WHEN 0 THEN 'NINGUNA'
        WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
        WHEN 2 THEN 'HERIDOS EN COMBATE'
        WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
        WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
        WHEN 5 THEN 'ODONTOLOGIA'
        WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
        WHEN 7 THEN 'CATASTROFE DE FISALUD'
        WHEN 8 THEN 'QUEMADOS'
        WHEN 9 THEN 'MATERNIDAD'
        WHEN 10 THEN 'ACCIDENTE LABORAL'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        END AS MOT_REMI2
        FROM     GENPACIEN P
		LEFT JOIN ADNINGRESO I ON I.GENPACIEN = P.OID
		LEFT JOIN GENDETCON G ON G.OID = I.GENDETCON
		LEFT JOIN GENMUNICI M ON M.OID = P.DGNMUNICIPIO        
    WHERE I.AINCONSEC > 90000 AND I.AINCONSEC LIKE '%${keyword}%'`;
};

export const fetchPacientesEspecializada = (
  pattern?: string,
  consecutivoId?: number,
  solicitudId?: number
) => {
  return `Select ${pattern ? 'top(5) ' : ''}
  2 as ORIGEN,
   HCNREFERSOL.OID, HCNREFERSOL.HCCONSEC As CONSECUTIVO,
    ISNULL(HCNREFERSOL.HCPRINOMPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGNOMPAC,'') + ' ' +
    ISNULL(HCNREFERSOL.HCPRIAPEPAC,'') + ' ' + ISNULL(HCNREFERSOL.HCSEGAPEPAC,'') As PACIENTE,
    HCNREFENT.HCNOMBRE As ENTI_REFERENCIA,
    GENMUNICI1.MUNNOMMUN As MUNICIPIO,
    HCNREFMOTREM.HCNOMBRE As MOT_REMI,
    HCNREFTRAM.HCAMPMOT MOT_REMI2
  From HCNREFERSOL
    Inner Join HCNREFTRAM On HCNREFTRAM.OID = HCNREFERSOL.HCNREFTRAM And
      HCNREFERSOL.OID = HCNREFTRAM.HCNREFERSOL
    Left Join HCNREFTRAMDS On HCNREFTRAMDS.OID = HCNREFTRAM.HCNREFTRAMDS1
    Inner Join HCNREFMOTREM On HCNREFMOTREM.OID = HCNREFTRAM.HCNREFMOTREM
    Inner Join HCNREFENT On HCNREFENT.OID = HCNREFERSOL.HCNREFENT
    Inner Join GENMUNICI On GENMUNICI.OID = HCNREFERSOL.GENMUNICI1
    Inner Join GENDETCON On GENDETCON.OID = HCNREFERSOL.GENDETCON
    Inner Join GENESPECI On GENESPECI.OID = HCNREFTRAM.GENESPECI
    Inner Join GENMUNICI GENMUNICI1 On GENMUNICI1.OID = HCNREFERSOL.GENMUNICI2
    Left Join GENUSUARIO On GENUSUARIO.OID = HCNREFTRAMDS.GENUSUARIO
    WHERE  HCNREFERSOL.HCESTADO IN (1,2) AND  HCNREFTRAMDS.HCPACACEP IN (1)
    and (SELECT TOP(1)AINCONSEC FROM ADNINGRESO
    INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
    WHERE PACNUMDOC=HCNREFERSOL.HCNUMDOCPAC ORDER BY AINFECING DESC) is null
    ${pattern ? 'and HCCONSEC like ' + `'%${pattern}%'` : ''}
    ${consecutivoId ? `and HCNREFERSOL.HCCONSEC = ${consecutivoId}` : ''}
    ${solicitudId ? `and HCNREFERSOL.OID = ${solicitudId}` : ''}
  order by 1 desc`;
};

export const selectPacienteFromHpn = (consecutivo?: number, ingreso?: number) => {
  // return `select
  // 1 AS ORIGEN,
  // ADNINGRESO OID,
  // AINCONSEC CONSECUTIVO,
  // GPANOMPAC PACIENTE,
  // GPADOCPAC CEDULA,
  // GDENOMBRE ENTI_REFERENCIA,
  // GPAMUNPAC MUNICIPIO,
  // AINFECING,
  //     CASE AINURGCON
  //     WHEN -1 THEN 'NINGUNO'
  //     WHEN 0 THEN 'URGENCIAS'
  //     WHEN 1 THEN 'CONSULTA EXTERNA'
  //     WHEN 2 THEN 'NACIDO EN LA IPS'
  //     WHEN 3 THEN 'REMITIDO'
  //     WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
  //     WHEN 5 THEN 'HOSPITALIZACION'
  //     WHEN 6 THEN 'IMAGENES'
  //     WHEN 7 THEN 'LABORATORIO'
  //     WHEN 8 THEN 'URGENCIA GINECOLOGIA'
  //     WHEN 9 THEN 'QUIROFANO'
  //     WHEN 10 THEN 'CIRUGIA AMBULATORIA'
  //     WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //     WHEN 12 THEN 'UCI NEONATAL'
  //     WHEN 13 THEN 'UCI ADULTO'
  //     END AS MOT_REMI,
  //     CASE AINCAUING
  //     WHEN 0 THEN 'NINGUNA'
  //     WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
  //     WHEN 2 THEN 'HERIDOS EN COMBATE'
  //     WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
  //     WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
  //     WHEN 5 THEN 'ODONTOLOGIA'
  //     WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
  //     WHEN 7 THEN 'CATASTROFE DE FISALUD'
  //     WHEN 8 THEN 'QUEMADOS'
  //     WHEN 9 THEN 'MATERNIDAD'
  //     WHEN 10 THEN 'ACCIDENTE LABORAL'
  //     WHEN 11 THEN 'CIRUGIA PROGRAMADA'
  //     END AS MOT_REMI2
  //     FROM GCVHOSCENPAC
  //     ${consecutivo ? `WHERE AINCONSEC = ${consecutivo}` : ''}
  //     ${ingreso ? `WHERE ADNINGRESO = ${ingreso}` : ''}`;
  return `
  select
		1 as ORIGEN,
    I.OID OID,
    I.AINCONSEC CONSECUTIVO,
    P.GPANOMCOM PACIENTE,
    P.PACNUMDOC CEDULA,
   (SELECT TOP 1 D.DIANOMBRE
    FROM HCNFOLIO F
    INNER JOIN HCNDIAPAC DP ON DP.HCNFOLIO = F.OID
    INNER JOIN GENDIAGNO D ON DP.GENDIAGNO = D.OID
    WHERE F.ADNINGRESO = I.OID
    ORDER BY F.HCFECFOL DESC, DP.HCPDIAPRIN DESC) AS DIAGNOSTICO,
   GDENOMBRE ENTI_REFERENCIA,
    M.MUNNOMMUN MUNICIPIO,
    I.AINFECING,
	CASE I.AINURGCON
        WHEN -1 THEN 'NINGUNO'
        WHEN 0 THEN 'URGENCIAS'
        WHEN 1 THEN 'CONSULTA EXTERNA'
        WHEN 2 THEN 'NACIDO EN LA IPS'
        WHEN 3 THEN 'REMITIDO'
        WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
        WHEN 5 THEN 'HOSPITALIZACION'
        WHEN 6 THEN 'IMAGENES'
        WHEN 7 THEN 'LABORATORIO'
        WHEN 8 THEN 'URGENCIA GINECOLOGIA'
        WHEN 9 THEN 'QUIROFANO'
        WHEN 10 THEN 'CIRUGIA AMBULATORIA'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        WHEN 12 THEN 'UCI NEONATAL'
        WHEN 13 THEN 'UCI ADULTO'
        END AS MOT_REMI,
        CASE AINCAUING
        WHEN 0 THEN 'NINGUNA'
        WHEN 1 THEN 'ENFERMEDAD PROFESIONAL'
        WHEN 2 THEN 'HERIDOS EN COMBATE'
        WHEN 3 THEN 'ENFERMEDAD GENERAL DE ADULTO'
        WHEN 4 THEN 'ENFERMEDAD GENERAL DE PEDIATRIA'
        WHEN 5 THEN 'ODONTOLOGIA'
        WHEN 6 THEN 'ACCIDENTE DE TRANSITO'
        WHEN 7 THEN 'CATASTROFE DE FISALUD'
        WHEN 8 THEN 'QUEMADOS'
        WHEN 9 THEN 'MATERNIDAD'
        WHEN 10 THEN 'ACCIDENTE LABORAL'
        WHEN 11 THEN 'CIRUGIA PROGRAMADA'
        END AS MOT_REMI2
        FROM     GENPACIEN P
		LEFT JOIN ADNINGRESO I ON I.GENPACIEN = P.OID
		LEFT JOIN GENDETCON G ON G.OID = I.GENDETCON
		LEFT JOIN GENMUNICI M ON M.OID = P.DGNMUNICIPIO        
    --WHERE I.AINCONSEC = ${consecutivo}
    ${consecutivo ? `WHERE I.AINCONSEC = ${consecutivo}` : ''}
    ${ingreso ? `WHERE ADNINGRESO = ${ingreso}` : ''}`;
};
