export const TANQUEO_REPOSITORY = Symbol('TANQUEO_REPOSITORY');
export const VEHICULO_REPOSITORY = Symbol('VEHICULO_REPOSITORY');
export const ESTACION_SERVICIO_REPOSITORY = Symbol('ESTACION_SERVICIO_REPOSITORY');
export const TANQUEO_INCONSISTENCIA_REPOSITORY = Symbol('TANQUEO_INCONSISTENCIA_REPOSITORY');
export const SYNC_LOG_REPOSITORY = Symbol('SYNC_LOG_REPOSITORY');
export const IDEMPOTENCY_STORE_REPOSITORY = Symbol('IDEMPOTENCY_STORE_REPOSITORY');
export const ABASTECIMIENTO_REPOSITORY = Symbol('ABASTECIMIENTO_REPOSITORY');
export const REPOSITORIO_COMBUSTIBLE_REPOSITORY = Symbol('REPOSITORIO_COMBUSTIBLE_REPOSITORY');
