-- 111 INSERCIONES
INSERT INTO
      GCMAGRUPGP2 (
            COD_SERIPS,
            COD_CUPS,
            NOM_SERVIPS,
            --CODAREA,
            AGRUPADOR,
            ORDEN,
            CONTRATO,
            FECHA_CONTRATO
      )
VALUES
      (
            '040717',
            '040717',
            'RESECCION DE TUMOR BENIGNO DE NERVIO EN ANTEBRAZO VIA ABIERTA(45783)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0.330151827830189',
            '8018',
            '2022-09-01'
      ),
      (
            '044510',
            '044510',
            'DESCOMPRESION DE NERVIO EN HOMBRO VIA ABIERTA(45821)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '2.83930571933962',
            '8018',
            '2022-09-01'
      ),
      (
            '372126',
            '372126',
            'HONORARIOS MEDICOS PARA PERINEOPLASTIA POR DESGARRO ANTIGUO DE PERINE(24482)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '639101',
            '639101',
            'ASPIRACION DE ESPERMATOCELE VIA PERCUTANEA(46410)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '699702',
            '699702',
            'RETIRO CUERPO EXTRA�O PENETRANTE EN CUELLO UTERINO VIA VAGINAL(46534)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '782771',
            '782771',
            'GRAPADO EPIFISIARIO DE FALANGES DE PIE (UNA O MAS)(32005)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '805202',
            '805202',
            'QUIMIONUCLEOLISIS DISCAL TORACICA(46989)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '864301',
            '864301',
            'CIRUGIA MICROGRAFICA [DE MOHS] POR CORTE(53660)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '766203',
            '766203',
            'OSTEOTOMIA DE RAMA MANDIBULAR VIA TRANS MUCOSA O VIA TRANSCUTANEA(29719)',
            --CODAREA,
            'CIRUGIA AMBULATORIA',
            6,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            'C40550',
            '361601 361602 361603 361604 361605 361606 361607 361608 361609 361610 361611 361612 361613 361614 361615 361616 361617 361618 361619 361620 361621 361622 361623 361624',
            'PUENTES AORTOCORONARIOS (386)(11625)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '352101',
            'C40551',
            'REEMPLAZO VALVULA MITRAL O AORTICA(11626)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '359501',
            'C40552',
            'REINTERVENCION POR SANGRADO POST-CIRUGIA DE CORAZON(27513)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '352401',
            'C40557',
            'REEMPLAZO O RECONSTRUCCION DE DOS O TRES VALVULAS(11632)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '351103',
            'C40562',
            'COMISUROTOMIA O VALVULOTOMIA CON CATETER BALON (45)(11637)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '351201',
            'C40569',
            'VALVULOPLASTIA MITRAL (385)(11644)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '352503',
            'E352602',
            'REPARACION POR DISFUNCION PROTESICA VALVULAR SIN REEMPLAZO VIA ENDOVASCULAR(35981)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '371203',
            'E371201',
            'VENTANA PERICARDICA POR VIDEOTORACOSCOPIA ( PERICARDIOTOMIA VIDEO ASISTIDA)(35983)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '352003',
            'E378303',
            'IMPLANTE PERCUTANEO DE VALVULA PULMONAR (INCLUYE SISTEMA DE INSERCION Y DISPOSITIVO PROTESICO)(35993)',
            --CODAREA,
            'CIRUGIA CARDIACA',
            21,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '890295',
            '890295',
            'CONSULTA DE PRIMERA VEZ POR ESPECIALISTA EN MEDICINA ALTERNATIVA (OSTEOPATICA)(5408)',
            --CODAREA,
            'CONSULTA MEDICA ESPECIALIZADA',
            1,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '378601',
            '379901',
            'IMPLANTE DE CARDIODESFIBRILADOR - PAQUETE(24287)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '373406',
            'E372218',
            'ABLACION SEPTAL CON ALCOHOL(35257)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '372801 373406',
            'E373404',
            'ESTUDIO ELECTROFISIOLOGICO MAPEO ENDOCARDICO Y ABLACION(32191)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '372801 373406',
            'E373405',
            'ESTUDIO ELECTROFISIOLOGICO CON MAPEO Y ABLACION ELECTROANATOMICO CON CATETERISMO IRRIGADO(44966)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '378401',
            'E378301',
            'IMPLANTE DE MARCAPASO Y/O RESINCRONIZADOR TRICAMERAL(NO INCLUYE EL MARCAPASO)(35992)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '378607',
            'E379902',
            'IMPLANTE DE SISTEMA DE CARDIODESFIBRILADOR SUBCUTANEO CON ELECTRODOS EXTRACARDIACOS(44292)',
            --CODAREA,
            'ELECTROFISIOLOGIA',
            15,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '372201',
            'C40553',
            'CATETERISMO CARDIACO DEL LADO IZQUIERDO DEL CORAZON (43)(11628)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '876212',
            'C40554',
            'ANGIOCARDIOGRAFIA DE CORAZON DERECHO (42)(11629)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '372302',
            'C40555',
            'CATETERISMO COMBINADO DE LOS LADOS DERECHO E IZQUIERDO DEL CORAZON (400)(11630)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '876121',
            'C40556',
            'CATETERISMO IZQUIERDO. MAS CATETERISMO DERECHO. MAS ARTERIOGRAFIA CORONARIA (356)(11631)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360101',
            'C40558',
            'ANGIOPLASTIA CORONARIA CON BALON. HASTA DOS VASOS (44)(11633)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360102',
            'C40559',
            'ANGIOPLASTIA CORONARIA CON BALON. EN MAS DE DOS VASOS (44)(11634)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360101',
            'C40560',
            'ANGIOPLASTIA CORONARIA Y/O ATERECTOMIA. DE UN VASO. MAS COLOCACION INTRAVASCULAR DE UNO O MAS STENTS (387) (388)(11635)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360102',
            'C40561',
            'ANGIOPLASTIA CORONARIA Y/O ATERECTOMIA. DE DOS O MAS VASOS. MAS COLOCACION INTRAVASCULAR DE UNO O MAS STENTS (388) (389)(11636)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '876122',
            'C40568',
            'ARTERIOGRAFIA CORONARIA MAS CATETERISMO IZQUIERDO CON ANGIOGRAFIA (329)(11643)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '372302',
            'C40820',
            'CATETERISMO IZQUIERDO Y DERECHO CON O SIN ANGIOGRAFIA MAS AORTOGRAMA (356) (383)(11739)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360101',
            'E360501',
            'ANGIOPLASTIA CORONARIA. MAS ARTERIOGRAFIA MAS UN STENT(INCLUYE STENT)(11927)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360501',
            'E378309',
            'ATERECTOMIA ROTACIONAL CORONARIA (ROTABLATOR) UN VASO(26003)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '360102',
            'E360103',
            'ANGIOPLASTIA CORONARIA Y/O ATERECTOM�A, DOS O M�S VASOS; M�S COLOCACI�N INTRAVASCULAR UNO O M�S STENTS.(11925)',
            --CODAREA,
            'HEMODINAMIA',
            14,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '10B001',
            '10B001',
            'INTERNACION COMPLEJIDAD BAJA HABITACION UNIPERSONAL INCLUYE AISLAMIENTO(56283)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '10B002',
            '10B002',
            'INTERNACION COMPLEJIDAD BAJA HABITACION BIPERSONAL(56284)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '10B003',
            '10B003',
            'INTERNACION COMPLEJIDAD BAJA TRES CAMAS(56285)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '10B004',
            '10B004',
            'INTERNACION COMPLEJIDAD BAJA CUATRO O MAS CAMAS(56286)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '120N01',
            'S12401',
            'INTERNACION EN UNIDAD DE CUIDADOS BASICOS NEONATALES COMPLEJIDAD MEDIANA(23357)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '120N01',
            'S12402',
            'INTERNACION EN UNIDAD DE CUIDADOS BASICOS NEONATALES COMPLEJIDAD ALTA(23358)',
            --CODAREA,
            'INTERNACION MEDICA',
            7,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '793709',
            '793709',
            'REDUCCION ABIERTA DE FRACTURA DE PERONE DIAFISIARIO CON FIJACION INTERNA(46927)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0.000010564072327044',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '395080',
            '395080',
            'ANGIOPLASTIA O ATERECTOMIA DE VASOS DE MIEMBROS INFERIORES. CON BALON(1909)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0.00000528203616352201',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '10A005',
            '10A005',
            'INTERNACION EN UNIDAD DE TRASPLANTE(56282)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '275802',
            '275802',
            'PROFUNDIZACION DE PISO DE BOCA(29390)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '440202',
            '440202',
            'VAGOTOMIA SELECTIVA O SUPRASELECTIVA VIA LAPAROSCOPICA(42202)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '451303',
            '451303',
            'INSERCION ENDOSCOPICA DE DISPOSTIVO DUODENAL(30018)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '502218',
            '502218',
            'LOBECTOMIA HEPATICA DERECHA DE DONANTE VIA ABIERTA(53633)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '502219',
            '502219',
            'LOBECTOMIA HEPATICA DERECHA DE DONANTE VIA LAPAROSCOPICA(53634)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '504001',
            '504001',
            'HEPATECTOMIA TOTAL (OBTENCION DE ORGANO) SIN CIRUGIA DE BANCO VIA ABIERTA(53637)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '504101',
            '504101',
            'HEPATECTOMIA TOTAL (OB TENCION DE ORGANO) CON CIRUGIA DE BANCO REDUCCION ANATOMICA(2402)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '504102',
            '504102',
            'HEPATECTOMIA TOTAL (OB TENCION DE ORGANO) CON CIRUGIA DE BANCO DIVISION ANATOMICA(2404)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '691102',
            '691102',
            'ESCISION O ABLACION DE LESION O TEJIDO EN ESTRUCTURAS DE SOPORTE(29808)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '773101',
            '773101',
            'OSTEOTOMIA PERIARTICULAR UNICA(46754)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '773103',
            '773103',
            'OSTEOTOMIA INTRAARTICULAR UNICA(46756)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '779942',
            '779942',
            'VERTEBRECTOMIA TOTAL CERVICAL TRANSORAL(46849)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '783803',
            '783803',
            'ALARGAMIENTO DE METATARSIANOS (UNO O MAS) POR INJERTO SIN DISPOSITIVOS INTERNOS DE FIJACION Y OSTEOTOMIA(3724)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '783805',
            '783805',
            'ALARGAMIENTO DE TARSIANOS (UNO O MAS) POR TECNICA DE DISTRACCI�N SIN CORTICOTOMIA/OSTEOTOMIA(3728)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '805107',
            '805107',
            'ESCISION DE DISCO INTERVERTEBRAL EN SEGMENTO CERVICAL VIA ANTERIOR PERCUTANEO(46969)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '810901',
            '810901',
            'REFUSION DE COLUMNA OCCIPITOCERVICAL ANTERIOR O LATERAL(47216)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '811202',
            '811202',
            'ARTRODESIS SUBTALAR VIA ABIERTA(47232)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '858405',
            '858405',
            'COLGAJO LIBRE CON TECNICA MICROVASCULAR EN LA MAMA(4588)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862505',
            '862505',
            'DERMOABRASION (QUIMICA O MECANICA) DE AREA GENERAL MENOR DEL 10% DE SUPERFICIE CORPORAL(24783)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862329',
            '862329',
            'ESCARECTOMIA DEL 30% O MAS DE SUPERFICIE CORPORAL(47394)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862352',
            '862352',
            'ESCAROTOMIA DESCOMPRESIVA EN TOBILLOS O PIES(47396)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862353',
            '862353',
            'ESCAROTOMIA DESCOMPRESIVA EN EXTREMIDAD SUPERIOR EXCEPTO MU�ECA MANOS(47397)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862354',
            '862354',
            'ESCAROTOMIA DESCOMPRESIVA EN EXTREMIDAD INFERIOR EXCEPTO TOBILLO PIE(47398)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862355',
            '862355',
            'ESCAROTOMIA DESCOMPRESIVA EN TRONCO (TORAX O ABDOMEN)(47399)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862506',
            '862506',
            'DERMOABRASION (QUIMICA O MECANICA) DE AREA GENERAL ENTRE EL 10% AL 19 % DE SUPERFICIE CORPORAL(47400)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862507',
            '862507',
            'DERMOABRASION (QUIMICA O MECANICA) DE AREA GENERAL ENTRE EL 20% AL 29 % DE SUPERFICIE CORPORAL(47401)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862508',
            '862508',
            'DERMOABRASION (QUIMICA O MECANICA) DE AREA GENERAL DEL 30 % AL 49% DE SUPERFICIE CORPORAL(47402)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862509',
            '862509',
            'DERMOABRASION (QUIMICA O MECANICA) DE AREA GENERAL DEL 50% O MAS DE SUPERFICIE CORPORAL(47403)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862511',
            '862511',
            'DERMOABRASION (QUIMICA O MECANICA) EN AREA ESPECIAL EN PLIEGUES DE FLEXION (AXILA , ANTECUBITAL, HUECOS POPLITEOS, INGUINAL)(47405)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862512',
            '862512',
            'DERMOABRASION (QUIMICA O MECANICA) EN AREA ESPECIAL EN MU�ECAS Y MANOS(47406)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862513',
            '862513',
            'DERMOABRASION (QUIMICA O MECANICA) EN AREA ESPECIAL EN TOBILLOS Y PIES(47407)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '862514',
            '862514',
            'DERMOABRASION (QUIMICA O MECANICA) EN AREA ESPECIAL EN GENITALES(47408)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '841202',
            '841202',
            'AMPUTACION O DESARTICULACION DE MEDIOPIE(47365)',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '030219',
            '030219',
            'EXPLORACION Y DESCOMPRESION DEL CANAL RAQUIDEO Y RAICES ESPINALES MAS DE DOS SEGMENTOS POR HEMILAMINECTOMIA VIA ENDOSCOPICA',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '345202',
            '345202',
            'PLEURODESIS QUIMICA POR TORACOSCOPIA',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '787901',
            '787901',
            'OSTEOCLASTIA DE FALANGES (UNO O M�S) DE MANO',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '805127',
            '805127',
            'ESCISION DE DISCO INTERVERTEBRAL EN SEGMENTO LUMBAR VIA ANTERIOR O LATERAL ENDOSCOPICA',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '876136',
            '876136',
            'ARTERIOGRAFIA PULMONAR UNILATERAL SELECTIVA',
            --CODAREA,
            'INTERNACION QUIRURGICA',
            9,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '033101',
            '033101',
            'PUNCION LUMBAR (DIAGNOSTICA O TERAPEUTICA)(45385)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '332201',
            '332201',
            'BRONCOSCOPIA FIBRO-OPTICA CON LAVADO BRONQUIAL(1382)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '552604',
            '552604',
            'BIOPSIA DE RI�ON VIA ENDOSCOPICA(46214)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '869400',
            '869400',
            'RETIRO DE SUTURA EN PIEL O TEJIDO CELULAR SUBCUT�NEO SOD(4778)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '895401',
            '895401',
            'MONITORIZACION ELECTROCARDIOGRAFICA (TELEMETRIA)(53676)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '930102',
            '930102',
            'PRUEBA COGNITIVA (CADA UNA)(9909)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '960405',
            '960405',
            'INSERCION DE CANULA JET TRANSTRAQUEAL(10101)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '972400',
            '972400',
            'SUSTITUCION DE DIAFRAGMA VAGINAL SOD(30179)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '563102',
            '563102',
            'URETEROSCOPIA RETROGRADA DIAGNOSTICA(46262)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '181103',
            '181103',
            'BIOPSIA DE OIDO EXTERNO(30112)',
            --CODAREA,
            'PROCEDIMIENTOS',
            3,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '815506',
            '815502',
            'REVISION REEMPLAZO PROTESICO TOTAL EN RODILLA +(4263)',
            --CODAREA,
            'REVISION DE REEMPLAZOS ARTICULARES',
            16,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '020701',
            '020701',
            'EXTRACCION O SUSTITUCION DE DISPOSITIVO DE FIJACION U OSTEOSINTESIS EN CRANEO(53617)',
            --CODAREA,
            'SISTEMA NERVIOSO CENTRAL',
            17,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '034307',
            '034307',
            'RESECCION DE TUMOR RADICULAR EN RELOJ DE ARENA EN CANAL VERTEBRAL EXTRADURAL CON EXTENSION FORAMINAL(45706)',
            --CODAREA,
            'SISTEMA NERVIOSO CENTRAL',
            17,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '040701',
            '040701',
            'RESECCION DE TUMOR PRIMARIO DEL NERVIO OPTICO, POR CRANEOTOMIA SUBFRONTAL(336)',
            --CODAREA,
            'SISTEMA NERVIOSO CENTRAL',
            17,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '044210',
            '044210',
            'DESCOMPRESION DE NERVIO FACIAL INTRATEMPORAL VIA FOSA MEDIA(24553)',
            --CODAREA,
            'SISTEMA NERVIOSO CENTRAL',
            17,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '601T02',
            'S31305',
            'TRASLADO BASICO SIMPLE OTROS MUNICIPIOS(23413)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '601T02',
            'S31306',
            'TRASLADO BASICO REDONDO OTROS MUNICIPIOS(23414)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '601T02',
            'S31307',
            'TRASLADO BASICO SERVICIO INTERMUNICIPAL MAYOR DE 25 KMS HASTA 300 KMS (CADA KILOMETRO)(23415)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '601T02',
            'S32305',
            'TRASLADO SIMPLE EN AMBULANCIA DE COMPLEJIDAD INTERMEDIA EN OTROS MUNICIPIOS(23423)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '601T02',
            'S32306',
            'TRASLADO REDONDO EN AMBULANCIA DE COMPLEJIDAD INTERMEDIA EN OTROS MUNICIPIOS(23424)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '602T02',
            'S33305',
            'TRASLADO MEDICALIZADO SIMPLE OTROS MUNICIPIOS(23437)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '602T02',
            'S33306',
            'TRASLADO MEDICALIZADO REDONDO OTROS MUNICIPIOS(23438)',
            --CODAREA,
            'TRASLADO ASISTENCIAL',
            4,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '487704',
            '487704',
            'DESCENSO RECTAL ABDOMINOPERINEAL POR AGANGLIOSIS VIA ABIERTA(46155)',
            --CODAREA,
            'TRATAMIENTO QUIRURGICO ENFERMEDADES CONGENITAS',
            10,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '547201',
            '547201',
            'CORRECCION PARCIAL DE ONFALOCELE CON DISPOSITIVO(46188)',
            --CODAREA,
            'TRATAMIENTO QUIRURGICO ENFERMEDADES CONGENITAS',
            10,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '039154',
            '039154',
            'MANEJO DIARIO DEL PACIENTE EN UCI POR ESPECIALISTAS(318)',
            --CODAREA,
            'UCI E INTERMEDIOS',
            -- ORDEN
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '5DSB01',
            '5DSB01',
            'DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD BAJA(57244)',
            --CODAREA,
            'URGENCIAS',
            2,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      ),
      (
            '7DS006',
            '7DS006',
            'DERECHOS DE SALA DE PROCEDIMIENTOS ESPECIAL(57251)',
             --CODAREA,
            'URGENCIAS',
            2,
            -- -- --FRECUENCIA_USO: '0',
            -- -- --N_EVENTOS: '0',
            '8018',
            '2022-09-01'
      );