export const fetchServiciosByConsecutivoQuery = (idCentro: number, codigosContratos: string[]) => {
  let contratos = '';

  codigosContratos.map((codigo, i) => {
    if (!i) contratos = `'${codigo}'`;
    else contratos = `${contratos}, '${codigo}'`;
  });

  const filterByCentro = idCentro ? `AND ADNINGRESO.ADNCENATE IN(${idCentro})` : '';

  return `
  SELECT 
      ISNULL(GENSERIPS.SIPCODIGO, 'MEDICAMENTOS') codigoServicio,
      ISNULL(GENSERIPS.SIPNOMBRE, 'MEDICAMENTOS') nombreServicio,
      GENARESER.GASCODIGO codigoArea,
      GENARESER.GASNOMBRE nombreArea, 
	 SUM(SLNSERPRO.SERCANTID * (SLNSERPRO.SERVALENT + SLNSERPRO.SERVALPAC)) totalEjecutado
  FROM SLNFACTUR SLNFACTUR
   INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
   INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
   LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
   INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
   INNER JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
   LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
 WHERE 
	SLNFACTUR.SFATIPDOC = 17
	AND SLNFACTUR.SFADOCANU = 0
	AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
	AND GENDETCON.GDECODIGO IN(${contratos})
	AND SLNORDSER.SOSESTADO = 1
  AND ADNINGRESO.ADNCENATE IS NOT NULL ${filterByCentro}
	AND ADNINGRESO.AINCONSEC = 	@2
	GROUP BY 
	GENARESER.GASCODIGO,
	GENARESER.GASNOMBRE,
	GENSERIPS.SIPCODIGO,
	GENSERIPS.SIPNOMBRE
  ORDER BY 
	TotalEjecutado DESC;`;
};
