import { GcmContexts } from '@common/application/constants';

export const fetchFacturasByContratoQuery = (context: GcmContexts, idCentro: number) => {
  const filterByCentro = idCentro ? `AND I.ADNCENATE IN(${idCentro})` : '';

  let colGCMFICHCON = 'GCMFICHCON';
  let colGCMAGRUPGP = 'GCMAGRUPGP2';
  let colEVENTOS = 'EVENTOS';

  if ([GcmContexts.ALTACENTRO].indexOf(context) >= 0) colGCMFICHCON = 'GCMFICHCON2';
  if ([GcmContexts.AGUACHICA, GcmContexts.VALLEDUPAR].indexOf(context) >= 0)
    colEVENTOS = 'NEVENTOS';
  if ([GcmContexts.AGUACHICA, GcmContexts.VALLEDUPAR].indexOf(context) >= 0)
    colGCMAGRUPGP = 'GCMAGRUPGP';

  const str = `
      SELECT 
I.OID idIngreso,
I.AINCONSEC idConsecutivo,
I.AINFECING fechaIngreso,
I.AINFECEGRE fechaEgreso,
P.GPANOMCOM nombreCompletoPaciente,
CONS.SFAVALCAR totalFacturadoPaciente,
CONS.SFAVALREC valorAnticipoPaciente,
F.OID idAgrupador,
F.GDECODIGO codigoContrato,
F.AGRUPADOR nombreAgrupador,
F.ORDEN ordenAgrupador,
F.${colEVENTOS} eventosContratados,
F.CME CmeContratado,
F.TOTALFACTURADO totalContratado
FROM ADNINGRESO I
INNER JOIN GENPACIEN P ON P.OID = I.GENPACIEN
RIGHT JOIN (
	SELECT  
    TOP 1 WITH TIES
    ISNULL(G.ORDEN, 0) ORDEN,
    ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
    ADNINGRESO.AINCONSEC,
    SLNFACTUR.SFAVALCAR,
    SLNFACTUR.SFAVALREC
    FROM SLNFACTUR
    INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
    INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
    INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
    LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
    LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
    LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
    LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
    LEFT JOIN ${colGCMAGRUPGP} G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS	
    AND G.CONTRATO = @2   
    WHERE 
    SLNFACTUR.SFATIPDOC = 17
    AND SLNFACTUR.SFADOCANU = 0 
    AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
    AND GENDETCON.GDECODIGO IN(@2)
    AND SLNORDSER.SOSESTADO = 1
    GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
    ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
    ) CONS ON CONS.AINCONSEC = I.AINCONSEC 
    RIGHT JOIN ${colGCMFICHCON} F ON F.AGRUPADOR = CONS.AGRUPADOR
    LEFT JOIN HPNDEFCAM H ON H.OID = I.HPNDEFCAM
    WHERE F.GDECODIGO =  @2 AND I.ADNCENATE IS NOT NULL ${filterByCentro};`;

  return str;
};

export const fetchFacturasByContratoQueryCond1 = (context: GcmContexts, idCentro: number) => {
  const filterByCentro = idCentro ? `AND I.ADNCENATE IN(${idCentro})` : '';

  let colGCMFICHCON = 'GCMFICHCON';
  let colGCMAGRUPGP = 'GCMAGRUPGP2';
  let colEVENTOS = 'EVENTOS';

  if ([GcmContexts.ALTACENTRO].indexOf(context) >= 0) colGCMFICHCON = 'GCMFICHCON2';
  if ([GcmContexts.AGUACHICA, GcmContexts.VALLEDUPAR].indexOf(context) >= 0)
    colEVENTOS = 'NEVENTOS';
  if ([GcmContexts.AGUACHICA, GcmContexts.VALLEDUPAR].indexOf(context) >= 0)
    colGCMAGRUPGP = 'GCMAGRUPGP';

  return `
    SELECT 
    I.OID idIngreso,
    I.AINCONSEC idConsecutivo,
    I.AINFECING fechaIngreso,
    I.AINFECEGRE fechaEgreso,
    P.GPANOMCOM nombreCompletoPaciente,
    CONS.SFAVALCAR totalFacturadoPaciente,
    CONS.SFAVALREC valorAnticipoPaciente,
    F.OID idAgrupador,
    F.GDECODIGO codigoContrato,
    F.AGRUPADOR nombreAgrupador,
    F.ORDEN ordenAgrupador,
    F.${colEVENTOS} eventosContratados,
    F.CME CmeContratado,
    F.TOTALFACTURADO totalContratado
    FROM ADNINGRESO I
    INNER JOIN GENPACIEN P ON P.OID = I.GENPACIEN
    RIGHT JOIN (
        SELECT  
        TOP 1 WITH TIES
        ISNULL(G.ORDEN, 0) ORDEN,
        ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
        ADNINGRESO.AINCONSEC,
        SLNFACTUR.SFAVALCAR,
        SLNFACTUR.SFAVALREC
        FROM SLNFACTUR
        INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
        INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
        LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
        LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
        LEFT JOIN ${colGCMAGRUPGP} G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS	
        AND G.CONTRATO = @3  
        WHERE 
        SLNFACTUR.SFATIPDOC = 17
        AND SLNFACTUR.SFADOCANU = 0 
        AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
        AND GENDETCON.GDECODIGO IN(@2)
        AND SLNORDSER.SOSESTADO = 1
        GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
        ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
        ) CONS ON CONS.AINCONSEC = I.AINCONSEC 
        RIGHT JOIN ${colGCMFICHCON} F ON F.AGRUPADOR = CONS.AGRUPADOR
        LEFT JOIN HPNDEFCAM H ON H.OID = I.HPNDEFCAM
        WHERE F.GDECODIGO = @3 AND I.OID IS NOT NULL AND I.ADNCENATE IS NOT NULL ${filterByCentro};
    `;
};
