export const getFacturasPendientesQuery = () => {
  return `
  SELECT
  CONVERT(DATE, ADNEGRESO.ADEFECSAL) AS fecha,
  ADNINGRESO.ADNCENATE idCentro,
  ADNINGRESO.AINESTADO estado,
  SUM(dbo.SLNSERPRO.SERVALPRO * dbo.SLNSERPRO.SERCANTID) AS total
  FROM SLNSERPRO
  INNER JOIN ADNINGRESO ON ADNINGRESO.OID = SLNSERPRO.ADNINGRES1
  INNER JOIN ADNEGRESO ON ADNEGRESO.ADNINGRESO = ADNINGRESO.OID
  INNER JOIN SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
  AND SLNORDSER.SOSESTADO <> 2 AND CONVERT(DATE, ADNEGRESO.ADEFECSAL, 103) BETWEEN @0 AND @1 AND AINESTADO != 1
  GROUP BY 
  ADNEGRESO.ADEFECSAL,
  ADNEGRESO.ADENUMEGR,
  ADNINGRESO.ADNCENATE, 
  ADNINGRESO.AINESTADO`;
};
