export const getFacturacionTercerosQuery = (centroId?: number) => {
  return `
  SELECT
  F.GENTERCER id,
  F.GTRNOMBRE nombre,
  COUNT(F.GENDETCON) totalFacturas,
  ISNULL(SUM(SFATOTFAC),0)-ISNULL(SUM(CASE WHEN CONVERT(DATE, SFAFECANU, 103)
  BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END), 0) total,
  ISNULL(SUM(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) IS NOT NULL THEN SFATOTFAC ELSE NULL END), 0) totalRefacturado,
  COUNT(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) IS NOT NULL THEN SFATOTFAC ELSE NULL END) totalFactRefacturadas
  FROM GCVUSUFACTUR F WHERE SFATIPDOC != 17 AND CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1 
  AND SFACANANU < 1 ${centroId ? 'AND ADNCENATE IN(' + centroId + ')' : ''}
  GROUP BY F.GENTERCER, F.GTRNOMBRE`;
};

export const getFacturacionEntidadesQuery = (centroId: number) => {
  return `
  SELECT
  F.GENDETCON id,
  F.GDENOMBRE nombre,
  COUNT(F.GENDETCON) totalFacturas,
  ISNULL(SUM(SFATOTFAC),0)-ISNULL(SUM(CASE WHEN CONVERT(DATE, SFAFECANU, 103)
  BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END), 0) total,
  ISNULL(SUM(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) < @0  THEN SFATOTFAC ELSE NULL END), 0) totalRefacturado,
  COUNT(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) IS NOT NULL THEN SFATOTFAC ELSE NULL END) totalFactRefacturadas
  FROM GCVUSUFACTUR F WHERE CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1
  AND SFACANANU < 1 AND F.GENTERCER = @2 AND SFATIPDOC != 17
  ${centroId ? 'AND ADNCENATE IN(' + centroId + ')' : ''}
  GROUP BY F.GENDETCON, F.GDENOMBRE`;
};
