export * from './tipo-manual';
export * from './tipo-accesorio';
export * from './tipo-disco-duro-conector';
export * from './tipo-entrada-conector';
export * from './clase-mouse';
export * from './sistema-operativo';
export * from './tipo-disco-duro';
export * from './clase-equipo';
export * from './tipo-mto';
