const fetch = () => {
  return `SELECT C.OID, C.ADNCENATE, C.ADNINGRESO, C.HCANOMBRE,
  I.AINCONSEC, I.AINFECING, P.PACPRINOM, P.PACSEGNOM, P.PACPRIAPE,
  P.PACSEGAPE, M.MUNNOMMUN, B.GEBNOMBRE, D.PACDIRECCION,
  C.HCAAISLAMIEN, C.HCABLOPOR, C.HCACODIGO, C.HCAESTADO,
  C.HCANUMHABI, C.HCAOBSHOS, C.HPNGRUPOS, G.HGRCODIGO,
  G.HGRNOMBRE, C.HPNSUBGRU, S.HSUCODIGO, S.HSUNOMBRE,
  C.HPNTIPOCA, I.GENDETCON, T.GDECODIGO, T.GDENOMBRE,
  T.GENTERCER1, R.TERNUMDOC, R.TERNOMCOM FROM HPNDEFCAM C
  INNER JOIN HPNSUBGRU S ON C.HPNSUBGRU = S.OID
  INNER JOIN HPNGRUPOS G ON C.HPNGRUPOS = G.OID
  LEFT JOIN ADNINGRESO I ON C.ADNINGRESO = I.OID
  LEFT JOIN GENPACIEN P ON I.GENPACIEN = P.OID
  LEFT JOIN GENDETCON T ON I.GENDETCON = T.OID
  LEFT JOIN GENBARRIO B ON P.GENBARRIO = B.OID
  LEFT JOIN GENPACIEND D ON P.GENPACIEND = D.OID
  LEFT JOIN GENMUNICI M ON P.DGNMUNICIPIO = M.OID
  LEFT JOIN GENTERCER R ON T.GENTERCER1 = R.OID
  WHERE C.HCAESTADO != 6 ORDER BY C.ADNINGRESO DESC`;
};

const fetchGasto = () => {
  return `SELECT SUM(SP.SERVALPRO * SP.SERCANTID) SUMA,
  C.ADNINGRESO FROM HPNDEFCAM C
  LEFT JOIN SLNSERPRO SP ON C.ADNINGRESO = SP.ADNINGRES1
  INNER JOIN SLNORDSER O ON SP.SLNORDSER1= O.OID
  WHERE C.HCAESTADO != 6 AND O.SOSESTADO != 2
  GROUP BY C.ADNINGRESO ORDER BY SUMA ASC`;
};

export const camasForHomeQueries = { fetch, fetchGasto };
