import { BadRequestException, Get } from '@nestjs/common';
import { Controller } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { CommonGuards } from '@common/presentation/decorators';
import { BaseSource } from '@common/infrastructure/services';
import { GCM_CONTEXTS } from '@common/domain/types';

@CommonGuards()
@ApiTags('V1 - Resources')
@Controller('v1/aguachica')
export class AguachicaController extends BaseSource {
  @Get()
  async execute() {
    try {
      const ctx = this.auth.context;
      const codigos = ctx === GCM_CONTEXTS.AGUACHICA ? ['22','23','30','31','32'] : GCM_CONTEXTS.VALLEDUPAR ? ['10','11','12','13','14','15'] : [];
      const date = new Date();
      const dateFt = new Date(`${date.toISOString().split('T')[0]}:00:00`);

      const query = `SELECT HCNCONTRDT.HCCFECTUR FECHA_TURNO,
(HCNCONCOTRI.HCPREFIJO + ' ' + CONVERT(VARCHAR(10),HCCTTURNO)) TURNO_ASOCIADO, 
HCNCONCOTRI.HCDESCRIP DESCRIPCION,
CASE HCCESTADO WHEN 0 THEN 'PENDIENTE' WHEN 1 THEN 'ATENDIDO' WHEN 2 THEN 'AUSENTE' WHEN 3 THEN 'FINALIZADO' END ESTADO,
HCNCLAURGTR.HCDESCRIP TRIAGE,
CONVERT(VARCHAR, HCNFECINREG, 108) HORA_INI_TRIAGE,
CONVERT(VARCHAR, HCTFECTRI, 108) HORA_FIN_TRAGE,
DATEDIFF(MINUTE, HCNTRIAGE.HCNFECINREG, HCNTRIAGE.HCTFECTRI) TIEMPO_ELABORACION_TRIAGE,
HCNTRIAGE.GPANOMBRE + ' ' + GPAAPELLI NOMBRE_TRIAGE,
CONVERT(VARCHAR, AINFECING, 108) HORA_ADMISION,
DATEDIFF(MINUTE, HCNTRIAGE.HCTFECTRI, ADNINGRESO.AINFECING) TIEMPO_ESPERA_TRIAGE_ADMISION,
AINCONSEC INGRESO,
GENPACIEN.GPANOMCOM PACIENTE,
CONVERT(VARCHAR, HCTCFECCONF, 108) AS HORA_INI_HC,
DATEDIFF (MINUTE, AINFECING, HCTCFECCONF)  TIEMPO_ESPERA_ADMISION_ATENCION_INI,
DATEDIFF (MINUTE, HCCFECTUR, HCTCFECCONF) MINUTOS_DESDE_TURNO_A_ATENCION_INI,
DATEDIFF (MINUTE, HCTFECTRI, HCTCFECCONF) MINUTOS_DESDE_CIERRE_TRIAGE__ATENCION_INI,
(SELECT TOP(1) HCNTIPHIS.HCCODIGO FROM HCNFOLIO INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID WHERE HCNFOLIO.ADNINGRESO=ADNINGRESO.OID  ) PRIMER_FOLIO_TH,
(SELECT GMENOMCOM FROM (SELECT GMENOMCOM,ROW_NUMBER() OVER(ORDER BY HCNUMFOL) ROWNUM  FROM HCNFOLIO INNER JOIN GENMEDICO ON HCNFOLIO.GENMEDICO =GENMEDICO.OID WHERE HCNFOLIO.ADNINGRESO=ADNINGRESO.OID  )T WHERE T. ROWNUM = 1 ) MEDICO_PRIMER_FOLIO
FROM HCNCONTRDT
INNER JOIN HCNCONCOTRI ON HCNCONCOTRI.OID = HCNCONTRDT.HCNCONCOTRI
LEFT JOIN HCNTRIAGE ON HCNCONTRDT.OID = HCNTRIAGE.HCNCONTRDT 
LEFT JOIN ADNINGRESO ON ADNINGRESO.OID = HCNTRIAGE.ADNINGRESO
LEFT JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
LEFT JOIN HCNCLAURGTR ON HCNTRIAGE.HCNCLAURGTR = HCNCLAURGTR.OID
WHERE (HCNCONCOTRI IN (${codigos}))
AND HCNCONTRDT.HCCFECTUR >= @0
ORDER BY HCCFECTUR DESC`;

      const results = await this.conn.query(query, [dateFt]);

      return results;
    } catch (error) {
      throw new BadRequestException(error.message);
    }
  }
}
