export const getPacientesRevaloracion = () => {
  return `SELECT 
 AINCONSEC,
 genpacien.pacnumdoc, 
 GENPACIEN.GPANOMCOM,
 HPNDEFCAM.HCACODIGO,
 HPNSUBGRU.HSUNOMBRE ,
 AINFECING AS FECHA_INGRESO,
 DATEDIFF(DAY,AINFECING,GETDATE()) AS DIAS_URG,
 DATEDIFF(hour,AINFECING,GETDATE()) AS horas_URG,
 --ADNINGRESO.ADNEGRESO,
 HCNFOLIO.HCNUMFOL,
 HCCM09N71 as REVALORACION,
 (select top(1) HCFECFOL from hcnfolio where hcnfolio.ADNINGRESO=adningreso.oid and HCNTIPHIS in ('1','2','7','18','50')) as PRIMER_FOLIO_FECHA,
 (select top(1) HCNTIPHIS.HCCODIGO from hcnfolio INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID where hcnfolio.ADNINGRESO=adningreso.oid  and HCNTIPHIS in ('1','2','7','18','50')) AS PRIMER_FOLIO_TH,
 (SELECT HCFECFOL FROM (select HCFECFOL,ROW_NUMBER() OVER(ORDER BY HCNUMFOL) ROWNUM  from hcnfolio where hcnfolio.ADNINGRESO=adningreso.oid  and HCNTIPHIS in ('1','2','7','18','50'))T WHERE T. ROWNUM = 2 ) AS SEGUNDO_FOLIO_FECHA,
 (SELECT HCCODIGO FROM (select  HCNTIPHIS.HCCODIGO,ROW_NUMBER() OVER(ORDER BY HCNUMFOL) ROWNUM from hcnfolio INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID where hcnfolio.ADNINGRESO=adningreso.oid  and HCNTIPHIS in ('1','2','7','18','50'))T WHERE T. ROWNUM = 2 )AS SEGUNDO_FOLIO_TH,
 (SELECT HCFECFOL FROM (select HCFECFOL,ROW_NUMBER() OVER(ORDER BY HCNUMFOL) ROWNUM  from hcnfolio where hcnfolio.ADNINGRESO=adningreso.oid  and HCNTIPHIS in ('1','2','7','18','50'))T WHERE T. ROWNUM = 3 ) AS tercer_FOLIO_FECHA,
 (SELECT HCCODIGO FROM (select  HCNTIPHIS.HCCODIGO,ROW_NUMBER() OVER(ORDER BY HCNUMFOL) ROWNUM from hcnfolio INNER JOIN HCNTIPHIS ON HCNFOLIO.HCNTIPHIS = HCNTIPHIS.OID where hcnfolio.ADNINGRESO=adningreso.oid  and HCNTIPHIS in ('1','2','7','18','50'))T WHERE T. ROWNUM = 3 )AS tercer_FOLIO_TH
 
 FROM ADNINGRESO
 inner join GENPACIEN on genpacien.OID = ADNINGRESO.GENPACIEN
 INNER JOIN HPNDEFCAM ON HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
 INNER JOIN HPNGRUPOS ON HPNGRUPOS.OID = HPNDEFCAM.HPNGRUPOS
 inner join HPNSUBGRU on HPNSUBGRU.OID= HPNDEFCAM.HPNSUBGRU
 inner join HCNFOLIO on hcnfolio.ADNINGRESO= adningreso.OID
 INNER JOIN HCMURG001 ON HCMURG001.HCNFOLIO = HCNFOLIO.OID
 WHERE AINESTADO IN (0,3)
 AND ADNINGRESO.ADNCENATE='2'
 and ADNEGRESO is null
 and hcnfolio.HCNTIPHIS='1'
 and HPNGRUPOS.oid in (20,26,37,31,38)
 order by 6 DESC`;
};
