export const fetchServiciosByConsecutivoQuery = (codigosContratos: string[]) => {
  let contratos = '';

  codigosContratos.map((codigo, i) => {
    if (!i) contratos = `'${codigo}'`;
    else contratos = `${contratos}, '${codigo}'`;
  });

  return `
      SELECT 
      ISNULL(GENSERIPS.SIPCODCUP, 'MEDICAMENTOS') codigo,
      ISNULL(GENSERIPS.SIPNOMBRE, 'MEDICAMENTOS') nombre,
    SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) totalCosto
   FROM HPNESTANC H
    INNER JOIN HPNDEFCAM E ON H.HPNDEFCAM = E.OID
    INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = E.ADNINGRESO
    INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
   LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.ADNINGRES1 = ADNINGRESO.OID
    LEFT JOIN SLNSERPRO ON SLNSERPRO.SLNORDSER1 = SLNORDSER.OID
   LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
   LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
    LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
  WHERE 
   ADNINGRESO.AINESTADO = 0 
   AND SLNORDSER.SOSESTADO <> 2
   AND E.HCAESTADO = 2
   AND H.HESFECSAL IS NULL
   AND GENDETCON.GDECODIGO IN (${contratos})
   AND ADNINGRESO.AINCONSEC = @0
 GROUP BY 
   GENSERIPS.SIPCODCUP,
   GENSERIPS.SIPNOMBRE
   ORDER BY totalCosto DESC;`;
};
