export const fetchPacientesByContratoQuery = (idCentro: number) => {
  const filterByCentro = idCentro ? `AND I.ADNCENATE IN(${idCentro})` : '';

  return `
  SELECT 
    GENDETCON.GDECODIGO codigoContrato,
        ADNINGRESO.AINCONSEC idConsecutivo,
        GENPACIEN.PACNUMDOC documentoPaciente,
        GENPACIEN.GPANOMCOM nombrePaciente,
        ADNINGRESO.AINFECING fechaIngreso,
         DateDiff(DAY, ADNINGRESO.AINFECING, GetDate()) As diasEstancia,
        CASE ADNINGRESO.AINURGCON
          WHEN -1 THEN 'NINGUNO'
          WHEN 0 THEN 'URGENCIAS'
          WHEN 1 THEN 'CONSULTA EXTERNA'
          WHEN 2 THEN 'NACIDO EN LA IPS'
          WHEN 3 THEN 'REMITIDO'
          WHEN 4 THEN 'HOSPITALIZACION DE URGENCIAS'
          WHEN 5 THEN 'HOSPITALIZACION'
          WHEN 6 THEN 'IMAGENES'
          WHEN 7 THEN 'LABORATORIO'
          WHEN 8 THEN 'URGENCIA GINECOLOGIA'
          WHEN 9 THEN 'QUIROFANO'
          WHEN 10 THEN 'CIRUGIA AMBULATORIA'
          WHEN 11 THEN 'CIRUGIA PROGRAMADA'
          WHEN 12 THEN 'UCI NEONATAL'
          WHEN 13 THEN 'UCI ADULTO'
          END AS TipoIngreso,
         HPNDEFCAM.HCACODIGO codigoCama,
        HPNDEFCAM.HCANOMBRE nombreCama,
        SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) AS totalEjecutado
        FROM HPNESTANC
          INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
          INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
          INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
          INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
          LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        WHERE GENDETCON.GDECODIGO IN (@2)
          AND SLNORDSER.SOSESTADO <> 2
          AND ADNINGRESO.AINESTADO = 0
          AND HPNDEFCAM.HCAESTADO = 2
          AND HPNESTANC.HESFECSAL IS NULL
      AND ADNINGRESO.AINFECFAC IS NULL
      AND ADNINGRESO.ADNCENATE IS NOT NULL ${filterByCentro}
        GROUP BY 
        GENDETCON.GDECODIGO,
          ADNINGRESO.AINCONSEC, 
          ADNINGRESO.AINURGCON,
          GENPACIEN.PACNUMDOC,
          GENPACIEN.GPANOMCOM,
          HPNDEFCAM.HCACODIGO,
          HPNDEFCAM.HCANOMBRE,
          ADNINGRESO.AINFECING
          ORDER BY TotalEjecutado DESC;`;
};
