import { GcmContexts } from '@common/application/constants';

export const fetchLargasEstanciasByContratoQuery = (
  context: GcmContexts,
  idCentro: number,
  codigosContratos: string[]
) => {
  let contratos = '';

  let colGCMAGRUPGP = 'GCMAGRUPGP';

  if ([GcmContexts.ALTACENTRO].indexOf(context) >= 0) colGCMAGRUPGP = 'GCMAGRUPGP2';

  codigosContratos.map((codigo, i) => {
    if (!i) contratos = `'${codigo}'`;
    else contratos = `${contratos}, '${codigo}'`;
  });

  const filterByCentro = idCentro ? `AND ADNINGRESO.ADNCENATE IN(${idCentro})` : '';

  return `
      SELECT
CONS.Agrupador nombreAgrupador,
CONS.ORDEN prioridad,
COUNT(*) cantidadPacientes
FROM ADNINGRESO
RIGHT JOIN 
(SELECT TOP 1 WITH TIES
	ISNULL(G.ORDEN, 0) ORDEN,
	ISNULL(G.AGRUPADOR, 'EVENTOS')AS Agrupador,
	ADNINGRESO.AINCONSEC
	FROM SLNFACTUR
		INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        INNER JOIN GENPACIEN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
        INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
        INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
        LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
        LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
        LEFT JOIN ${colGCMAGRUPGP} G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS
		AND G.CONTRATO IN (${contratos})
			WHERE 
			SLNFACTUR.SFATIPDOC = 17
            AND SLNFACTUR.SFADOCANU = 0
            AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
            AND GENDETCON.GDECODIGO IN (${contratos})
            AND ADNINGRESO.ADNCENATE IS NOT NULL ${filterByCentro}
            AND SLNORDSER.SOSESTADO = 1
            GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC
            ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC))  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
            LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
            WHERE DateDiff(DAY, ADNINGRESO.AINFECING, ADNINGRESO.AINFECEGRE) >= 10
            GROUP BY CONS.Agrupador, CONS.ORDEN
			order by cons.ORDEN DESC;`;
};
