import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity('EKINNRHSERVICIO')
export class RhServicioOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'NOMBRE', length: 120 }) nombre: string; @Column({ name: 'DESCRIPCION', length: 500, nullable: true }) descripcion?: string; @Column({ name: 'ACTIVO', default: true }) activo: boolean; @Column({ name: 'FECHACREA' }) fechaCreacion: Date; @Column({ name: 'FECHAACT' }) fechaActualizacion: Date; }
@Entity('EKINNRHHABITACION')
export class RhHabitacionOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'NUMERO', length: 40 }) numero: string; @Column({ name: 'NOMBRE', length: 120, nullable: true }) nombre?: string; @Column({ name: 'EKINNRHSERVICIO' }) servicioId: number; @Column({ name: 'ACTIVO', default: true }) activo: boolean; @Column({ name: 'FECHACREA' }) fechaCreacion: Date; @Column({ name: 'FECHAACT' }) fechaActualizacion: Date; }
@Entity('EKINNRHRONDA')
export class RhRondaOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'ADNCENATE' }) sedeId: number; @Column({ name: 'SEMANA' }) semana: number; @Column({ name: 'ANIO' }) anio: number; @Column({ name: 'FECHAINICIO' }) fechaInicio: Date; @Column({ name: 'FECHAFINAL', nullable: true }) fechaFinalizacion?: Date; @Column({ name: 'RESPONSABLEID' }) responsableId: number; @Column({ name: 'RESPONSABLENOMBRE', length: 180 }) responsableNombre: string; @Column({ name: 'ESTADO', length: 20 }) estado: 'EN_PROGRESO' | 'COMPLETADA'; @Column({ name: 'TOTALHABITACIONES' }) totalHabitaciones: number; @Column({ name: 'HABITACIONESREGISTRADAS', default: 0 }) habitacionesRegistradas: number; @Column({ name: 'OBSERVACIONES', length: 1000, nullable: true }) observacionesGenerales?: string; @Column({ name: 'CREADOPOR' }) creadoPor: number; @Column({ name: 'FECHACREA' }) fechaCreacion: Date; @Column({ name: 'FECHAACT' }) fechaActualizacion: Date; }
@Entity('EKINNRHREGISTRO')
export class RhRegistroHabitacionOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'EKINNRHRONDA' }) rondaId: number; @Column({ name: 'EKINNRHHABITACION' }) habitacionId: number; @Column({ name: 'EKINNRHSERVICIO' }) servicioId: number; @Column({ name: 'OBSERVACIONES', length: 1000, nullable: true }) observaciones?: string; @Column({ name: 'FECHAREGISTRO' }) fechaRegistro: Date; @Column({ name: 'REGISTRADOPOR' }) registradoPor: number; }
@Entity('EKINNRHREGISTROEQUIPO')
export class RhRegistroEquipoOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'EKINNRHREGISTRO' }) registroHabitacionId: number; @Column({ name: 'TIPOEQUIPO', length: 40 }) tipoEquipo: string; @Column({ name: 'ESTADO', length: 20 }) estado: string; @Column({ name: 'OBSERVACION', length: 500, nullable: true }) observacion?: string; }
@Entity('EKINNRHALERTA')
export class RhAlertaOrm { @PrimaryGeneratedColumn({ name: 'OID' }) id: number; @Column({ name: 'EKINNRHRONDA' }) rondaId: number; @Column({ name: 'EKINNRHHABITACION' }) habitacionId: number; @Column({ name: 'TIPOEQUIPO', length: 40 }) tipoEquipo: string; @Column({ name: 'ESTADOANTERIOR', length: 20 }) estadoAnterior: string; @Column({ name: 'ESTADOACTUAL', length: 20 }) estadoActual: string; @Column({ name: 'TIPOALERTA', length: 30 }) tipoAlerta: string; @Column({ name: 'RESUELTA', default: false }) resuelta: boolean; @Column({ name: 'FECHAGENERACION' }) fechaGeneracion: Date; @Column({ name: 'FECHARESOLUCION', nullable: true }) fechaResolucion?: Date; @Column({ name: 'RESUELTAPOR', nullable: true }) resueltaPor?: number; @Column({ name: 'OBSRESOLUCION', length: 1000, nullable: true }) observacionResolucion?: string; }
export const ORM_INN_RONDAS_HABITACIONES_ENTITIES = [RhServicioOrm, RhHabitacionOrm, RhRondaOrm, RhRegistroHabitacionOrm, RhRegistroEquipoOrm, RhAlertaOrm];
