import { HPN_AUTHORITIES } from '@authorities/hospitalizacion';
import { ADMIN_AUTHORITY } from '@authorities/principal';

export const DAY_IN_MS = 86400000;

export const DIE_AUTHORITIES = {
  ADMINISTRADOR: ADMIN_AUTHORITY,
  REGISTRAR: HPN_AUTHORITIES.DIETAS.REGISTRAR,
  REGISTRAR_EXTRATIME: HPN_AUTHORITIES.DIETAS.REGISTRAR_IGNORA_JORNADA,
  EXTRA_CONFIG: HPN_AUTHORITIES.DIETAS.ASIGNAR_EXTRAORDINARIAS,
  VER_JORNADA: HPN_AUTHORITIES.DIETAS.VER_JORNADA,
  ENVIAR: HPN_AUTHORITIES.DIETAS.FUNCIONES_PROVEEDOR,
  RECIBIR: HPN_AUTHORITIES.DIETAS.RECIBIR_EN_DESTINO,
  GESTIONAR_ENTREGA: HPN_AUTHORITIES.DIETAS.VER_JORNADA,
  ELIMINAR: ADMIN_AUTHORITY,
  REPORTAR_NO_RECIBIDAS: HPN_AUTHORITIES.DIETAS.REPORTAR_FALTANTES,
  FACTURACION: HPN_AUTHORITIES.DIETAS.VER_FACTURACION,
};
