export const boletaQuirurgicaQuery = () => {
  return `
  SELECT 
          GCMCIRDERINTRAHOSP.INGRESO,
          GCMCIRDERINTRAHOSP.ESTADO AS ESTADO_REGISTRO,
          HPNDEFCAM.HCACODIGO,
          LEFT(HPNSUBGRU.HSUNOMBRE,40) AS SERVICIO,
          ISNULL(GCMCIRDERINTRAHOSPPRO.PROGRAMADA,'') AS ESTADO_CIRUGIA, 
          LEFT((SELECT top(1) GENSERIPS.SIPDESCUP FROM HCNSOLPQX INNER JOIN ADNINGRESO ON HCNSOLPQX.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENSERIPS ON HCNSOLPQX.GENSERIPS = GENSERIPS.OID inner join hcnfolio on hcnfolio.oid= HCNSOLPQX.hcnfolio WHERE AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO and HCNUMFOL=GCMCIRDERINTRAHOSP.FOLIO ORDER BY HCNSOLPQX.OID ASC ),60)AS PROCEDIMIENTO , 
          CASE GCMCIRDERINTRAHOSPAUD.PENDIENTE7 WHEN 'SI' THEN 'X' ELSE '' END AS AUTORIZACIONES, 
          case GCMCIRDERINTRAHOSPGESTORQ.estado_autorizacion WHEN 'SI' THEN 'X' ELSE '' END AS GESTOR_QX, 
          case GCMCIRDERINTRAHOSPGES.estado2_MAOS WHEN 'SI' THEN 'X' ELSE '' END AS MAOS, 
          case GCMCIRDERINTRAHOSPPRO.ESTADO_PROG WHEN 'SI' THEN 'X' ELSE '' END AS PROGRAMACION, 
          CASE WHEN GCMCIRDERINTRAHOSPAUD.PENDIENTE7='si' AND GCMCIRDERINTRAHOSPGESTORQ.estado_autorizacion ='SI' AND GCMCIRDERINTRAHOSPGES.estado2_MAOS ='SI' AND GCMCIRDERINTRAHOSPPRO.ESTADO_PROG='SI' THEN 'COMPLETA' ELSE '' END AS ESTADO_GESTION, 
          GCMCIRDERINTRAHOSP.ESPECIALIDAD, 
          GCMCIRDERINTRAHOSP.DOCUMENTO, 
          GCMCIRDERINTRAHOSP.NOM_PAC, 
          CONVERT(varchar,GCMCIRDERINTRAHOSP.FEC_INGRESO,23) as FEC_INGRESO, 
          CONVERT(varchar,GCMCIRDERINTRAHOSP.FEC_SOLICITUD,23)AS FEC_SOLICITUD, 
          GCMCIRDERINTRAHOSP.FOLIO, 
          GCMCIRDERINTRAHOSP.NOM_SEDE, 
          GCMCIRDERINTRAHOSP.NOM_MEDICO, 
          GCMCIRDERINTRAHOSP.COD_EPS, 
          GCMCIRDERINTRAHOSP.NOMBRE_EPS, 
          GCMCIRDERINTRAHOSP.DIANOMBRE,
          GCMCIRDERINTRAHOSPPRO.PROGRAMADA, 
          case DATEPART(yyyy,GCMCIRDERINTRAHOSPPRO.fecha_programacion) when 1900 then '' else FECHA_PROGRAMACION end as FECHA_PROGRAMACION 
        FROM GCMCIRDERINTRAHOSP 
        LEFT JOIN GCMCIRDERINTRAHOSPPRO ON GCMCIRDERINTRAHOSP.INGRESO = GCMCIRDERINTRAHOSPPRO.INGRESO and GCMCIRDERINTRAHOSP.folio = GCMCIRDERINTRAHOSPPRO.folio 
        LEFT OUTER JOIN GCMCIRDERINTRAHOSPAUD ON GCMCIRDERINTRAHOSP.INGRESO = GCMCIRDERINTRAHOSPAUD.INGRESO and GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPAUD.folio 
        left join GCMCIRDERINTRAHOSPGESTORQ on GCMCIRDERINTRAHOSPGESTORQ.INGRESO = GCMCIRDERINTRAHOSP.INGRESO and GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPGESTORQ.folio 
        left join GCMCIRDERINTRAHOSPGES on GCMCIRDERINTRAHOSPGES.INGRESO= GCMCIRDERINTRAHOSP.INGRESO and GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPGES.folio 
        inner join ADNINGRESO on adningreso.AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO 
        left join HPNDEFCAM on HPNDEFCAM.oid = ADNINGRESO.HPNDEFCAM 
        left join HPNSUBGRU on HPNSUBGRU.oid= HPNDEFCAM.HPNSUBGRU 
        where FEC_INGRESO >= '2023-06-30' and ainestado in (0,3) 
        AND FEC_SOLICITUD >= '2018-02-20' and GCMCIRDERINTRAHOSP.ESTADO<>'CERRADO' 
        and adningreso.oid not in (select ADNINGRESO from ADNEGRESO where ADEFECSAL>='2024-12-31') 
        order by fec_solicitud,documento
    `;
};
