export const boletaQuirurgicaPacienteQuery = () => `
  SELECT GCMCIRDERINTRAHOSP.*,
    CASE ADNINGRESO.AINESTADO
      WHEN 0 THEN 'Ingreso Abierto'
      WHEN 3 THEN 'Ingreso Bloqueado'
      WHEN 1 THEN 'Ingreso Facturado'
    END AS ESTADO_INGRESO,
    ADNEGRESO.ADEFECSAL AS FECHA_EGRESO,
    DATOS_BASICOS_PACIENTES.*
  FROM GCMCIRDERINTRAHOSP
  INNER JOIN ADNINGRESO ON ADNINGRESO.AINCONSEC = GCMCIRDERINTRAHOSP.INGRESO
  LEFT JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
  LEFT JOIN DATOS_BASICOS_PACIENTES ON DATOS_BASICOS_PACIENTES.PACNUMDOC = GENPACIEN.PACNUMDOC
  LEFT JOIN ADNEGRESO ON ADNEGRESO.ADNINGRESO = ADNINGRESO.OID
  WHERE GCMCIRDERINTRAHOSP.INGRESO = @0 AND GCMCIRDERINTRAHOSP.FOLIO = @1
`;
