export const boletaQuirurgicaNuevaQuery = () => {
  return `
  Select distinct
GCMCIRDERINTRAHOSP.INGRESO,
GCMCIRDERINTRAHOSP.ESTADO As ESTADO_REGISTRO,
HPNDEFCAM.HCACODIGO,
GCMCIRDERINTRAHOSP.DOCUMENTO,
GCMCIRDERINTRAHOSP.NOM_PAC,
Convert(varchar, GCMCIRDERINTRAHOSP.FEC_SOLICITUD, 23)As FEC_SOLICITUD,GCMCIRDERINTRAHOSP.FOLIO,
Left(CONCAT(
Left((SELECT top(1) GENSERIPS.SIPDESCUP FROM HCNSOLPQX INNER JOIN ADNINGRESO ON HCNSOLPQX.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENSERIPS ON HCNSOLPQX.GENSERIPS = GENSERIPS.OID inner join hcnfolio on hcnfolio.oid= HCNSOLPQX.hcnfolio WHERE AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO And HCNUMFOL=GCMCIRDERINTRAHOSP.FOLIO ORDER BY HCNSOLPQX.OID ASC ),60),
Left((SELECT top(1) GENSERIPS.SIPDESCUP FROM HCNSOLPNQX INNER JOIN ADNINGRESO On HCNSOLPNQX.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENSERIPS On HCNSOLPNQX.GENSERIPS = GENSERIPS.OID inner join hcnfolio On hcnfolio.oid= HCNSOLPNQX.hcnfolio WHERE AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO And HCNUMFOL=GCMCIRDERINTRAHOSP.FOLIO ORDER BY HCNSOLPNQX.OID ASC ), 60),
Left((SELECT top(1) GENSERIPS.SIPDESCUP FROM HCNSOLEXA INNER JOIN ADNINGRESO On HCNSOLEXA.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENSERIPS On HCNSOLEXA.GENSERIPS = GENSERIPS.OID inner join hcnfolio On hcnfolio.oid= HCNSOLEXA.hcnfolio WHERE AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO And HCNUMFOL=GCMCIRDERINTRAHOSP.FOLIO ORDER BY HCNSOLEXA.OID ASC ), 60)
),80)AS PROCEDIMIENTO ,
Case GCMCIRDERINTRAHOSPAUD.PENDIENTE7 When 'SI' THEN GCMCIRDERINTRAHOSPAUD.AUTORIZADO ELSE isnull(GCMCIRDERINTRAHOSPAUD.AUTORIZADO,'SIN GESTIONAR') END AS AUTORIZADO,
Case GCMCIRDERINTRAHOSPGESTORQ.estado_autorizacion When 'SI' THEN 'FINALIZADO' ELSE 'EN GESTION' END AS GESTOR_QX,
Case GCMCIRDERINTRAHOSPGES.estado2_MAOS When 'SI' THEN CONCAT('FINALIZADO ',ISNULL(ESTADO_MAOS,'SIN GESTIONAR')) ELSE ISNULL(ESTADO_MAOS,'SIN GESTIONAR') END AS MAOS,
Case GCMCIRDERINTRAHOSPPRO.ESTADO_PROG When 'SI' THEN ISNULL(PROGRAMADA,'PROGRAMADA') ELSE ISNULL(PROGRAMADA,'SIN GESTIONAR') END AS PROGRAMACION,
GCMCIRDERINTRAHOSP.ESPECIALIDAD,
Convert(varchar, GCMCIRDERINTRAHOSP.FEC_INGRESO, 23) As FEC_INGRESO,  
ACANOMBRE AS NOMBRE_SEDE,--GCMCIRDERINTRAHOSP.NOM_SEDE,
GCMCIRDERINTRAHOSP.NOM_MEDICO,
Left(HPNSUBGRU.HSUNOMBRE, 40) As SERVICIO, GCMCIRDERINTRAHOSP.TIPO, case ainestado when 0 then 'Ingreso Abierto' when 3 then 'Ingreso Bloqueado' when 1 then 'Ingreso Facturado' end As ESTADO_INGRESO,
DATEDIFF(day,GCMCIRDERINTRAHOSP.FEC_SOLICITUD,GETDATE()) as DIAS
From GCMCIRDERINTRAHOSP 
Left Join GCMCIRDERINTRAHOSPPRO ON GCMCIRDERINTRAHOSP.INGRESO = GCMCIRDERINTRAHOSPPRO.INGRESO And GCMCIRDERINTRAHOSP.folio = GCMCIRDERINTRAHOSPPRO.folio
Left OUTER JOIN GCMCIRDERINTRAHOSPAUD ON GCMCIRDERINTRAHOSP.INGRESO = GCMCIRDERINTRAHOSPAUD.INGRESO And GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPAUD.folio
Left Join GCMCIRDERINTRAHOSPGESTORQ on GCMCIRDERINTRAHOSPGESTORQ.INGRESO = GCMCIRDERINTRAHOSP.INGRESO And GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPGESTORQ.folio
Left Join GCMCIRDERINTRAHOSPGES on GCMCIRDERINTRAHOSPGES.INGRESO= GCMCIRDERINTRAHOSP.INGRESO And GCMCIRDERINTRAHOSP.folio =GCMCIRDERINTRAHOSPGES.folio
inner Join ADNINGRESO on adningreso.AINCONSEC=GCMCIRDERINTRAHOSP.INGRESO
INNER JOIN ADNCENATE ON ADNCENATE.OID=ADNINGRESO.ADNCENATE
Left Join HPNDEFCAM on HPNDEFCAM.oid = ADNINGRESO.HPNDEFCAM
Left Join HPNSUBGRU on HPNSUBGRU.oid= HPNDEFCAM.HPNSUBGRU
WHERE GCMCIRDERINTRAHOSP.FEC_SOLICITUD >= DATEADD(DAY, -30, GETDATE())
  `;
};
