export const cirugiasRealizadasQuery = () => `
  SELECT
    HCNFOLIO.HCNUMFOL AS FOLIO,
    HCNFOLIO.HCFECFOL AS FECHA_OPERACION,
    GENSERIPS.SIPNOMBRE,
    HCMDESCQX.HCCM02N10 AS PROCEDIMIENTO,
    HCMDESCQX.DESCHCCM22N15 AS CIRUGANO,
    HCMDESCQX.HCCM03N13 AS DESCRIPCION,
    'PQX' AS ORIGEN
  FROM HCMDESCQX
  INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCMDESCQX.HCNFOLIO
  INNER JOIN ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
  LEFT JOIN HCNQXEPAC ON HCNFOLIO.OID = HCNQXEPAC.HCNFOLIO
  LEFT JOIN GENSERIPS ON GENSERIPS.OID = HCNQXEPAC.GENSERIPS
  WHERE ADNINGRESO.AINCONSEC = @0

  UNION ALL

  SELECT
    HCNFOLIO.HCNUMFOL AS FOLIO,
    HCNFOLIO.HCFECFOL AS FECHA_OPERACION,
    GENSERIPS.SIPNOMBRE,
    HCMINFINT.DESCHCCM22N15 AS PROCEDIMIENTO,
    HCMINFINT.DESCHCCM22N36 AS CIRUGANO,
    HCMINFINT.HCCM03N02 AS DESCRIPCION,
    'PROCEDIMIENTO INTERVENCIONISTA' AS ORIGEN
  FROM HCMINFINT
  INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCMINFINT.HCNFOLIO
  INNER JOIN ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
  LEFT JOIN HCNQXEPAC ON HCNFOLIO.OID = HCNQXEPAC.HCNFOLIO
  LEFT JOIN GENSERIPS ON GENSERIPS.OID = HCNQXEPAC.GENSERIPS
  WHERE ADNINGRESO.AINCONSEC = @0

  UNION ALL

  SELECT
    HCNFOLIO.HCNUMFOL AS FOLIO,
    HCNFOLIO.HCFECFOL AS FECHA_OPERACION,
    GENSERIPS.SIPNOMBRE,
    '' AS PROCEDIMIENTO,
    HCMDEQUCA.DESCHCCM22N07 AS CIRUGANO,
    HCMDEQUCA.HCCM03N14 AS DESCRIPCION,
    'PQX CARDIOVASCULAR' AS ORIGEN
  FROM HCMDEQUCA
  INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCMDEQUCA.HCNFOLIO
  INNER JOIN ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
  LEFT JOIN HCNQXEPAC ON HCNFOLIO.OID = HCNQXEPAC.HCNFOLIO
  LEFT JOIN GENSERIPS ON GENSERIPS.OID = HCNQXEPAC.GENSERIPS
  WHERE ADNINGRESO.AINCONSEC = @0

  ORDER BY FOLIO DESC
`;
