export const cirugiasRealizadasQuery = (ingreso: number) => `
    SELECT HCNFOLIO.HCNUMFOL AS FOLIO, HCFECFOL as FECHA_OPERACION,GENSERIPS.SIPNOMBRE,  HCCM02N10 AS PROCEDIMIENTO, DESCHCCM22N15 AS CIRUGANO,hccm03n13 as DESCRIPCION,'PQX'  from HCMDESCQX 
 INNER join HCNFOLIO on HCNFOLIO.oid= HCMDESCQX.HCNFOLIO
 INNER join adningreso on hcnfolio.adningreso=adningreso.oid
 LEFT JOIN HCNQXEPAC ON HCNFOLIO.OID=HCNQXEPAC.HCNFOLIO
 LEFT JOIN GENSERIPS ON GENSERIPS.OID=HCNQXEPAC.GENSERIPS
WHERE ainconsec= ${ingreso}
 UNION all
Select HCNFOLIO.HCNUMFOL As FOLIO, 
HCFECFOL As FECHA_OPERACION,
GENSERIPS.SIPNOMBRE,  
DEScHCCM22N15 As PROCEDIMIENTO, 
DESCHCCM22N36 As CIRUGANO,
HCCM03N02 As DESCRIPCION,'OTRO'  
From HCMINFINT 
 INNER Join HCNFOLIO on HCNFOLIO.oid= HCMINFINT.HCNFOLIO
 INNER Join adningreso on hcnfolio.adningreso=adningreso.oid
 LEFT Join HCNQXEPAC ON HCNFOLIO.OID=HCNQXEPAC.HCNFOLIO
 LEFT Join GENSERIPS ON GENSERIPS.OID=HCNQXEPAC.GENSERIPS
WHERE ainconsec= ${ingreso}  order by HCNFOLIO.HCNUMFOL desc
`;
