export const cupsEjecutadosQuery = () => `
  SELECT HCNQXEPAC.OID, HCNFOLIO.HCNUMFOL, HCNQXEPAC.GENSERIPS,
         GENSERIPS.SIPCODIGO, GENSERIPS.SIPNOMBRE
  FROM HCNQXEPAC
  INNER JOIN GENSERIPS ON GENSERIPS.OID = HCNQXEPAC.GENSERIPS
  INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCNQXEPAC.HCNFOLIO
  INNER JOIN ADNINGRESO ON ADNINGRESO.OID = HCNFOLIO.ADNINGRESO
  WHERE ADNINGRESO.AINCONSEC = @0 AND HCNFOLIO.HCNUMFOL = @1
`;

export const actualizarCupEjecutadoQuery = () => `
  UPDATE HCNQXEPAC SET GENSERIPS = @0
  FROM HCNQXEPAC
  INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCNQXEPAC.HCNFOLIO
  INNER JOIN ADNINGRESO ON ADNINGRESO.OID = HCNFOLIO.ADNINGRESO
  WHERE HCNQXEPAC.OID = @1
    AND ADNINGRESO.AINCONSEC = @2
    AND HCNFOLIO.HCNUMFOL = @3
    AND EXISTS (SELECT 1 FROM GENSERIPS WHERE OID = @0);
  SELECT @@ROWCOUNT AS afectados;
`;
