export const getInfoProcedimientoQuery = () => `
    SELECT 
        ADNINGRESO.AINCONSEC AS INGRESO, 
        HCNSOLPQX.OID, 
        GENSERIPS.SIPCODIGO AS CODIGO_INTERNO, 
        GENSERIPS.SIPCODCUP AS CODIGO_CUPS, 
        GENSERIPS.SIPDESCUP AS DESCRIPCION,
        HCSOBSERV AS OBSERVACION,
        HCSCANTI AS CANTIDAD,
        HCNREQUERI AS REQUERIMIENTO,
        HCSFECSOL AS FECHA_SOLICITUD, 
        CASE HCSESTADO 
            WHEN 0 THEN 'URGENTE' 
            WHEN 1 THEN 'RUTINARIO' 
            WHEN 2 THEN 'ELECTIVA'
            WHEN 3 THEN 'PRIORITARIA' 
            WHEN 4 THEN 'MUY URGENTE' 
            WHEN 5 THEN 'CONTROL' 
            WHEN 6 THEN 'PROGRAMADO' 
        END AS PRIORIDAD
    FROM HCNSOLPQX 
    INNER JOIN ADNINGRESO ON HCNSOLPQX.ADNINGRESO = ADNINGRESO.OID 
    INNER JOIN GENSERIPS ON HCNSOLPQX.GENSERIPS = GENSERIPS.OID
    INNER JOIN HCNFOLIO ON HCNFOLIO.OID = HCNSOLPQX.HCNFOLIO
    WHERE AINCONSEC = @0 AND HCNUMFOL = @1
`;

//response ---> INGRESO	OID	CODIGO_INTERNO	CODIGO_CUPS	DESCRIPCION	OBSERVACION	CANTIDAD	REQUERIMIENTO	FECHA_SOLICITUD	PRIORIDAD	PENDIENTE6	PENDIENTE7	SERVICIO	OBSERVACION	FECHA_FIN	cambio_cups	usuario	folio
