/**
 * @param -@0 Date (string)
 * @param -@1 Date (string)
 * @returns ConciliacionResponse[] (query)
 */
export const fetchConciliacionesQuery = () => {
  return `
SELECT 
GGC.FECHA,
GGC.OID IDGEST,
GU.OID IDUSU,
GU.USUNOMBRE,
GU.USUDESCRI,
GT.OID IDTERC,
GT.TERNUMDOC,
GT.TERNOMCOM,
GCC.OID,
GCC.NACTACONCI,
GCC.FECHACONC,
GDF.CalendarYear,
GDF.CalendarQuarterOfYear,
GDF.MonthNumberOfYear,
DATEDIFF(DAY, GDF.DATE, GETDATE()) Dias,
GCC.VALCONCI,
GCC.VALRECPAG,
GCC.VALGLOSAD,
GCC.VALDEVUEL,
GCC.VALNORADI,
GCC.AUDITORIA,
GCC.RETENCION,
GCC.GLOSACEPTIPS,
GCC.NOTNODESCEPS,
GCC.PAGNOAPLI,
GCC.COPCUOMODE,
GCC.VALCANCEL,
GCC.TOTAL,
GCC.DIFEREN,
GCC.RUTARCHI,
GCC.ESTADO
FROM GCMCONCCART GCC
INNER JOIN GCMGESCART GGC ON GCC.GCMGESCART = GGC.OID
INNER JOIN GCMDIMFECHA GDF ON CONVERT(DATE, GGC.FECHCONCI, 103) = GDF.Date
INNER JOIN GENUSUARIO GU ON GGC.GENUSUARIO = GU.OID
INNER JOIN GENTERCER GT ON GGC.GENTERCER = GT.OID
WHERE CONVERT(DATE, FECHA, 103) BETWEEN @0 AND @1 ORDER BY GGC.FECHA DESC;`;
};
