/**
 * @param -@0 Date (string)
 * @param -@1 Date (string)
 * @returns GestionResponse[] (query)
 */
export const fetchGestionesQuery = () => {
  return `SELECT 
G.OID,
G.GENUSUARIO,
U.USUNOMBRE,
U.USUDESCRI,
G.FECHA,
G.GENTERCER,
T.TERNOMCOM,
G.TELEFTERC,
G.RESPTERC,
G.MOTLLAMAD,
G.OBSERVACION,
G.FECHCONCI,
G.TIPCONCI
FROM GCMGESCART G
INNER JOIN GENUSUARIO U  ON U.OID = G.GENUSUARIO
INNER JOIN GENTERCER T ON T.OID = G.GENTERCER
WHERE CONVERT(DATE, FECHA, 103) BETWEEN @0 AND @1 -- AND G.DELETEAT IS NULL
ORDER BY G.FECHA DESC`;
};
