/** Productos físicos como origen; el servicio consolida por agrupamiento y sede. */
// null indica todos los almacenes de la sede; una lista vacía es una configuración inválida.
export const reporteConsumoQuery = (almacenes: readonly number[] | null): string => {
  if (
    almacenes !== null &&
    (!Array.isArray(almacenes) ||
      !almacenes.length ||
      almacenes.some(id => !Number.isSafeInteger(id) || id <= 0))
  ) {
    throw new Error('Almacenes de reporte invalidos');
  }
  const filtroAlmacenes = almacenes === null ? '' : ` AND A.OID IN (${almacenes.join(', ')})`;
  return `
DECLARE @corte date = CONVERT(date, @0, 23);
WITH Consumo AS (
  SELECT M.INNPRODUC,
    SUM(CASE WHEN D.IDFECDOC >= DATEADD(day, -15, @corte) AND D.IDFECDOC < @corte THEN M.IDDCANTID ELSE 0 END) AS CANTIDAD_15_DIAS,
    SUM(CASE WHEN D.IDFECDOC >= DATEADD(day, -7, @corte) AND D.IDFECDOC < @corte THEN M.IDDCANTID ELSE 0 END) AS CANTIDAD_7_DIAS,
    MAX(D.IDFECDOC) AS ULTIMA_FECHA_SUMINISTRO
  FROM INNCSUMPA C
  INNER JOIN INNMSUMPA M ON M.INNCSUMPA = C.OID
  INNER JOIN INNDOCUME D ON D.OID = C.OID
  INNER JOIN INNALMACE A ON A.OID = C.INNALMACE
  WHERE D.IDESTADO = 1 AND D.IDFECDOC <= GETDATE()
    AND A.ACACODIGO = @1${filtroAlmacenes}
  GROUP BY M.INNPRODUC
), Existencia AS (
  SELECT F.INNPRODUC, SUM(F.IFICANTID) AS EXISTENCIA_ACTUAL
  FROM INNFISICO F
  INNER JOIN INNALMACE A ON A.OID = F.INNALMACE
  WHERE A.ACACODIGO = @1${filtroAlmacenes}
  GROUP BY F.INNPRODUC
)
SELECT P.OID AS PRODUCTOID, P.IPRCODIGO AS CODIGOPRODUCTO,
  P.IPRDESCOR AS DESCRIPCIONPRODUCTO, P.IPRBLOQUEO AS BLOQUEADO,
  AGR.OID AS AGRUPAMIENTOID, AGR.AGRCODIGO AS CODIGOAGRUPAMIENTO,
  AGR.AGRNOMBRE AS NOMBREAGRUPAMIENTO, G.IGRNOMBRE AS GRUPO,
  COALESCE(C.CANTIDAD_15_DIAS, 0) AS CANTIDAD_15_DIAS,
  COALESCE(C.CANTIDAD_7_DIAS, 0) AS CANTIDAD_7_DIAS,
  COALESCE(F.EXISTENCIA_ACTUAL, 0) AS EXISTENCIA_ACTUAL,
  C.ULTIMA_FECHA_SUMINISTRO,
  P.IPRFEULCO AS ULTIMA_COMPRA
FROM INNPRODUC P
LEFT JOIN INNAGRUPAMI AGR ON AGR.OID = P.INNAGRUPAMI
LEFT JOIN INNGRUPO G ON G.OID = P.IGRCODIGO
LEFT JOIN Consumo C ON C.INNPRODUC = P.OID
LEFT JOIN Existencia F ON F.INNPRODUC = P.OID
WHERE P.IGRCODIGO IN (1, 2)
ORDER BY P.OID`;
};

/** Los despachos recientes son avisos, nunca recepciones ni descuentos de stock. */
export const referenciasConsumoQuery = () => `
SELECT I.INNPRODUC AS PRODUCTOID, S.OID AS SOLICITUDID,
  S.NUMEROSOLICITUD,
  CASE WHEN S.ESTADO IN (1, 2) AND I.ESTADODESPACHO IN (1, 2)
    THEN CASE WHEN I.CANTIDAD - COALESCE(I.CANTIDADENVIADA, 0)
      - COALESCE(I.CANTIDADRECHAZADA, 0) - COALESCE(I.CANTIDADSOBREPEDIDO, 0) > 0
      THEN I.CANTIDAD - COALESCE(I.CANTIDADENVIADA, 0)
      - COALESCE(I.CANTIDADRECHAZADA, 0) - COALESCE(I.CANTIDADSOBREPEDIDO, 0)
      ELSE 0 END
    ELSE 0 END AS PENDIENTE,
  COALESCE(D.CANTIDAD, 0) AS DESPACHADORECIENTE,
  D.FECHA AS ULTIMODESPACHO
FROM EKINNSOLPEPROD I
INNER JOIN EKINNSOLPE S ON S.OID = I.SOLICITUDPEDIDOID
LEFT JOIN (
  SELECT SOLPEPRODID, SUM(CANTIDAD) AS CANTIDAD, MAX(FECHACREAC) AS FECHA
  FROM EKINNSOLPEPRODDESP
  WHERE FECHACREAC >= DATEADD(day, -15, CONVERT(date, @0, 23))
    AND FECHACREAC <= GETDATE()
  GROUP BY SOLPEPRODID
) D ON D.SOLPEPRODID = I.OID
WHERE S.SEDE = @1 AND ((S.ESTADO IN (1, 2) AND I.ESTADODESPACHO IN (1, 2)) OR D.FECHA IS NOT NULL)`;
