export function getReporteCentro() {
  return `
    SELECT 
year(inkfecha) as año,month(inkfecha) as mes,AGRCODIGO AS 'COD AGRUPAMIENTO', AGRNOMBRE AS 'NOM AGRUPAMIENTO',iprcodigo, IPRDESCOR, 
isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202605 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0) AS APROVECHAMIENTO,
Sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) as ENTRADA,
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end) as 'SALIDA SIN FORMULA',
case when (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202605 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0))) <=  0 then '0' else (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202605 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) end as 'SALIDA CORREGIDA',
isnull((select SUM(INKCANTID) from INKD202605 INS1 inner join INNDOCUME D on D.oid= INS1.INNDOCUME inner join INNPRODUC P on P.oid = INS1.INNPRODUC inner join INNORDDESC O on O.oid = D.OID  where IDTIPDOC=17 and INS1.INNALMACE IN (2,39) AND INS1.innproduc = INS.INNPRODUC and IODTIPOORDEN='1' and INKTIPMOV='1'),0) AS 'DESPACHO CONSUMO',
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202605 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) AS 'SALIDA FV',
(Select sum(INNFISICO.IFICANTID) From INNPRODUC I Inner Join INNFISICO On I.OID = INNFISICO.INNPRODUC where i.IPRCODIGO=INNPRODUC.IPRCODIGO  AND INNALMACE IN (2,39) group by INNFISICO.INNPRODUC)AS 'EXISTENCIA ACTUAL',
INNGRUPO.IGRNOMBRE
FROM INKD202605 INS 
left JOIN INNPRODUC ON INS.INNPRODUC = INNPRODUC.OID left JOIN INNDOCUME ON INNDOCUME.OID = INS.INNDOCUME left JOIN INNAGRUPAMI ON INNAGRUPAMI.OID = INNPRODUC.INNAGRUPAMI left join inngrupo on INNPRODUC.igrcodigo=inngrupo.oid
where INNPRODUC.IGRCODIGO in (1,2) AND ins.INNALMACE IN (2,39)  and IDTIPDOC not in ('10','17','21','14','15','16') 
--and AGRCODIGO='N20004'
group by year(inkfecha) ,month(inkfecha) ,AGRCODIGO,AGRNOMBRE,IPRCODIGO,IPRDESCOR,INNAGRUPAMI.oid,INS.INNPROduc,INNGRUPO.IGRNOMBRE
UNION

SELECT 
year(inkfecha) as año,month(inkfecha) as mes,AGRCODIGO AS 'COD AGRUPAMIENTO', AGRNOMBRE AS 'NOM AGRUPAMIENTO',iprcodigo, IPRDESCOR, 
isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202606 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0) AS APROVECHAMIENTO,
Sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) as ENTRADA,
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end) as 'SALIDA SIN FORMULA',
case when (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202606 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0))) <=  0 then '0' else (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202606 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) end as 'SALIDA CORREGIDA',
isnull((select SUM(INKCANTID) from INKD202606 INS1 inner join INNDOCUME D on D.oid= INS1.INNDOCUME inner join INNPRODUC P on P.oid = INS1.INNPRODUC inner join INNORDDESC O on O.oid = D.OID  where IDTIPDOC=17 and INS1.INNALMACE IN (2,39) AND INS1.innproduc = INS.INNPRODUC and IODTIPOORDEN='1' and INKTIPMOV='1'),0) AS 'DESPACHO CONSUMO',
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202606 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) AS 'SALIDA FV',
(Select sum(INNFISICO.IFICANTID) From INNPRODUC I Inner Join INNFISICO On I.OID = INNFISICO.INNPRODUC where i.IPRCODIGO=INNPRODUC.IPRCODIGO  AND INNALMACE IN (2,39) group by INNFISICO.INNPRODUC)AS 'EXISTENCIA ACTUAL',
INNGRUPO.IGRNOMBRE
FROM INKD202606 INS 
left JOIN INNPRODUC ON INS.INNPRODUC = INNPRODUC.OID left JOIN INNDOCUME ON INNDOCUME.OID = INS.INNDOCUME left JOIN INNAGRUPAMI ON INNAGRUPAMI.OID = INNPRODUC.INNAGRUPAMI left join inngrupo on INNPRODUC.igrcodigo=inngrupo.oid
where INNPRODUC.IGRCODIGO in (1,2) AND ins.INNALMACE IN (2,39)  and IDTIPDOC not in ('10','17','21','14','15','16') 
--and AGRCODIGO='N20004'
group by year(inkfecha) ,month(inkfecha) ,AGRCODIGO,AGRNOMBRE,IPRCODIGO,IPRDESCOR,INNAGRUPAMI.oid,INS.INNPROduc,INNGRUPO.IGRNOMBRE
union
SELECT 
year(inkfecha) as año,month(inkfecha) as mes,AGRCODIGO AS 'COD AGRUPAMIENTO', AGRNOMBRE AS 'NOM AGRUPAMIENTO',iprcodigo, IPRDESCOR, 
isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202607 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0) AS APROVECHAMIENTO,
Sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) as ENTRADA,
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end) as 'SALIDA SIN FORMULA',
case when (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202607 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0))) <=  0 then '0' else (SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202607 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) end as 'SALIDA CORREGIDA',
isnull((select SUM(INKCANTID) from INKD202607 INS1 inner join INNDOCUME D on D.oid= INS1.INNDOCUME inner join INNPRODUC P on P.oid = INS1.INNPRODUC inner join INNORDDESC O on O.oid = D.OID  where IDTIPDOC=17 and INS1.INNALMACE IN (2,39) AND INS1.innproduc = INS.INNPRODUC and IODTIPOORDEN='1' and INKTIPMOV='1'),0) AS 'DESPACHO CONSUMO',
SUM(case when ("INKTIPMOV" = 1) then "INKCANTID" else 0 end)-(isnull((select sum(case when ("INKTIPMOV" = 0) then "INKCANTID" else 0 end) from INKD202607 INS1 left JOIN INNDOCUME ON INNDOCUME.OID = INS1.INNDOCUME where IDTIPDOC='11' and INS1.INNALMACE IN (2,39) and INS1.innproduc = INS.INNPRODUC),0)) AS 'SALIDA FV',
(Select sum(INNFISICO.IFICANTID) From INNPRODUC I Inner Join INNFISICO On I.OID = INNFISICO.INNPRODUC where i.IPRCODIGO=INNPRODUC.IPRCODIGO  AND INNALMACE IN (2,39) group by INNFISICO.INNPRODUC)AS 'EXISTENCIA ACTUAL',
INNGRUPO.IGRNOMBRE
FROM INKD202607 INS 
left JOIN INNPRODUC ON INS.INNPRODUC = INNPRODUC.OID left JOIN INNDOCUME ON INNDOCUME.OID = INS.INNDOCUME left JOIN INNAGRUPAMI ON INNAGRUPAMI.OID = INNPRODUC.INNAGRUPAMI left join inngrupo on INNPRODUC.igrcodigo=inngrupo.oid
where INNPRODUC.IGRCODIGO in (1,2) AND ins.INNALMACE IN (2,39)  and IDTIPDOC not in ('10','17','21','14','15','16') 
--and AGRCODIGO='N20004'
group by year(inkfecha) ,month(inkfecha) ,AGRCODIGO,AGRNOMBRE,IPRCODIGO,IPRDESCOR,INNAGRUPAMI.oid,INS.INNPROduc,INNGRUPO.IGRNOMBRE
    `;
}
