const MESES_REPORTE = [
  { anio: 2026, mes: 5, tabla: 'INKD202605' },
  { anio: 2026, mes: 6, tabla: 'INKD202606' },
  { anio: 2026, mes: 7, tabla: 'INKD202607' },
] as const;

const crearConsultaMes = (anio: number, mes: number, tabla: string, almacenes: string): string => `
SELECT
  ${anio} AS ANO,
  ${mes} AS MES,
  AGR.AGRCODIGO AS COD_AGRUPAMIENTO,
  AGR.AGRNOMBRE AS NOM_AGRUPAMIENTO,
  P.IPRCODIGO,
  P.IPRDESCOR,
  COALESCE(M.APROVECHAMIENTO, 0) AS APROVECHAMIENTO,
  COALESCE(M.ENTRADA, 0) AS ENTRADA,
  COALESCE(M.SALIDA_SIN_FORMULA, 0) AS SALIDA_SIN_FORMULA,
  CASE
    WHEN COALESCE(M.SALIDA_SIN_FORMULA, 0) - COALESCE(M.APROVECHAMIENTO, 0) < 0 THEN 0
    ELSE COALESCE(M.SALIDA_SIN_FORMULA, 0) - COALESCE(M.APROVECHAMIENTO, 0)
  END AS SALIDA_CORREGIDA,
  COALESCE(C.DESPACHO_CONSUMO, 0) AS DESPACHO_CONSUMO,
  COALESCE(M.SALIDA_SIN_FORMULA, 0) - COALESCE(M.APROVECHAMIENTO, 0) AS SALIDA_FV,
  COALESCE(F.EXISTENCIA_ACTUAL, 0) AS EXISTENCIA_ACTUAL,
  G.IGRNOMBRE
FROM INNPRODUC P
LEFT JOIN INNAGRUPAMI AGR ON AGR.OID = P.INNAGRUPAMI
LEFT JOIN INNGRUPO G ON G.OID = P.IGRCODIGO
LEFT JOIN (
  SELECT
    MOV.INNPRODUC,
    SUM(CASE WHEN MOV.INKTIPMOV = 0 AND D.IDTIPDOC NOT IN ('10', '17', '21', '14', '15', '16') THEN MOV.INKCANTID ELSE 0 END) AS ENTRADA,
    SUM(CASE WHEN MOV.INKTIPMOV = 1 AND D.IDTIPDOC NOT IN ('10', '17', '21', '14', '15', '16') THEN MOV.INKCANTID ELSE 0 END) AS SALIDA_SIN_FORMULA,
    SUM(CASE WHEN MOV.INKTIPMOV = 0 AND D.IDTIPDOC = '11' THEN MOV.INKCANTID ELSE 0 END) AS APROVECHAMIENTO
  FROM ${tabla} MOV
  LEFT JOIN INNDOCUME D ON D.OID = MOV.INNDOCUME
  WHERE MOV.INNALMACE IN (${almacenes})
  GROUP BY MOV.INNPRODUC
) M ON M.INNPRODUC = P.OID
LEFT JOIN (
  SELECT MOV.INNPRODUC, SUM(MOV.INKCANTID) AS DESPACHO_CONSUMO
  FROM ${tabla} MOV
  INNER JOIN INNDOCUME D ON D.OID = MOV.INNDOCUME
  INNER JOIN INNORDDESC O ON O.OID = D.OID
  WHERE MOV.INNALMACE IN (${almacenes})
    AND MOV.INKTIPMOV = 1
    AND D.IDTIPDOC = '17'
    AND O.IODTIPOORDEN = '1'
  GROUP BY MOV.INNPRODUC
) C ON C.INNPRODUC = P.OID
LEFT JOIN (
  SELECT FIS.INNPRODUC, SUM(FIS.IFICANTID) AS EXISTENCIA_ACTUAL
  FROM INNFISICO FIS
  WHERE FIS.INNALMACE IN (${almacenes})
  GROUP BY FIS.INNPRODUC
) F ON F.INNPRODUC = P.OID
WHERE P.IGRCODIGO IN (1, 2)`;

/**
 * INNPRODUC es la tabla padre para conservar productos sin movimientos en el
 * periodo. Cada bloque mensual retorna exactamente una fila por producto.
 */
export const crearQueryReporteInventario = (almacenes: readonly number[]): string => {
  if (almacenes.length === 0) {
    throw new Error('El reporte requiere al menos un almacen configurado');
  }

  const almacenesSql = almacenes.join(', ');
  return MESES_REPORTE.map(({ anio, mes, tabla }) =>
    crearConsultaMes(anio, mes, tabla, almacenesSql)
  ).join('\nUNION ALL\n');
};
