export const FetchReportesCirugiasQuery = () => {
  return `
    SELECT P.GPANOMCOM , I.AINFECING, f.OID, f.HCFECFOL, UC.HCCM02N12, UC.HCCM03N13 FROM HPNESTANC E
    INNER JOIN ADNINGRESO I ON E.ADNINGRES = I.OID 
    INNER JOIN GENPACIEN P ON I.GENPACIEN = P.OID
    INNER JOIN HCNFOLIO F ON F.ADNINGRESO = I.OID
    INNER JOIN HCNTIPHIS  TH ON F.HCNTIPHIS = TH.OID
    INNER JOIN HCMDESCQX UC ON UC.HCNFOLIO = F.OID
    WHERE HESFECSAL IS NULL AND TH.HCNOMBRE = 'DESCRIPCION QUIRURGICA'`;
};
