export const fetchInfoIngresoQuery = (consecutivo: number, fecha: Date) => {
  const fechaFt = fecha.toISOString().split('T')[0];
  return `
  Select TOP(1)
ADNINGRESO.AINCONSEC,
ADNINGRESO.OID,
HPNDEFCAM.HCACODIGO,
HPNGRUPOS.HGRNOMBRE,
GENPACIEN.PACNUMDOC,
GENPACIEN.GPANOMCOM,
HCNREGENF.HCFECREG,
GENDETCON.GDENOMBRE,
HCNREGENF.HCRPESO PESO
  From ADNINGRESO
    Left Join HPNDEFCAM On HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
    Left Join HPNSUBGRU On HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
    Left Join GENARESER On GENARESER.OID = HPNSUBGRU.GENARESER
    Left Join HPNGRUPOS On HPNGRUPOS.OID = HPNDEFCAM.HPNGRUPOS
    Left Join GENPACIEN On GENPACIEN.OID = ADNINGRESO.GENPACIEN
    Left Join HCNREGENF On ADNINGRESO.OID = HCNREGENF.ADNINGRESO
    Left Join GENDETCON On GENDETCON.OID = ADNINGRESO.GENDETCON
    Where ADNINGRESO.AINCONSEC IN (${consecutivo}) And HCNREGENF.HCFECREG = '${fechaFt}'
  ORDER BY PESO DESC;
  `;
};

export const fetchLiquidosQuery = (consecutivos: number[], fecha: Date) => {
  const fechaFt = fecha.toISOString().split('T')[0];
  return `
  SELECT HCNTIPLQEL.HCLNOMBRE LIQUIDO,
        DatePart(HOUR, HCNLIQELM.HCRHORREG) HORA,
        HCNLIQELM.HCLCANTID CANTIDAD,
        HCNLIQELM.HCLVIAELM,
        'LIQUIDOS ELIMINADOS' SUBGRUPO FROM HCNREGENF
        Inner Join HCNLIQELM ON HCNREGENF.OID = HCNLIQELM.HCNREGENF
        Inner Join ADNINGRESO ON ADNINGRESO.OID = HCNREGENF.ADNINGRESO
        Inner Join HCNTIPLQEL ON HCNTIPLQEL.OID = HCNLIQELM.HCNTIPLQEL
        WHERE HCNREGENF.HCFECREG='${fechaFt}' AND ADNINGRESO.AINCONSEC IN (${consecutivos}) 
        UNION
        SELECT HCNLIQADM.HCLLIQNOM LIQUIDO,
        DatePart(HOUR, HCNLIQADM.HCRHORREG) HORA,
        HCNLIQADM.HCLCANTID CANTIDAD,
        null as HCLVIAELM,
        'LIQUIDOS ADMINISTRADOS' SUBGRUPO FROM HCNREGENF
        Inner Join HCNLIQADM ON HCNREGENF.OID = HCNLIQADM.HCNREGENF
        Inner Join ADNINGRESO ON ADNINGRESO.OID = HCNREGENF.ADNINGRESO
        WHERE HCNREGENF.HCFECREG='${fechaFt}' AND ADNINGRESO.AINCONSEC IN (${consecutivos}) ORDER BY SUBGRUPO ASC;`;
};

export const fetchSignosVitalesQuery = (consecutivos: number[], fecha: Date) => {
  const fechaFt = fecha.toISOString().split('T')[0];
  return `
  Select HORAS_DIA.HORA hora,
      CONSOLIDADO.SIGNO,
      CONSOLIDADO.VALOR valor
      From HORAS_DIA
      Left Join (Select DatePart(HOUR, HCNSIGVIT.HCRHORREG) HORAREG,
        HCNTIPSVIT.HCSDESCRI SIGNO,
        HCNSIGVIT.HCSVALOR VALOR,
        0 As PESO,
        HCNREGENF.HCFECREG FECHA_REGISTRO_ENF
      From HCNREGENF
        Inner Join HCNSIGVIT On HCNREGENF.OID = HCNSIGVIT.HCNREGENF
        Inner Join HCNTIPSVIT On HCNTIPSVIT.OID = HCNSIGVIT.HCNTIPSVIT
        Inner Join ADNINGRESO On ADNINGRESO.OID = HCNREGENF.ADNINGRESO
      Where HCNREGENF.HCFECREG = '${fechaFt}' And ADNINGRESO.AINCONSEC IN
      (${consecutivos})) As CONSOLIDADO On CONSOLIDADO.HORAREG = HORAS_DIA.hora 
        Where CONSOLIDADO.HORAREG Is Not Null order by oid`;
};

export const fetchGlucometriasQuery = (consecutivos: number[], fecha: Date) => {
  const fechaFt = fecha.toISOString().split('T')[0];
  return `
  Select HORAS_DIA.hora,
          CONSOLIDADO.RESULTADO valor,
          CONSOLIDADO.OBSERVACION observacion,
        CASE CONSOLIDADO.INSULINA
        WHEN -1 THEN 'NINGUNA'
        WHEN 0 THEN 'CRISTALINA'
        WHEN 1 THEN 'NPH'
        WHEN 2 THEN '70 30'
        WHEN 3 THEN 'GLARGINA'
        WHEN 4 THEN 'OTROS'
        WHEN 5 THEN 'LISPRO'
        WHEN 6 THEN 'GLULISINA'
        WHEN 7 THEN 'ASPART'
        WHEN 8 THEN 'DETEMIRT'
        END
        AS insulina,
        CONSOLIDADO.CANTIDAD cantidad
          From HORAS_DIA
          Left Join (
        Select DatePart(HOUR, HCNGLUCOM.HCRHORREG) HORAREG,
            HCNGLUCOM.HCGRESGLU RESULTADO,
            HCNGLUCOM.HCGOBSERV OBSERVACION,
        HCNGLUCOM.HCGINSUTIP INSULINA,
        HCNGLUCOM.HCGINSUNI CANTIDAD
          From HCNREGENF
            Inner Join HCNGLUCOM On HCNREGENF.OID = HCNGLUCOM.HCNREGENF
            Inner Join ADNINGRESO On ADNINGRESO.OID = HCNREGENF.ADNINGRESO
            Left Join HPNDEFCAM On HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
            Left Join HPNSUBGRU On HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
            Left Join GENARESER On GENARESER.OID = HPNSUBGRU.GENARESER
            Left Join HPNGRUPOS On HPNGRUPOS.OID = HPNDEFCAM.HPNGRUPOS
          Where CONVERT(DATE, HCNREGENF.HCFECREG, 103) = '${fechaFt}' And (1 = 1) And ADNINGRESO.AINCONSEC IN (${consecutivos})
        )As CONSOLIDADO On CONSOLIDADO.HORAREG = HORAS_DIA.hora`;
};
