export const getEgresosFacturacionQuery = (banderaPermisos: boolean, id: number) => {
  const query = `
    SELECT DISTINCT 
        ADNINGRESO.AINCONSEC AS NUMERO_INGRESO,
        ADNEGRESO.ADENUMEGR AS NUMERO_EGRESO,
        CASE adningreso.adncenate
            WHEN 1 THEN 'CENTRO MEDICO'
            WHEN 2 THEN 'ALTA COMPLEJIDAD'
            WHEN 3 THEN 'CAPS'
        END AS SEDE,
        adningreso.ADNCENATE,
        AINFECING AS FECHA_INGRESO,
        ADNEGRESO.ADEFECSAL AS FECHA_EGRESO,
        CASE ADNINGRESO.AINURGCON
            WHEN 0 THEN 'URGENCIA'
            WHEN 1 THEN 'CONSULTA EXTERNA'
            WHEN 2 THEN 'NACIDO HOSPITAL'
            WHEN 3 THEN 'REMITIDO'
            WHEN 4 THEN 'HOSPITALIZACIÓN URGENCIA'
            WHEN 5 THEN 'HOSPITALIZACION'
            WHEN 6 THEN 'IMAGENES'
            WHEN 7 THEN 'LABORATORIO'
            WHEN 8 THEN 'URGENCIA GINECOLOGICA'
            WHEN 9 THEN 'QUIROFANO'
            WHEN 10 THEN 'CIRUGÍA AMBULATORIA'
            WHEN 11 THEN 'CIRUGÍA PROGRAMADA'
        END AS 'INGRESO_POR',
        GENPACIEN.PACNUMDOC AS IDENTIFICACION,
        GENPACIEN.GPANOMCOM AS PACIENTE,
        DATEDIFF (YEAR, genpacien.GPAFECNAC, GETDATE()) AS EDAD,
        GENDETCON.GDENOMBRE AS EPS,
        ADNEGRESER.ADESNOMBRE AS AREA_EGRESO,
        HPNDEFCAM.HCACODIGO AS CODIGO_CAMA,
        HPNDEFCAM.HCANOMBRE AS NOMBRE_CAMA,
        HPNSUBGRU.HSUCODIGO AS CODIGO_SUBGRUPO,
        HPNSUBGRU.HSUNOMBRE AS NOMBRE_SUBGRUPO,
        YEAR(ADNEGRESO.ADEFECSAL) AS AÑO_EGRESO,
        CASE MONTH(ADEFECSAL)
            WHEN 1 THEN 'ENE'
            WHEN 2 THEN 'FEB'
            WHEN 3 THEN 'MAR'
            WHEN 4 THEN 'ABR'
            WHEN 5 THEN 'MAY'
            WHEN 6 THEN 'JUN'
            WHEN 7 THEN 'JUL'
            WHEN 8 THEN 'AGO'
            WHEN 9 THEN 'SEP'
            WHEN 10 THEN 'OCT'
            WHEN 11 THEN 'NOV'
            WHEN 12 THEN 'DIC'
        END AS MES_EGRESO,
        DAY(ADNEGRESO.ADEFECSAL) AS DIA_EGRESO,
        --V_HCNINDMED.GMENOMCOM ,
        --genespeci.geedescri AS ESPECIALIDAD_MEDICO,
		(select TOP(1) V_HCNINDMED.GMENOMCOM FROM V_HCNINDMED WHERE V_HCNINDMED.ADNINGRESO=ADNINGRESO.AINCONSEC ORDER BY V_HCNINDMED.HCNFOLIO DESC) AS MEDICO_INDICO_SALIDA,
		(select TOP(1) V_HCNINDMED.GEEDESCRI FROM V_HCNINDMED WHERE V_HCNINDMED.ADNINGRESO=ADNINGRESO.AINCONSEC ORDER BY V_HCNINDMED.HCNFOLIO DESC) AS ESPECIALIDAD_MEDICO,
        GENUSUARIO.USUDESCRI AS USUARIO_CREO_EGRESO,
        GENROL.ROLNOMBRE AS ROL_USUARIO,
        (
        SELECT count(*)
        FROM hcmdescqx
            INNER JOIN HCNFOLIO ON HCNFOLIO.OID=hcmdescqx.HCNFOLIO
            WHERE HCNFOLIO.ADNINGRESO=ADNINGRESO.OID) AS CANT_PQX,
        SLNORDSAL.SRACONSEC AS ORDEN_SALIDA,
        SLNORDSAL.SRAFECSAL AS FECHA_ORDEN_SALIDA,
        HCNEPICRI.HCECONSEC AS NUMERO_EPICRISIS,
        HCNEPICRI.HCEFECDOC AS FECHA_EPICRISIS,
        CASE 
            WHEN EKSLNEGRFACASIG.ESTADO IS NOT NULL THEN 
                CASE EKSLNEGRFACASIG.ESTADO
                    WHEN 1 THEN 'PENDIENTE'
                    WHEN 2 THEN 'ASIGNADO'
                    WHEN 3 THEN 'FACTURADO'
                    ELSE 'POR FACTURAR'
                END
            WHEN EKSLNEGRFACPEN.ESTADO IS NOT NULL THEN 
                CASE EKSLNEGRFACPEN.ESTADO
                    WHEN 1 THEN 'PENDIENTE'
                    WHEN 2 THEN 'ASIGNADO'
                    WHEN 3 THEN 'FACTURADO'
                    ELSE 'POR FACTURAR'
                END
            ELSE 'POR FACTURAR'
        END AS ESTADO,
        CASE EKSLNEGRFACPEN.ESTADO
                    WHEN 1 THEN 'PENDIENTE'
                    WHEN 2 THEN 'ASIGNADO'
                    WHEN 3 THEN 'FACTURADO'
                    ELSE 'POR FACTURAR'
                END AS ESTADO_PENDIENTE,
        CASE EKSLNEGRFACASIG.ESTADO
                    WHEN 1 THEN 'PENDIENTE'
                    WHEN 2 THEN 'ASIGNADO'
                    WHEN 3 THEN 'FACTURADO'
                    ELSE 'POR FACTURAR'
                END AS ESTADO_ASIGNADO,
		EKSLNEGRFACPEN.MOTIVONOFACTURACION AS MOTIVONOFACTURACION,
		EKSLNEGRFACPEN.OBSERVACION AS OBSERVACIONPENDIENTE,
		EKSLNEGRFACASIG.TIPOCUENTA AS TIPOCUENTA,
		EKSLNEGRFACASIG.OBSERVACION AS OBSERVACIONASIGNAR,
        EKSLNEGRFACASIG.USUARIOASIGNADO AS USUARIOASIGNADO,
        EKSLNEGRFACASIG.FECHA AS FECHAREGISTROASIGNADO,
        EKSLNEGRFACPEN.FECHA AS FECHAMOTIVONOFACTURACION,
		CASE EKINNFMCCGT.ESTADO
			WHEN 1 THEN 'PENDIENTE'
			WHEN 2 THEN 'EN TRAMITE'
			WHEN 3 THEN 'PRODUCTOS POR FACTURAR'
			WHEN 4 THEN 'FINALIZADO'
			WHEN 5 THEN 'RECHAZADO'
			WHEN 6 THEN 'INICIADO'
			ELSE 'NO MAOS'
		END AS ESTADO_CONTROL_GASTO,
        ADNINGRESO.AINESTADO AS ESTADO_ADNINGRESO

    FROM ADNEGRESO
    INNER JOIN ADNEGRESER ON ADNEGRESER.OID = ADNEGRESO.ADNEGRESER
    INNER JOIN ADNINGRESO ON ADNINGRESO.OID = ADNEGRESO.ADNINGRESO
    INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
    INNER JOIN GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
    LEFT JOIN HPNDEFCAM ON HPNDEFCAM.OID = ADNINGRESO.HPNDEFCAM
    LEFT JOIN HPNSUBGRU ON HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
    LEFT JOIN GENUSUARIO ON GENUSUARIO.OID= ADNEGRESO.GEENUSUARIO
    LEFT JOIN GENROL ON GENROL.OID= GENUSUARIO.GENROL
    --LEFT JOIN V_HCNINDMED ON V_HCNINDMED.ADNINGRESO= ADNINGRESO.OID
    --LEFT JOIN genespeci ON V_HCNINDMED.genespeci=genespeci.oid
    LEFT JOIN SLNORDSAL ON SLNORDSAL.ADNINGRES1=ADNINGRESO.OID
    LEFT JOIN HCNEPICRI ON HCNEPICRI.ADNINGRESO=ADNINGRESO.OID
    LEFT JOIN EKSLNEGRFACPEN ON EKSLNEGRFACPEN.ADNINGRESO=ADNINGRESO.AINCONSEC
    LEFT JOIN EKSLNEGRFACASIG ON EKSLNEGRFACASIG.ADNINGRESO = ADNINGRESO.AINCONSEC
    LEFT JOIN EKINNFMCCGT AS EKINNFMCCGT ON EKINNFMCCGT.INGRESO = ADNINGRESO.AINCONSEC
    WHERE CAST(ADNEGRESO.ADEFECSAL AS DATE) BETWEEN @0 AND @1 

    ${!banderaPermisos ? '  AND EKSLNEGRFACASIG.USUARIOASIGNADO = ' + id + ' ' : ''}
    ORDER BY AINCONSEC
`;

  return query;
};
