export enum GcmContexts {
  SANJUAN = 'SANJUAN',
  EKLIPSE = 'EKLIPSE',
  AGUACHICA = 'AGUACHICA',
  AMMEDICAL = 'AMMEDICAL',
  ALTACENTRO = 'ALTACENTRO',
  VALLEDUPAR = 'VALLEDUPAR',
  DEVELOPMENT = 'DEVELOPMENT',
}
