export const TipoContextoArchivo = {
  REGISTRO_FOTOGRAFICO_EQUIPO: 'REG_FOTO_EQP',
  DOCUMENTO_TIPO_EQUIPO_SOPORTE: 'DOC_TEQP_SOP',
  DOCUMENTO_TIPO_EQUIPO_MANUAL: 'DOC_TEQP_MAN',
  DOCUMENTO_TRANSACCIONAL_SOPORTE: 'DOC_COMPRA_SOP',
  EVIDENCIA_TANQUEO: 'EVID_TANQUEO',
  ACTA_EQUIPO: 'ACTA_EQPS',
  MANTENIMIENTO: 'MANT',
  FIRMA: {
    USR: 'FIRM_USR',
    TERCERO: 'FIRM_TERC',
    REG_DILIGENCIADO: {
      ACTIVIDAD: 'DILGO_ACTIVIDAD',
    },
  },
} as const;
