import { INN_MODULES } from './common';

export const COTIZACIONES_PREFABRICADAS_AUTHS = {
  CODE: INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS,
  REGISTRAR_SET: `${INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS}001`,
  ADD_PROVEEDOR_TO_SET: `${INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS}002`,
};
