import { INN_MODULES } from './common';

export const FARMACIA_AUTHS = {
  CODE: INN_MODULES.SUBS.FARMACIA,
  GESTION_INVENTARIO_CICLICO: `${INN_MODULES.SUBS.FARMACIA}001`,
  VERIFICAR_INVENTARIO_CICLICO: `${INN_MODULES.SUBS.FARMACIA}002`,
  GESTION_DEMANDAS_INSATISFECHAS: `${INN_MODULES.SUBS.FARMACIA}003`,
  CONTROL_GASTOS_SOLICITANTE: `${INN_MODULES.SUBS.FARMACIA}004`,
  CONTROL_GASTOS_FACTURADOR: `${INN_MODULES.SUBS.FARMACIA}005`,
  LEGALIZACION_FACTURAS_SOLICITANTE: `${INN_MODULES.SUBS.FARMACIA}006`,
  LEGALIZACION_FACTURAS_FACTURADOR: `${INN_MODULES.SUBS.FARMACIA}007`,
  INVENTARIO_ADMIN: `${INN_MODULES.SUBS.FARMACIA}008`,
  INVENTARIO_CONTEO: `${INN_MODULES.SUBS.FARMACIA}009`,
  REPORTE_INVENTARIO: `${INN_MODULES.SUBS.FARMACIA}010`,
};
