import { INN_MODULES } from './common';

export const RECEPCION_TECNICA_AUTHS = {
  CODE: INN_MODULES.SUBS.RECEPCION_TECNICA,
  GENERAR_CONSULTAR_RECEPC_TECN: `${INN_MODULES.SUBS.RECEPCION_TECNICA}001`,
};
