import { INN_MODULES } from './common';

export const SERVICIO_TECNICO_AUTHS = {
  CODE: INN_MODULES.SUBS.SERVICIO_TECNICO,
  AGREGAR_SOLICITUDES: `${INN_MODULES.SUBS.SERVICIO_TECNICO}001`,
  ATENDER_SOLICITUDES: `${INN_MODULES.SUBS.SERVICIO_TECNICO}002`,
  MANAGE_TIPOS_TO_USUARIOS: `${INN_MODULES.SUBS.SERVICIO_TECNICO}003`,
};
