import { INN_MODULES } from './common';

export const SOLICITUD_PEDIDO_AUTHS = {
  CODE: INN_MODULES.SUBS.SOLICITUD_PEDIDO,
  SOLICITAR_PEDIDO: `${INN_MODULES.SUBS.SOLICITUD_PEDIDO}001`,
  FACTURAR_PEDIDO: `${INN_MODULES.SUBS.SOLICITUD_PEDIDO}002`,
};
