import { INN_MODULES } from './common';

export const SUMINISTROS_PACIENTE_AUTHS = {
  CODE: INN_MODULES.SUBS.SUMINISTROS_PACIENTE,
  GESTIONAR: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}001`,
  DISABLED_1: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}002`,
  GESTION_SUM_MEZCLA_DEV: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}003`,
};
