import { INN_MODULES } from './_common';
import { CTC_AUTHS } from './central-compras';

export const INN_AUTHORITIES = {
  CODE: INN_MODULES.CODE,
  RECEPCION_TECNICA: {
    CODE: INN_MODULES.SUBS.RECEPCION_TECNICA,
    GENERAR_CONSULTAR_RECEPC_TECN: `${INN_MODULES.SUBS.RECEPCION_TECNICA}001`,
  },
  DOCUMENTOS: {
    CODE: INN_MODULES.SUBS.DOCUMENTOS,
    GENERAR_RECIBO_ORDEN_DESPACHO: `${INN_MODULES.SUBS.DOCUMENTOS}002`,
  },
  SUMINISTROS_PACIENTE: {
    CODE: INN_MODULES.SUBS.SUMINISTROS_PACIENTE,
    GESTIONAR: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}001`,
    DISABLED_1: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}002`,
    GESTION_SUM_MEZCLA_DEV: `${INN_MODULES.SUBS.SUMINISTROS_PACIENTE}003`,
  },
  CENTRAL_COMPRAS: CTC_AUTHS,
  PRODUCTOS: {
    CODE: INN_MODULES.SUBS.PRODUCTOS,
    GESTION_REPORTES: `${INN_MODULES.SUBS.PRODUCTOS}001`,
  },
  COTIZACIONES_PREFABRICADAS: {
    CODE: INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS,
    REGISTRAR_SET: `${INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS}001`,
    ADD_PROVEEDOR_TO_SET: `${INN_MODULES.SUBS.COTIZACIONES_PREFABRICADAS}002`,
  },
  FARMACIA: {
    CODE: INN_MODULES.SUBS.FARMACIA,
    GESTION_INVENTARIO_CICLICO: `${INN_MODULES.SUBS.FARMACIA}001`,
    VERIFICAR_INVENTARIO_CICLICO: `${INN_MODULES.SUBS.FARMACIA}002`,
    GESTION_DEMANDAS_INSATISFECHAS: `${INN_MODULES.SUBS.FARMACIA}003`,
    CONTROL_GASTOS_SOLICITANTE: `${INN_MODULES.SUBS.FARMACIA}004`,
    CONTROL_GASTOS_FACTURADOR: `${INN_MODULES.SUBS.FARMACIA}005`,
    LEGALIZACION_FACTURAS_SOLICITANTE: `${INN_MODULES.SUBS.FARMACIA}006`,
    LEGALIZACION_FACTURAS_FACTURADOR: `${INN_MODULES.SUBS.FARMACIA}007`,
    INVENTARIO_ADMIN: `${INN_MODULES.SUBS.FARMACIA}008`,
    INVENTARIO_CONTEO: `${INN_MODULES.SUBS.FARMACIA}009`,
    REPORTE_INVENTARIO: `${INN_MODULES.SUBS.FARMACIA}010`,
  },
  SERVICIO_TECNICO: {
    CODE: INN_MODULES.SUBS.SERVICIO_TECNICO,
    AGREGAR_SOLICITUDES: `${INN_MODULES.SUBS.SERVICIO_TECNICO}001`,
    ATENDER_SOLICITUDES: `${INN_MODULES.SUBS.SERVICIO_TECNICO}002`,
    MANAGE_TIPOS_TO_USUARIOS: `${INN_MODULES.SUBS.SERVICIO_TECNICO}003`,
  },
  EQUIPOS: {
    CODE: INN_MODULES.SUBS.EQUIPOS,
  },
};
