export const porMesQuery = `
SELECT 
(
  SUM(CASE WHEN SFATIPDOC IN(0, 1)THEN SFATOTFAC ELSE NULL END)
  - ISNULL(SUM(CASE WHEN SFATIPDOC IN(0, 1) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END), 0)
  + ISNULL(SUM(CASE WHEN SFATIPDOC = 16 AND SFADOCANU = 0 THEN SFATOTFAC ELSE NULL END), 0)
  ) facturadoTotal,
ISNULL(SUM(CASE WHEN (SFATIPDOC = 16 OR C.GDECODIGO IN('8014', '8016')) AND SFADOCANU = 0 THEN SFATOTFAC ELSE NULL END), 0) facturadoPGP,

SUM(CASE WHEN SFADOCANU = 1 AND CONVERT(DATE, SFAFECANU, 103) > @1 THEN SFATOTFAC ELSE NULL END) totalAnuladoPosterior,

SUM(CASE WHEN SFATIPDOC = 17 AND SFADOCANU = 0 THEN SFATOTFAC ELSE NULL END) registroPGP,

SUM(CASE WHEN SFATIPDOC = 17 AND SFADOCANU = 1 AND CONVERT(DATE, SFAFECANU, 103) > @1 THEN SFATOTFAC ELSE NULL END) registroAnuladoPosteriorPGP,

ISNULL(SUM(CASE WHEN CONVERT(DATE, SRFFECFAC, 103) < @0 THEN SRFTOTFAC ELSE NULL END), 0) refacturado

FROM GCVUSUFACTUR
INNER JOIN GENDETCON C ON C.OID = GCVUSUFACTUR.GENDETCON
WHERE
CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1
AND SFACANANU < 1;`;

export const registroPorMesEVENTOSQuery = `

SELECT ISNULL(
SUM(CASE WHEN SFATIPDOC IN(0, 1, 17) THEN SFATOTFAC ELSE NULL END) 
- SUM(CASE WHEN SFATIPDOC IN(0, 1) AND CONVERT(DATE, SFAFECANU, 103) BETWEEN @0 AND @1 THEN SFATOTFAC ELSE NULL END)
, SUM(CASE WHEN SFATIPDOC IN(0, 1, 17) AND SFADOCANU = 0 THEN SFATOTFAC ELSE NULL END)
) TOTAL
FROM GCVUSUFACTUR
INNER JOIN GENDETCON T ON GCVUSUFACTUR.GENDETCON = T.OID
WHERE
CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1
AND SUBSTRING(T.GDECODIGO, 1, 1) != '8'
AND SFACANANU < 1
AND ADNCENATE IN(@2,@3)
GROUP BY SFATIPDOC`;

export const anuladoDespuesQuery = `
SELECT SUM(F.SFATOTFAC) TOTAL
FROM GCVUSUFACTUR F WHERE
CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1
AND SFACANANU < 1
AND ADNCENATE IN(@2, @3)
  AND  CONVERT(DATE, SFAFECANU, 103) > @1
  AND SFATIPDOC IN(0, 1, 17);`;

export const proyectPorMesQuery = `SELECT 
SUM(CASE MONTH(@0)
WHEN 1 THEN CENPROENE
WHEN 2 THEN CENPROFEB
WHEN 3 THEN CENPROMAR
WHEN 4 THEN CENPROABR
WHEN 5 THEN CENPROMAY
WHEN 6 THEN CENPROJUN
WHEN 7 THEN CENPROJUL
WHEN 8 THEN CENPROAGO
WHEN 9 THEN CENPROSEP
WHEN 10 THEN CENPROOCT
WHEN 11 THEN CENPRONOV
WHEN 12 THEN CENPRODIC
ELSE
0
END) META
FROM
GCMCENATEPRO
WHERE 
PERIODO = YEAR(@0)
AND ADNCENATE IN(@2, @3)`;
